// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 Shahzad A. Bhatti <bhatti@plexobject.com>
//
// This file is part of PlexSpaces.
//
// PlexSpaces is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PlexSpaces is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with PlexSpaces. If not, see <https://www.gnu.org/licenses/>.

//! Lock-free pending ask correlation map for the local ask() pattern.
//!
//! Replaces the `ReplyWaiter` + `ReplyWaiterRegistry` + temporary actor
//! approach with a DashMap of oneshot channels keyed by correlation_id.
//! Each ask inserts one entry; the background GC sweeps expired entries.
//!
//! ## Tenant isolation
//!
//! Correlation IDs are ULIDs (128-bit, globally unique). Because each ask()
//! generates a fresh ULID, two asks — regardless of tenant — will always have
//! distinct keys. The isolation guarantee is structural: it is impossible for a
//! reply to land in the wrong pending-ask entry.
//!
//! This is preferable to a tenant-scoped composite key because `resolve()` is
//! called from `dispatch_local_message` with the *replying actor's* context,
//! not the *caller's* context. Those contexts can differ in namespace when an
//! actor is shared across namespaces, which would cause a key mismatch and
//! silent reply loss.

use std::env;
use std::sync::Arc;
use std::time::{Duration, Instant};

use dashmap::DashMap;
use plexspaces_proto::common::v1::Message;
use tokio::sync::oneshot;

/// Default ask timeout when none is specified (30 seconds).
const DEFAULT_ASK_TIMEOUT_SECS: u64 = 30;

/// Environment variable that overrides the default ask timeout in milliseconds.
pub const ASK_TIMEOUT_ENV: &str = "PLEXSPACES_ASK_TIMEOUT_MS";

/// GC sweep interval.
const GC_INTERVAL: Duration = Duration::from_secs(5);

struct PendingAskEntry {
    tx: oneshot::Sender<Message>,
    expires_at: Instant,
}

/// Lock-free registry of in-flight ask() correlations.
///
/// Each `ask()` call registers a oneshot channel keyed by a ULID correlation_id.
/// When the reply arrives at `dispatch_local_message`, it calls `resolve()` to
/// deliver the message directly to the waiting future — no actor object, no
/// mailbox, no HashMap write lock.
///
/// A background tokio task sweeps expired entries every `GC_INTERVAL` seconds.
pub struct PendingAsks {
    entries: DashMap<String, PendingAskEntry>,
    default_timeout: Duration,
}

impl PendingAsks {
    /// Creates a new `PendingAsks` with an explicit default timeout.
    pub fn new(default_timeout: Duration) -> Self {
        PendingAsks {
            entries: DashMap::with_shard_amount(16),
            default_timeout,
        }
    }

    /// Creates `PendingAsks` reading `PLEXSPACES_ASK_TIMEOUT_MS` from the environment.
    /// Falls back to 30 seconds if the variable is absent or invalid.
    pub fn from_env() -> Self {
        let timeout_ms = env::var(ASK_TIMEOUT_ENV)
            .ok()
            .and_then(|v| v.parse::<u64>().ok())
            .unwrap_or(DEFAULT_ASK_TIMEOUT_SECS * 1000);
        Self::new(Duration::from_millis(timeout_ms))
    }

    /// Returns the configured default timeout.
    pub fn default_timeout(&self) -> Duration {
        self.default_timeout
    }

    /// Register an in-flight ask and return the receiver half.
    ///
    /// `correlation_id` must be a ULID generated by the caller. Tenant isolation
    /// is guaranteed by ULID global uniqueness — no two asks will share a key.
    pub fn register(
        &self,
        correlation_id: String,
        timeout: Duration,
    ) -> oneshot::Receiver<Message> {
        let (tx, rx) = oneshot::channel();
        let expires_at = Instant::now() + timeout;
        self.entries
            .insert(correlation_id, PendingAskEntry { tx, expires_at });
        rx
    }

    /// Deliver a reply to the waiting ask.
    ///
    /// Returns `true` if the entry was found and the message delivered.
    /// Returns `false` if the entry is absent (already resolved, expired, or cancelled).
    pub fn resolve(&self, correlation_id: &str, reply: Message) -> bool {
        if let Some((_, entry)) = self.entries.remove(correlation_id) {
            // send() fails only if the receiver was dropped (ask timed out or
            // cancelled by the caller) — that is expected, not an error.
            entry.tx.send(reply).is_ok()
        } else {
            false
        }
    }

    /// Cancel an in-flight ask (e.g. on dispatch error before any reply is expected).
    pub fn cancel(&self, correlation_id: &str) {
        self.entries.remove(correlation_id);
    }

    /// Remove all entries whose deadline has passed.
    ///
    /// Called by the background GC task. Returns the number swept.
    pub fn sweep_expired(&self) -> usize {
        let now = Instant::now();
        let mut count = 0usize;
        self.entries.retain(|_, entry| {
            if entry.expires_at <= now {
                count += 1;
                false
            } else {
                true
            }
        });
        count
    }

    /// Returns the current number of in-flight asks.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Start the background GC task. Call once at node startup.
    pub fn start_gc(self: Arc<Self>) {
        tokio::spawn(async move {
            let mut interval = tokio::time::interval(GC_INTERVAL);
            loop {
                interval.tick().await;
                let swept = self.sweep_expired();
                if swept > 0 {
                    if tracing::enabled!(tracing::Level::DEBUG) {
                        tracing::debug!(
                            swept,
                            remaining = self.entries.len(),
                            "PendingAsks: swept expired entries"
                        );
                    }
                    metrics::counter!("plexspaces_pending_asks_expired_total")
                        .increment(swept as u64);
                }
                metrics::gauge!("plexspaces_pending_asks_inflight")
                    .set(self.entries.len() as f64);
            }
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use plexspaces_proto::common::v1::Message;

    fn make_reply(correlation_id: &str) -> Message {
        Message {
            id: "reply-1".to_string(),
            correlation_id: correlation_id.to_string(),
            message_type: "reply".to_string(),
            ..Default::default()
        }
    }

    #[tokio::test]
    async fn register_and_resolve_delivers_message() {
        let pa = PendingAsks::new(Duration::from_secs(5));
        let rx = pa.register("corr-1".to_string(), Duration::from_secs(5));
        let reply = make_reply("corr-1");
        assert!(pa.resolve("corr-1", reply));
        let received = rx.await.expect("should receive reply");
        assert_eq!(received.correlation_id, "corr-1");
    }

    #[tokio::test]
    async fn resolve_returns_false_for_unknown_correlation() {
        let pa = PendingAsks::new(Duration::from_secs(5));
        let reply = make_reply("no-such-id");
        assert!(!pa.resolve("no-such-id", reply));
    }

    #[tokio::test]
    async fn cancel_removes_entry() {
        let pa = PendingAsks::new(Duration::from_secs(5));
        let _rx = pa.register("corr-2".to_string(), Duration::from_secs(5));
        assert_eq!(pa.len(), 1);
        pa.cancel("corr-2");
        assert_eq!(pa.len(), 0);
    }

    #[tokio::test]
    async fn sweep_expired_removes_timed_out_entries() {
        let pa = PendingAsks::new(Duration::from_secs(5));
        // expires_at = Instant::now() + 0 — immediately in the past.
        // Any subsequent Instant::now() satisfies expires_at <= now.
        let _rx = pa.register("expired".to_string(), Duration::ZERO);
        let swept = pa.sweep_expired();
        assert_eq!(swept, 1);
        assert_eq!(pa.len(), 0);
    }

    #[tokio::test]
    async fn sweep_keeps_non_expired_entries() {
        let pa = PendingAsks::new(Duration::from_secs(5));
        let _rx = pa.register("live".to_string(), Duration::from_secs(60));
        let swept = pa.sweep_expired();
        assert_eq!(swept, 0);
        assert_eq!(pa.len(), 1);
    }

    #[tokio::test]
    async fn independent_asks_do_not_interfere() {
        // Two concurrent asks with distinct correlation IDs must be fully independent.
        // Tenant isolation is guaranteed by ULID uniqueness — each ask() generates
        // a fresh ULID so keys never collide across tenants or requests.
        let pa = PendingAsks::new(Duration::from_secs(5));
        let _rx_a = pa.register("corr-a".to_string(), Duration::from_secs(5));
        let rx_b = pa.register("corr-b".to_string(), Duration::from_secs(5));

        // Resolving corr-b must not affect corr-a.
        assert!(pa.resolve("corr-b", make_reply("corr-b")));
        assert_eq!(pa.len(), 1, "corr-a should still be pending");

        let received = rx_b.await.expect("corr-b should be delivered");
        assert_eq!(received.correlation_id, "corr-b");
    }

    #[tokio::test]
    async fn resolve_is_idempotent_for_same_key() {
        // Second resolve on the same key returns false (entry already removed).
        let pa = PendingAsks::new(Duration::from_secs(5));
        let _rx = pa.register("corr-x".to_string(), Duration::from_secs(5));
        assert!(pa.resolve("corr-x", make_reply("corr-x")));
        assert!(!pa.resolve("corr-x", make_reply("corr-x")));
    }

    /// Env-var tests must run serially to avoid cross-test process env mutation races.
    #[test]
    fn from_env_default_and_override() {
        env::remove_var(ASK_TIMEOUT_ENV);
        assert_eq!(
            PendingAsks::from_env().default_timeout(),
            Duration::from_secs(30),
            "default when var absent"
        );

        env::set_var(ASK_TIMEOUT_ENV, "5000");
        assert_eq!(
            PendingAsks::from_env().default_timeout(),
            Duration::from_secs(5),
            "reads env var"
        );

        env::remove_var(ASK_TIMEOUT_ENV);
    }
}
