# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025 PlexSpaces Contributors
#
# PlexSpaces Runtime
#
# Generates the WIT interface wrapper for actor classes decorated with @actor.
# This bridges the gap between the Pythonic SDK API and the componentize-py
# WIT bindings.

"""
Runtime support for PlexSpaces actors.

## Multi-Actor Dispatch

The framework always sets ``actor_type`` to the exact class name in the init
config (e.g. ``"SessionActor"``).  The dispatch rule is therefore simple:

1. ``config["actor_type"]`` — exact lookup in the class map.  This is the
   normal case and covers every virtual-actor activation.
2. ``config["role"]`` — exact lookup, used only when multiple children in
   ``app-config.toml`` share the same ``actor_type`` but need different
   behaviour (e.g. ``ephemeral`` / ``channel`` / ``controller`` all map to
   ``AbstractionsActor``).
3. ``default_class`` — first class in ``__all__`` / registration order.

No aliases, no prefix matching, no normalization.  The framework is the
source of truth; the SDK trusts what it receives.
"""

import json
from typing import Type, List, Dict, Optional

from .decorators import (
    get_state_dict,
    set_state_dict,
    dispatch_message,
    init_actor,
    _sanitize_payload_for_wasm,
    _desanitize_from_wasm,
    _has_float,
)


def _to_snake_case(name: str) -> str:
    """Convert PascalCase/camelCase to snake_case.

    The framework stores actor_type as snake_case in app-config.toml
    (e.g. "inference_worker") while Python classes use PascalCase
    (e.g. "InferenceWorker").
    """
    import re
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', name)
    s = re.sub(r'([a-z\d])([A-Z])', r'\1_\2', s)
    return s.lower()


def build_class_map(
    actor_classes: List[Type],
    actor_roles: Optional[Dict[str, Type]] = None,
) -> Dict[str, Type]:
    """Build the dispatch map used by ``select_actor_class``.

    Keys are exact strings the framework places in ``actor_type`` or ``role``:
    - Each class is registered under its exact ``__name__``.
    - Each class is also registered under its snake_case form to match the
      framework's TOML convention (e.g. "InferenceWorker" -> "inference_worker").
    - Explicit ``actor_roles`` entries are registered under their exact key
      (for same-class multi-instance cases like ``ephemeral``/``channel``).
    """
    class_map: Dict[str, Type] = {}

    # Class names first (lower priority — roles may override for same-class dispatch)
    for cls in actor_classes:
        class_map[cls.__name__] = cls
        snake = _to_snake_case(cls.__name__)
        if snake != cls.__name__:
            class_map[snake] = cls

    # Explicit role overrides (only valid when multiple children share actor_type)
    if actor_roles:
        for role, cls in actor_roles.items():
            if cls in actor_classes:
                class_map[role] = cls

    return class_map


def select_actor_class(
    config: dict,
    class_map: Dict[str, Type],
    default_class: Type,
) -> Type:
    """Select the actor class from the framework-supplied init config.

    Priority:
    1. ``config["actor_type"]`` — exact match (the normal case).
    2. ``config["role"]`` — exact match (same-class multi-instance only).
    3. ``default_class`` — first registered class.
    """
    if not isinstance(config, dict) or not class_map:
        return default_class

    actor_type = config.get("actor_type", "")
    if actor_type and actor_type in class_map:
        return class_map[actor_type]

    role = config.get("role", "")
    if role and role in class_map:
        return class_map[role]

    return default_class


def generate_wrapper(
    actor_classes: List[Type],
    module_name: str,
    actor_roles: Optional[Dict[str, Type]] = None,
) -> str:
    """Generate the WIT interface wrapper for one or more actor classes.

    Args:
        actor_classes: List of @actor decorated classes (at least one).
        module_name: Name of the module containing the actor classes.
        actor_roles: Optional role→class map for same-class multi-instance dispatch.

    Returns:
        Python source code for the generated wrapper.
    """
    if not actor_classes:
        raise ValueError("No @actor classes provided")

    class_names = [cls.__name__ for cls in actor_classes]
    imports = ", ".join(class_names)
    default_class = class_names[0]
    class_map = build_class_map(actor_classes, actor_roles)

    lines = [
        "# AUTO-GENERATED by PlexSpaces SDK",
        "# DO NOT EDIT - regenerate with: plexspaces-py build",
        "",
        "import json",
        "from wit_world import exports",
        f"from {module_name} import {imports}",
        "from plexspaces.decorators import (",
        "    get_state_dict, set_state_dict, dispatch_message, init_actor,",
        "    _sanitize_payload_for_wasm, _desanitize_from_wasm, _has_float,",
        "    payload_from_request_json,",
        ")",
        "from plexspaces.runtime import select_actor_class as _select_actor_class",
        "",
    ]

    if len(actor_classes) == 1:
        lines.append(f"_actor_class = {default_class}")
        lines.append("_CLASS_MAP = {}")
    else:
        lines.append(f"_actor_class = {default_class}  # default")
        lines.append("")
        lines.append("# Dispatch map: actor_type / role -> class (exact match only)")
        lines.append("_CLASS_MAP = {")
        for key, cls in class_map.items():
            lines.append(f'    "{key}": {cls.__name__},')
        lines.append("}")

    lines.extend([
        "",
        "# Actor instance (created on first init)",
        "_instance = None",
        "",
        "",
        "def _select_class(config):",
        '    """Delegate to plexspaces.runtime.select_actor_class (single source of truth)."""',
        f"    return _select_actor_class(config, _CLASS_MAP, {default_class})",
        "",
        "",
        f'class Actor(exports.Actor):',
        f'    """WIT interface wrapper (supports {", ".join(class_names)})."""',
        "",
        "    def _decode(self, data):",
        '        """Decode WIT payload (list<u8>) to str. Accepts bytes or str."""',
        "        if isinstance(data, (bytes, bytearray)):",
        "            return data.decode('utf-8')",
        "        return str(data) if data else ''",
        "",
        "    def init(self, config):",
        '        """Initialize the actor with optional config."""',
        "        global _instance, _actor_class",
        "        try:",
        "            config_json = self._decode(config)",
        "            config = json.loads(config_json) if config_json else {}",
        "            _actor_class = _select_class(config)",
        "            _instance = _actor_class()",
        "            if config:",
        "                init_actor(_instance, config)",
        "        except Exception as e:",
        '            return f"ERROR: {e}"',
        "",
        "    def handle(self, from_actor: str, msg_type: str, payload):",
        '        """Handle incoming message."""',
        "        global _instance",
        "        if _instance is None:",
        '            return json.dumps({"error": "Actor not initialized"}).encode("utf-8")',
        "",
        "        try:",
        "            payload_json = self._decode(payload)",
        '            payload = payload_from_request_json(payload_json or "")',
        "            result = dispatch_message(_instance, from_actor, msg_type, payload)",
        "",
        "            if isinstance(result, str):",
        '                return result.encode("utf-8")',
        "            # json.dumps handles floats natively as JSON numbers.",
        "            # Do NOT sanitize floats to strings here -- that corrupts",
        "            # inter-actor ask() responses (receivers get strings where",
        "            # they expect numbers, causing 'float + str' TypeError).",
        "            # Float sanitization is only needed in get_state() for",
        "            # checkpoint persistence (reversed by _desanitize_from_wasm",
        "            # in set_state).",
        '            return json.dumps(result).encode("utf-8")',
        "        except Exception as e:",
        '            return json.dumps({"error": str(e)}).encode("utf-8")',
        "",
        "    def get_state(self):",
        '        """Get actor state as JSON bytes."""',
        "        global _instance",
        "        if _instance is None:",
        '            return b"{}"',
        "",
        "        try:",
        "            state = get_state_dict(_instance)",
        "            state['__actor_class__'] = type(_instance).__name__",
        "            state_safe = _sanitize_payload_for_wasm(state)",
        '            return json.dumps(state_safe).encode("utf-8")',
        "        except Exception as e:",
        '            return json.dumps({"error": str(e)}).encode("utf-8")',
        "",
        "    def set_state(self, state_data):",
        '        """Restore actor state from JSON bytes."""',
        "        global _instance, _actor_class",
        "",
        "        try:",
        "            state_json = self._decode(state_data)",
        "            state = json.loads(state_json)",
        "            cls_name = state.pop('__actor_class__', None)",
        "            if cls_name and cls_name in _CLASS_MAP:",
        "                _actor_class = _CLASS_MAP[cls_name]",
        "            if _instance is None:",
        "                _instance = _actor_class()",
        "            # Recursively restore stringified numbers back to numeric types.",
        "            # get_state sanitizes floats to strings for WASM JSON safety;",
        "            # _desanitize_from_wasm reverses this for lists, dicts, and scalars.",
        "            state = _desanitize_from_wasm(state)",
        "            set_state_dict(_instance, state)",
        '            return ""',
        "        except Exception as e:",
        '            return f"ERROR: {e}"',
    ])

    return "\n".join(lines)


def create_actor_module(user_module_path: str, output_path: str = None) -> str:
    """
    Create a wrapped actor module from a user's actor file.

    Args:
        user_module_path: Path to the user's Python file with @actor class(es)
        output_path: Optional output path (defaults to {name}_wrapper.py)

    Returns:
        Path to the generated wrapper file
    """
    import importlib.util
    import os

    # Load the user's module
    module_name = os.path.splitext(os.path.basename(user_module_path))[0]
    spec = importlib.util.spec_from_file_location(module_name, user_module_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    # Find ALL @actor decorated classes (preserving definition order)
    actor_classes = []
    for name in dir(module):
        obj = getattr(module, name)
        if isinstance(obj, type) and hasattr(obj, '_plexspaces_is_actor'):
            actor_classes.append(obj)

    if not actor_classes:
        raise ValueError(f"No @actor decorated class found in {user_module_path}")

    actor_roles = getattr(module, "ACTOR_ROLES", None)

    # Generate wrapper
    wrapper_code = generate_wrapper(actor_classes, module_name, actor_roles=actor_roles)

    # Write to output file
    if output_path is None:
        output_path = os.path.join(
            os.path.dirname(user_module_path),
            f"{module_name}_actor.py"
        )

    with open(output_path, 'w') as f:
        f.write(wrapper_code)

    return output_path
