# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (C) 2025 PlexSpaces Contributors
#
# PlexSpaces Runtime
#
# Generates the WIT interface wrapper for actor classes decorated with @actor.
# This bridges the gap between the Pythonic SDK API and the componentize-py
# WIT bindings.
#
# Supports multiple @actor classes in one module via Erlang-style ApplicationSpec:
# The framework passes {"actor_id": "child-spec-id", ...} in init config,
# and the wrapper selects the correct class based on a mapping defined
# in the module-level ACTOR_ROLES dict.

"""
Runtime support for PlexSpaces actors.

This module provides:
- Wrapper generation for WIT interface compatibility
- State serialization/deserialization
- Message dispatch
- Multi-actor support (multiple @actor classes in one WASM module)

The generated wrapper implements the WIT actor interface:
    interface actor {
        init: func(config-json: string) -> string;
        handle: func(from-actor: string, msg-type: string, payload-json: string) -> string;
        get-state: func() -> string;
        set-state: func(state-json: string) -> string;
    }

## Multi-Actor Support

When a module contains multiple @actor classes, the wrapper uses the
init config's ``actor_id`` field to select which class to instantiate.
Mapping is defined in the module via ``ACTOR_ROLES``:

    ACTOR_ROLES = {
        "parameter-server": ParameterServer,
        "data-worker": DataWorker,        # prefix match
    }

If no mapping is found or only one @actor class exists, the first class is used.
"""

import json
import textwrap
from typing import Type, Any, List, Dict

from .decorators import (
    get_state_dict,
    set_state_dict,
    dispatch_message,
    init_actor,
    _sanitize_payload_for_wasm,
    _has_float,
)


def generate_wrapper(actor_classes: List[Type], module_name: str) -> str:
    """
    Generate the WIT interface wrapper code for one or more actor classes.

    When multiple classes are provided, the wrapper reads ``actor_id`` from
    the init config and uses ``ACTOR_ROLES`` (module-level dict) or prefix
    matching on class names to select which class to instantiate.

    Args:
        actor_classes: List of @actor decorated classes (at least one)
        module_name: Name of the module containing the actor classes

    Returns:
        Python source code for the wrapper
    """
    if not actor_classes:
        raise ValueError("No @actor classes provided")

    class_names = [cls.__name__ for cls in actor_classes]
    imports = ", ".join(class_names)
    default_class = class_names[0]

    # Build role-matching logic for multi-actor support
    if len(actor_classes) == 1:
        # Single actor - simple path
        class_selection = f"    _actor_class = {default_class}"
        role_lookup = ""
    else:
        # Multiple actors - use ACTOR_ROLES dict from module, fall back to
        # prefix matching on actor_id
        role_entries = []
        for cls_name in class_names:
            # Convert CamelCase to kebab-case for prefix matching
            # e.g., ParameterServer -> parameter-server, DataWorker -> data-worker
            kebab = ""
            for i, ch in enumerate(cls_name):
                if ch.isupper() and i > 0:
                    kebab += "-"
                kebab += ch.lower()
            role_entries.append(f'        "{kebab}": {cls_name},')

        roles_dict = "\n".join(role_entries)
        class_selection = f"    _actor_class = {default_class}  # default"
        role_lookup = textwrap.dedent(f'''
    # Auto-generated role mapping (CamelCase -> kebab-case prefix)
    _AUTO_ROLES = {{
{roles_dict}
    }}

    # Merge user-defined ACTOR_ROLES (if any) with auto-generated ones
    try:
        from {module_name} import ACTOR_ROLES as _USER_ROLES
        _ROLE_MAP = {{**_AUTO_ROLES, **_USER_ROLES}}
    except ImportError:
        _ROLE_MAP = _AUTO_ROLES
        ''').rstrip()

    wrapper_code = textwrap.dedent(f'''
        # AUTO-GENERATED by PlexSpaces SDK
        # DO NOT EDIT - regenerate with: plexspaces-py build

        import json
        from wit_world import exports
        from {module_name} import {imports}
        from plexspaces.decorators import (
            get_state_dict, set_state_dict, dispatch_message, init_actor,
            _sanitize_payload_for_wasm, _has_float, payload_from_request_json,
        )

    {class_selection}
    {role_lookup}

        # Actor instance (created on first init)
        _instance = None


        def _select_class(config):
            """Select actor class based on init config actor_id."""
            global _actor_class
            actor_id = config.get("actor_id", "") if isinstance(config, dict) else ""
            if not actor_id or not _ROLE_MAP:
                return _actor_class
            # Exact match first
            if actor_id in _ROLE_MAP:
                return _ROLE_MAP[actor_id]
            # Prefix match (e.g., "data-worker-0" matches "data-worker")
            for prefix, cls in sorted(_ROLE_MAP.items(), key=lambda x: -len(x[0])):
                if actor_id.startswith(prefix):
                    return cls
            return _actor_class


        class Actor(exports.Actor):
            """WIT interface wrapper (supports {", ".join(class_names)})."""

            def init(self, config_json: str) -> str:
                """Initialize the actor with optional config."""
                global _instance, _actor_class
                try:
                    config = json.loads(config_json) if config_json else {{}}
                    _actor_class = _select_class(config)
                    _instance = _actor_class()
                    if config:
                        init_actor(_instance, config)
                    return ""
                except Exception as e:
                    return f"ERROR: {{e}}"

            def handle(self, from_actor: str, msg_type: str, payload_json: str) -> str:
                """Handle incoming message."""
                global _instance
                if _instance is None:
                    return json.dumps({{"error": "Actor not initialized"}})

                try:
                    payload = payload_from_request_json(payload_json or "")
                    result = dispatch_message(_instance, from_actor, msg_type, payload)

                    if isinstance(result, str):
                        return result
                    if not _has_float(result):
                        return json.dumps(result)
                    result_safe = _sanitize_payload_for_wasm(result)
                    return json.dumps(result_safe)
                except Exception as e:
                    return json.dumps({{"error": str(e)}})

            def get_state(self) -> str:
                """Get actor state as JSON."""
                global _instance
                if _instance is None:
                    return "{{}}"

                try:
                    state = get_state_dict(_instance)
                    state_safe = _sanitize_payload_for_wasm(state)
                    return json.dumps(state_safe)
                except Exception as e:
                    return json.dumps({{"error": str(e)}})

            def set_state(self, state_json: str) -> str:
                """Restore actor state from JSON."""
                global _instance
                if _instance is None:
                    _instance = _actor_class()

                try:
                    state = json.loads(state_json)
                    state_safe = _sanitize_payload_for_wasm(state)
                    set_state_dict(_instance, state_safe)
                    return ""
                except Exception as e:
                    return f"ERROR: {{e}}"
    ''').strip()

    return wrapper_code


def create_actor_module(user_module_path: str, output_path: str = None) -> str:
    """
    Create a wrapped actor module from a user's actor file.

    Args:
        user_module_path: Path to the user's Python file with @actor class(es)
        output_path: Optional output path (defaults to {name}_wrapper.py)

    Returns:
        Path to the generated wrapper file
    """
    import importlib.util
    import os

    # Load the user's module
    module_name = os.path.splitext(os.path.basename(user_module_path))[0]
    spec = importlib.util.spec_from_file_location(module_name, user_module_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    # Find ALL @actor decorated classes (preserving definition order)
    actor_classes = []
    for name in dir(module):
        obj = getattr(module, name)
        if isinstance(obj, type) and hasattr(obj, '_plexspaces_is_actor'):
            actor_classes.append(obj)

    if not actor_classes:
        raise ValueError(f"No @actor decorated class found in {user_module_path}")

    # Generate wrapper
    wrapper_code = generate_wrapper(actor_classes, module_name)

    # Write to output file
    if output_path is None:
        output_path = os.path.join(
            os.path.dirname(user_module_path),
            f"{module_name}_actor.py"
        )

    with open(output_path, 'w') as f:
        f.write(wrapper_code)

    return output_path
