# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (C) 2025 PlexSpaces Contributors
#
# PlexSpaces Runtime
#
# Generates the WIT interface wrapper for actor classes decorated with @actor.
# This bridges the gap between the Pythonic SDK API and the componentize-py
# WIT bindings.

"""
Runtime support for PlexSpaces actors.

This module provides:
- Wrapper generation for WIT interface compatibility
- State serialization/deserialization
- Message dispatch

The generated wrapper implements the WIT actor interface:
    interface actor {
        init: func(config-json: string) -> string;
        handle: func(from-actor: string, msg-type: string, payload-json: string) -> string;
        get-state: func() -> string;
        set-state: func(state-json: string) -> string;
    }
"""

import json
import textwrap
from typing import Type, Any

from .decorators import (
    get_state_dict,
    set_state_dict,
    dispatch_message,
    init_actor,
    _sanitize_payload_for_wasm,
    _has_float,
)


def generate_wrapper(actor_class: Type, module_name: str) -> str:
    """
    Generate the WIT interface wrapper code for an actor class.
    
    This generates a Python file that:
    1. Imports the user's actor class
    2. Creates a class that implements the WIT actor interface
    3. Delegates to the SDK's runtime functions
    
    Args:
        actor_class: The @actor decorated class
        module_name: Name of the module containing the actor class
    
    Returns:
        Python source code for the wrapper
    """
    class_name = actor_class.__name__
    
    wrapper_code = textwrap.dedent(f'''
        # AUTO-GENERATED by PlexSpaces SDK
        # DO NOT EDIT - regenerate with: plexspaces-py build
        
        import json
        from wit_world import exports
        from {module_name} import {class_name}
        from plexspaces.decorators import (
            get_state_dict, set_state_dict, dispatch_message, init_actor,
            _sanitize_payload_for_wasm, _has_float, payload_from_request_json,
        )
        
        # Actor instance (created on first init)
        _instance = None
        
        
        class Actor(exports.Actor):
            """WIT interface wrapper for {class_name}."""
            
            def init(self, config_json: str) -> str:
                """Initialize the actor with optional config."""
                global _instance
                try:
                    _instance = {class_name}()
                    if config_json:
                        config = json.loads(config_json)
                        init_actor(_instance, config)
                    return ""
                except Exception as e:
                    return f"ERROR: {{e}}"
            
            def handle(self, from_actor: str, msg_type: str, payload_json: str) -> str:
                """Handle incoming message. Result is sanitized for WIT/WASM (no raw float)."""
                global _instance
                if _instance is None:
                    return json.dumps({{"error": "Actor not initialized"}})
                
                try:
                    payload = payload_from_request_json(payload_json or "")
                    result = dispatch_message(_instance, from_actor, msg_type, payload)
                    
                    if isinstance(result, str):
                        return result
                    # Skip sanitize when no floats to avoid creating new dict/list (WASM frame cleanup trap)
                    if not _has_float(result):
                        return json.dumps(result)
                    result_safe = _sanitize_payload_for_wasm(result)
                    return json.dumps(result_safe)
                except Exception as e:
                    return json.dumps({{"error": str(e)}})
            
            def get_state(self) -> str:
                """Get actor state as JSON. State is sanitized for WIT/WASM (no raw float)."""
                global _instance
                if _instance is None:
                    return "{{}}"
                
                try:
                    state = get_state_dict(_instance)
                    state_safe = _sanitize_payload_for_wasm(state)
                    return json.dumps(state_safe)
                except Exception as e:
                    return json.dumps({{"error": str(e)}})
            
            def set_state(self, state_json: str) -> str:
                """Restore actor state from JSON. Input is sanitized for WIT/WASM."""
                global _instance
                if _instance is None:
                    _instance = {class_name}()
                
                try:
                    state = json.loads(state_json)
                    state_safe = _sanitize_payload_for_wasm(state)
                    set_state_dict(_instance, state_safe)
                    return ""
                except Exception as e:
                    return f"ERROR: {{e}}"
    ''').strip()
    
    return wrapper_code


def create_actor_module(user_module_path: str, output_path: str = None) -> str:
    """
    Create a wrapped actor module from a user's actor file.
    
    Args:
        user_module_path: Path to the user's Python file with @actor class
        output_path: Optional output path (defaults to {name}_wrapper.py)
    
    Returns:
        Path to the generated wrapper file
    """
    import importlib.util
    import os
    
    # Load the user's module
    module_name = os.path.splitext(os.path.basename(user_module_path))[0]
    spec = importlib.util.spec_from_file_location(module_name, user_module_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    
    # Find the @actor decorated class
    actor_class = None
    for name in dir(module):
        obj = getattr(module, name)
        if isinstance(obj, type) and hasattr(obj, '_plexspaces_is_actor'):
            actor_class = obj
            break
    
    if actor_class is None:
        raise ValueError(f"No @actor decorated class found in {user_module_path}")
    
    # Generate wrapper
    wrapper_code = generate_wrapper(actor_class, module_name)
    
    # Write to output file
    if output_path is None:
        output_path = os.path.join(
            os.path.dirname(user_module_path),
            f"{module_name}_actor.py"
        )
    
    with open(output_path, 'w') as f:
        f.write(wrapper_code)
    
    return output_path
