// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 Shahzad A. Bhatti <bhatti@plexobject.com>
//
// This file is part of PlexSpaces.
//
// Actor domain types and error codes.
// Moved here from actor_runtime.proto to separate stable data contracts
// from the gRPC request/response service API.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plexspaces/v1/actors/types.proto

package actorv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/bhatti/plexspaces/sdks/go/plexspaces/proto/plexspaces/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Actor lifecycle states.
//
// ## Purpose
// Defines the state machine for actor lifecycle management and supervision.
//
// ## Why This Exists
// - Enables supervision to track actor health and make restart decisions
// - Supports graceful activation/deactivation (Orbit-inspired auto-activation)
// - Allows migration state tracking for mobile agents
// - Provides clear state transitions for debugging and monitoring
//
// ## State Transitions
// ```
// CREATING -> ACTIVATING -> ACTIVE -> DEACTIVATING -> INACTIVE
//
//	\-> MIGRATING -> ACTIVE (on new node)
//	\-> FAILED -> (supervisor restarts)
//	\-> TERMINATED (permanent stop)
//
// ```
//
// ## Design Notes
// - UNSPECIFIED should never occur in valid states (indicates error)
// - ACTIVATING/DEACTIVATING enable graceful lifecycle management
// - MIGRATING supports actor mobility between nodes
// - FAILED triggers supervisor restart policies
// - FAILED state includes error message for debugging (see Actor message for error details)
type ActorState int32

const (
	ActorState_ACTOR_STATE_UNSPECIFIED  ActorState = 0
	ActorState_ACTOR_STATE_CREATING     ActorState = 1 // Actor is created but not yet started (replaces "Initializing")
	ActorState_ACTOR_STATE_ACTIVE       ActorState = 2 // Actor is running and processing messages
	ActorState_ACTOR_STATE_INACTIVE     ActorState = 3 // Actor is suspended/not processing (replaces "Suspended")
	ActorState_ACTOR_STATE_ACTIVATING   ActorState = 4 // Actor is activating (loading state, running on_activate)
	ActorState_ACTOR_STATE_DEACTIVATING ActorState = 5 // Actor is deactivating (saving state, running on_deactivate)
	ActorState_ACTOR_STATE_STOPPING     ActorState = 6 // Actor is stopping (shutdown in progress)
	ActorState_ACTOR_STATE_MIGRATING    ActorState = 7 // Actor is migrating to another node
	ActorState_ACTOR_STATE_FAILED       ActorState = 8 // Actor has crashed (error message in Actor.error_message field)
	ActorState_ACTOR_STATE_TERMINATED   ActorState = 9 // Actor has permanently stopped (replaces "Stopped")
)

// Enum value maps for ActorState.
var (
	ActorState_name = map[int32]string{
		0: "ACTOR_STATE_UNSPECIFIED",
		1: "ACTOR_STATE_CREATING",
		2: "ACTOR_STATE_ACTIVE",
		3: "ACTOR_STATE_INACTIVE",
		4: "ACTOR_STATE_ACTIVATING",
		5: "ACTOR_STATE_DEACTIVATING",
		6: "ACTOR_STATE_STOPPING",
		7: "ACTOR_STATE_MIGRATING",
		8: "ACTOR_STATE_FAILED",
		9: "ACTOR_STATE_TERMINATED",
	}
	ActorState_value = map[string]int32{
		"ACTOR_STATE_UNSPECIFIED":  0,
		"ACTOR_STATE_CREATING":     1,
		"ACTOR_STATE_ACTIVE":       2,
		"ACTOR_STATE_INACTIVE":     3,
		"ACTOR_STATE_ACTIVATING":   4,
		"ACTOR_STATE_DEACTIVATING": 5,
		"ACTOR_STATE_STOPPING":     6,
		"ACTOR_STATE_MIGRATING":    7,
		"ACTOR_STATE_FAILED":       8,
		"ACTOR_STATE_TERMINATED":   9,
	}
)

func (x ActorState) Enum() *ActorState {
	p := new(ActorState)
	*p = x
	return p
}

func (x ActorState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorState) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[0].Descriptor()
}

func (ActorState) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[0]
}

func (x ActorState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorState.Descriptor instead.
func (ActorState) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{0}
}

// Exit reason for actor termination (Erlang/OTP-style)
//
// ## Purpose
// Defines why an actor terminated, enabling proper supervision decisions
// and link/monitor propagation semantics.
//
// ## Erlang Equivalent
// Maps to Erlang's exit reasons:
// - normal: Normal termination (not an error)
// - shutdown: Graceful shutdown requested
// - kill: Forcefully killed
// - {error, Reason}: Error with message
// - {linked, Pid, Reason}: Linked actor died
//
// ## Usage
// - Used in Actor::terminate() and Actor::handle_exit() lifecycle hooks
// - Propagated to linked actors (if trap_exit=false, causes cascading crash)
// - Used by supervisors to decide restart policies
type ExitReason int32

const (
	ExitReason_EXIT_REASON_UNSPECIFIED ExitReason = 0
	ExitReason_EXIT_REASON_NORMAL      ExitReason = 1 // Normal termination (not an error)
	ExitReason_EXIT_REASON_SHUTDOWN    ExitReason = 2 // Shutdown requested (graceful)
	ExitReason_EXIT_REASON_KILLED      ExitReason = 3 // Killed forcefully
	ExitReason_EXIT_REASON_ERROR       ExitReason = 4 // Error with message (error_message field contains details)
	ExitReason_EXIT_REASON_LINKED      ExitReason = 5 // Linked actor died (linked_actor_id and linked_reason fields)
)

// Enum value maps for ExitReason.
var (
	ExitReason_name = map[int32]string{
		0: "EXIT_REASON_UNSPECIFIED",
		1: "EXIT_REASON_NORMAL",
		2: "EXIT_REASON_SHUTDOWN",
		3: "EXIT_REASON_KILLED",
		4: "EXIT_REASON_ERROR",
		5: "EXIT_REASON_LINKED",
	}
	ExitReason_value = map[string]int32{
		"EXIT_REASON_UNSPECIFIED": 0,
		"EXIT_REASON_NORMAL":      1,
		"EXIT_REASON_SHUTDOWN":    2,
		"EXIT_REASON_KILLED":      3,
		"EXIT_REASON_ERROR":       4,
		"EXIT_REASON_LINKED":      5,
	}
)

func (x ExitReason) Enum() *ExitReason {
	p := new(ExitReason)
	*p = x
	return p
}

func (x ExitReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExitReason) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[1].Descriptor()
}

func (ExitReason) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[1]
}

func (x ExitReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExitReason.Descriptor instead.
func (ExitReason) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{1}
}

// Exit action when handling EXIT from linked actor
//
// ## Purpose
// Determines how an actor responds to EXIT signal from a linked actor.
// Only relevant when ActorContext.trap_exit = true.
//
// ## Erlang Equivalent
// Maps to Erlang's handle_exit behavior:
// - Propagate: Actor will also terminate (default link behavior)
// - Handle: Actor continues running (traps the exit)
type ExitAction int32

const (
	ExitAction_EXIT_ACTION_UNSPECIFIED ExitAction = 0
	ExitAction_EXIT_ACTION_PROPAGATE   ExitAction = 1 // Propagate exit - this actor will also terminate
	ExitAction_EXIT_ACTION_HANDLE      ExitAction = 2 // Handle exit - this actor continues running
)

// Enum value maps for ExitAction.
var (
	ExitAction_name = map[int32]string{
		0: "EXIT_ACTION_UNSPECIFIED",
		1: "EXIT_ACTION_PROPAGATE",
		2: "EXIT_ACTION_HANDLE",
	}
	ExitAction_value = map[string]int32{
		"EXIT_ACTION_UNSPECIFIED": 0,
		"EXIT_ACTION_PROPAGATE":   1,
		"EXIT_ACTION_HANDLE":      2,
	}
)

func (x ExitAction) Enum() *ExitAction {
	p := new(ExitAction)
	*p = x
	return p
}

func (x ExitAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExitAction) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[2].Descriptor()
}

func (ExitAction) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[2]
}

func (x ExitAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExitAction.Descriptor instead.
func (ExitAction) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{2}
}

type ActorErrorCode int32

const (
	ActorErrorCode_ACTOR_ERROR_UNSPECIFIED        ActorErrorCode = 0
	ActorErrorCode_ACTOR_ERROR_NOT_FOUND          ActorErrorCode = 1
	ActorErrorCode_ACTOR_ERROR_ALREADY_EXISTS     ActorErrorCode = 2
	ActorErrorCode_ACTOR_ERROR_INVALID_STATE      ActorErrorCode = 3
	ActorErrorCode_ACTOR_ERROR_TIMEOUT            ActorErrorCode = 4
	ActorErrorCode_ACTOR_ERROR_TERMINATED         ActorErrorCode = 5
	ActorErrorCode_ACTOR_ERROR_FACET_ERROR        ActorErrorCode = 6
	ActorErrorCode_ACTOR_ERROR_MAILBOX_ERROR      ActorErrorCode = 7
	ActorErrorCode_ACTOR_ERROR_BEHAVIOR_ERROR     ActorErrorCode = 8
	ActorErrorCode_ACTOR_ERROR_JOURNAL_ERROR      ActorErrorCode = 9
	ActorErrorCode_ACTOR_ERROR_PLACEMENT_CONFLICT ActorErrorCode = 10 // Unique placement violated - actor already active elsewhere
)

// Enum value maps for ActorErrorCode.
var (
	ActorErrorCode_name = map[int32]string{
		0:  "ACTOR_ERROR_UNSPECIFIED",
		1:  "ACTOR_ERROR_NOT_FOUND",
		2:  "ACTOR_ERROR_ALREADY_EXISTS",
		3:  "ACTOR_ERROR_INVALID_STATE",
		4:  "ACTOR_ERROR_TIMEOUT",
		5:  "ACTOR_ERROR_TERMINATED",
		6:  "ACTOR_ERROR_FACET_ERROR",
		7:  "ACTOR_ERROR_MAILBOX_ERROR",
		8:  "ACTOR_ERROR_BEHAVIOR_ERROR",
		9:  "ACTOR_ERROR_JOURNAL_ERROR",
		10: "ACTOR_ERROR_PLACEMENT_CONFLICT",
	}
	ActorErrorCode_value = map[string]int32{
		"ACTOR_ERROR_UNSPECIFIED":        0,
		"ACTOR_ERROR_NOT_FOUND":          1,
		"ACTOR_ERROR_ALREADY_EXISTS":     2,
		"ACTOR_ERROR_INVALID_STATE":      3,
		"ACTOR_ERROR_TIMEOUT":            4,
		"ACTOR_ERROR_TERMINATED":         5,
		"ACTOR_ERROR_FACET_ERROR":        6,
		"ACTOR_ERROR_MAILBOX_ERROR":      7,
		"ACTOR_ERROR_BEHAVIOR_ERROR":     8,
		"ACTOR_ERROR_JOURNAL_ERROR":      9,
		"ACTOR_ERROR_PLACEMENT_CONFLICT": 10,
	}
)

func (x ActorErrorCode) Enum() *ActorErrorCode {
	p := new(ActorErrorCode)
	*p = x
	return p
}

func (x ActorErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[3].Descriptor()
}

func (ActorErrorCode) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[3]
}

func (x ActorErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorErrorCode.Descriptor instead.
func (ActorErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{3}
}

type BehaviorErrorCode int32

const (
	BehaviorErrorCode_BEHAVIOR_ERROR_UNSPECIFIED         BehaviorErrorCode = 0
	BehaviorErrorCode_BEHAVIOR_ERROR_HANDLER_NOT_FOUND   BehaviorErrorCode = 1
	BehaviorErrorCode_BEHAVIOR_ERROR_UNSUPPORTED_MESSAGE BehaviorErrorCode = 2
	BehaviorErrorCode_BEHAVIOR_ERROR_TRANSITION_FAILED   BehaviorErrorCode = 3
	BehaviorErrorCode_BEHAVIOR_ERROR_PROCESSING_ERROR    BehaviorErrorCode = 4
)

// Enum value maps for BehaviorErrorCode.
var (
	BehaviorErrorCode_name = map[int32]string{
		0: "BEHAVIOR_ERROR_UNSPECIFIED",
		1: "BEHAVIOR_ERROR_HANDLER_NOT_FOUND",
		2: "BEHAVIOR_ERROR_UNSUPPORTED_MESSAGE",
		3: "BEHAVIOR_ERROR_TRANSITION_FAILED",
		4: "BEHAVIOR_ERROR_PROCESSING_ERROR",
	}
	BehaviorErrorCode_value = map[string]int32{
		"BEHAVIOR_ERROR_UNSPECIFIED":         0,
		"BEHAVIOR_ERROR_HANDLER_NOT_FOUND":   1,
		"BEHAVIOR_ERROR_UNSUPPORTED_MESSAGE": 2,
		"BEHAVIOR_ERROR_TRANSITION_FAILED":   3,
		"BEHAVIOR_ERROR_PROCESSING_ERROR":    4,
	}
)

func (x BehaviorErrorCode) Enum() *BehaviorErrorCode {
	p := new(BehaviorErrorCode)
	*p = x
	return p
}

func (x BehaviorErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BehaviorErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[4].Descriptor()
}

func (BehaviorErrorCode) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[4]
}

func (x BehaviorErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BehaviorErrorCode.Descriptor instead.
func (BehaviorErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{4}
}

type ActorIdErrorCode int32

const (
	ActorIdErrorCode_ACTOR_ID_ERROR_UNSPECIFIED        ActorIdErrorCode = 0
	ActorIdErrorCode_ACTOR_ID_ERROR_INVALID_NAME       ActorIdErrorCode = 1
	ActorIdErrorCode_ACTOR_ID_ERROR_INVALID_ACTOR_TYPE ActorIdErrorCode = 2
	ActorIdErrorCode_ACTOR_ID_ERROR_MISSING_FIELD      ActorIdErrorCode = 3
	ActorIdErrorCode_ACTOR_ID_ERROR_INVALID_FORMAT     ActorIdErrorCode = 4
)

// Enum value maps for ActorIdErrorCode.
var (
	ActorIdErrorCode_name = map[int32]string{
		0: "ACTOR_ID_ERROR_UNSPECIFIED",
		1: "ACTOR_ID_ERROR_INVALID_NAME",
		2: "ACTOR_ID_ERROR_INVALID_ACTOR_TYPE",
		3: "ACTOR_ID_ERROR_MISSING_FIELD",
		4: "ACTOR_ID_ERROR_INVALID_FORMAT",
	}
	ActorIdErrorCode_value = map[string]int32{
		"ACTOR_ID_ERROR_UNSPECIFIED":        0,
		"ACTOR_ID_ERROR_INVALID_NAME":       1,
		"ACTOR_ID_ERROR_INVALID_ACTOR_TYPE": 2,
		"ACTOR_ID_ERROR_MISSING_FIELD":      3,
		"ACTOR_ID_ERROR_INVALID_FORMAT":     4,
	}
)

func (x ActorIdErrorCode) Enum() *ActorIdErrorCode {
	p := new(ActorIdErrorCode)
	*p = x
	return p
}

func (x ActorIdErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorIdErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[5].Descriptor()
}

func (ActorIdErrorCode) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[5]
}

func (x ActorIdErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorIdErrorCode.Descriptor instead.
func (ActorIdErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{5}
}

type SupervisorErrorCode int32

const (
	SupervisorErrorCode_SUPERVISOR_ERROR_UNSPECIFIED           SupervisorErrorCode = 0
	SupervisorErrorCode_SUPERVISOR_ERROR_CHILD_START_FAILED    SupervisorErrorCode = 1
	SupervisorErrorCode_SUPERVISOR_ERROR_MAX_RESTARTS_EXCEEDED SupervisorErrorCode = 2
	SupervisorErrorCode_SUPERVISOR_ERROR_CHILD_NOT_FOUND       SupervisorErrorCode = 3
	SupervisorErrorCode_SUPERVISOR_ERROR_SHUTDOWN_TIMEOUT      SupervisorErrorCode = 4
	SupervisorErrorCode_SUPERVISOR_ERROR_CONFIG_ERROR          SupervisorErrorCode = 5
)

// Enum value maps for SupervisorErrorCode.
var (
	SupervisorErrorCode_name = map[int32]string{
		0: "SUPERVISOR_ERROR_UNSPECIFIED",
		1: "SUPERVISOR_ERROR_CHILD_START_FAILED",
		2: "SUPERVISOR_ERROR_MAX_RESTARTS_EXCEEDED",
		3: "SUPERVISOR_ERROR_CHILD_NOT_FOUND",
		4: "SUPERVISOR_ERROR_SHUTDOWN_TIMEOUT",
		5: "SUPERVISOR_ERROR_CONFIG_ERROR",
	}
	SupervisorErrorCode_value = map[string]int32{
		"SUPERVISOR_ERROR_UNSPECIFIED":           0,
		"SUPERVISOR_ERROR_CHILD_START_FAILED":    1,
		"SUPERVISOR_ERROR_MAX_RESTARTS_EXCEEDED": 2,
		"SUPERVISOR_ERROR_CHILD_NOT_FOUND":       3,
		"SUPERVISOR_ERROR_SHUTDOWN_TIMEOUT":      4,
		"SUPERVISOR_ERROR_CONFIG_ERROR":          5,
	}
)

func (x SupervisorErrorCode) Enum() *SupervisorErrorCode {
	p := new(SupervisorErrorCode)
	*p = x
	return p
}

func (x SupervisorErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SupervisorErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[6].Descriptor()
}

func (SupervisorErrorCode) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[6]
}

func (x SupervisorErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SupervisorErrorCode.Descriptor instead.
func (SupervisorErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{6}
}

type GenServerErrorCode int32

const (
	GenServerErrorCode_GEN_SERVER_ERROR_UNSPECIFIED   GenServerErrorCode = 0
	GenServerErrorCode_GEN_SERVER_ERROR_SERIALIZATION GenServerErrorCode = 1
	GenServerErrorCode_GEN_SERVER_ERROR_CALL          GenServerErrorCode = 2
	GenServerErrorCode_GEN_SERVER_ERROR_CAST          GenServerErrorCode = 3
	GenServerErrorCode_GEN_SERVER_ERROR_SPAWN         GenServerErrorCode = 4
)

// Enum value maps for GenServerErrorCode.
var (
	GenServerErrorCode_name = map[int32]string{
		0: "GEN_SERVER_ERROR_UNSPECIFIED",
		1: "GEN_SERVER_ERROR_SERIALIZATION",
		2: "GEN_SERVER_ERROR_CALL",
		3: "GEN_SERVER_ERROR_CAST",
		4: "GEN_SERVER_ERROR_SPAWN",
	}
	GenServerErrorCode_value = map[string]int32{
		"GEN_SERVER_ERROR_UNSPECIFIED":   0,
		"GEN_SERVER_ERROR_SERIALIZATION": 1,
		"GEN_SERVER_ERROR_CALL":          2,
		"GEN_SERVER_ERROR_CAST":          3,
		"GEN_SERVER_ERROR_SPAWN":         4,
	}
)

func (x GenServerErrorCode) Enum() *GenServerErrorCode {
	p := new(GenServerErrorCode)
	*p = x
	return p
}

func (x GenServerErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenServerErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[7].Descriptor()
}

func (GenServerErrorCode) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[7]
}

func (x GenServerErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenServerErrorCode.Descriptor instead.
func (GenServerErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{7}
}

type FsmErrorCode int32

const (
	FsmErrorCode_FSM_ERROR_UNSPECIFIED   FsmErrorCode = 0
	FsmErrorCode_FSM_ERROR_SERIALIZATION FsmErrorCode = 1
	FsmErrorCode_FSM_ERROR_TRANSITION    FsmErrorCode = 2
	FsmErrorCode_FSM_ERROR_QUERY         FsmErrorCode = 3
	FsmErrorCode_FSM_ERROR_SPAWN         FsmErrorCode = 4
)

// Enum value maps for FsmErrorCode.
var (
	FsmErrorCode_name = map[int32]string{
		0: "FSM_ERROR_UNSPECIFIED",
		1: "FSM_ERROR_SERIALIZATION",
		2: "FSM_ERROR_TRANSITION",
		3: "FSM_ERROR_QUERY",
		4: "FSM_ERROR_SPAWN",
	}
	FsmErrorCode_value = map[string]int32{
		"FSM_ERROR_UNSPECIFIED":   0,
		"FSM_ERROR_SERIALIZATION": 1,
		"FSM_ERROR_TRANSITION":    2,
		"FSM_ERROR_QUERY":         3,
		"FSM_ERROR_SPAWN":         4,
	}
)

func (x FsmErrorCode) Enum() *FsmErrorCode {
	p := new(FsmErrorCode)
	*p = x
	return p
}

func (x FsmErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FsmErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[8].Descriptor()
}

func (FsmErrorCode) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[8]
}

func (x FsmErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FsmErrorCode.Descriptor instead.
func (FsmErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{8}
}

type EventErrorCode int32

const (
	EventErrorCode_EVENT_ERROR_UNSPECIFIED   EventErrorCode = 0
	EventErrorCode_EVENT_ERROR_SERIALIZATION EventErrorCode = 1
	EventErrorCode_EVENT_ERROR_EMIT          EventErrorCode = 2
	EventErrorCode_EVENT_ERROR_SPAWN         EventErrorCode = 3
)

// Enum value maps for EventErrorCode.
var (
	EventErrorCode_name = map[int32]string{
		0: "EVENT_ERROR_UNSPECIFIED",
		1: "EVENT_ERROR_SERIALIZATION",
		2: "EVENT_ERROR_EMIT",
		3: "EVENT_ERROR_SPAWN",
	}
	EventErrorCode_value = map[string]int32{
		"EVENT_ERROR_UNSPECIFIED":   0,
		"EVENT_ERROR_SERIALIZATION": 1,
		"EVENT_ERROR_EMIT":          2,
		"EVENT_ERROR_SPAWN":         3,
	}
)

func (x EventErrorCode) Enum() *EventErrorCode {
	p := new(EventErrorCode)
	*p = x
	return p
}

func (x EventErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[9].Descriptor()
}

func (EventErrorCode) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[9]
}

func (x EventErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventErrorCode.Descriptor instead.
func (EventErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{9}
}

type WorkflowRefErrorCode int32

const (
	WorkflowRefErrorCode_WORKFLOW_REF_ERROR_UNSPECIFIED   WorkflowRefErrorCode = 0
	WorkflowRefErrorCode_WORKFLOW_REF_ERROR_SERIALIZATION WorkflowRefErrorCode = 1
	WorkflowRefErrorCode_WORKFLOW_REF_ERROR_EXECUTION     WorkflowRefErrorCode = 2
	WorkflowRefErrorCode_WORKFLOW_REF_ERROR_SPAWN         WorkflowRefErrorCode = 3
)

// Enum value maps for WorkflowRefErrorCode.
var (
	WorkflowRefErrorCode_name = map[int32]string{
		0: "WORKFLOW_REF_ERROR_UNSPECIFIED",
		1: "WORKFLOW_REF_ERROR_SERIALIZATION",
		2: "WORKFLOW_REF_ERROR_EXECUTION",
		3: "WORKFLOW_REF_ERROR_SPAWN",
	}
	WorkflowRefErrorCode_value = map[string]int32{
		"WORKFLOW_REF_ERROR_UNSPECIFIED":   0,
		"WORKFLOW_REF_ERROR_SERIALIZATION": 1,
		"WORKFLOW_REF_ERROR_EXECUTION":     2,
		"WORKFLOW_REF_ERROR_SPAWN":         3,
	}
)

func (x WorkflowRefErrorCode) Enum() *WorkflowRefErrorCode {
	p := new(WorkflowRefErrorCode)
	*p = x
	return p
}

func (x WorkflowRefErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowRefErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[10].Descriptor()
}

func (WorkflowRefErrorCode) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[10]
}

func (x WorkflowRefErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowRefErrorCode.Descriptor instead.
func (WorkflowRefErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{10}
}

type VirtualActorErrorCode int32

const (
	VirtualActorErrorCode_VIRTUAL_ACTOR_ERROR_UNSPECIFIED       VirtualActorErrorCode = 0
	VirtualActorErrorCode_VIRTUAL_ACTOR_ERROR_NOT_FOUND         VirtualActorErrorCode = 1
	VirtualActorErrorCode_VIRTUAL_ACTOR_ERROR_ACTIVATION_FAILED VirtualActorErrorCode = 2
)

// Enum value maps for VirtualActorErrorCode.
var (
	VirtualActorErrorCode_name = map[int32]string{
		0: "VIRTUAL_ACTOR_ERROR_UNSPECIFIED",
		1: "VIRTUAL_ACTOR_ERROR_NOT_FOUND",
		2: "VIRTUAL_ACTOR_ERROR_ACTIVATION_FAILED",
	}
	VirtualActorErrorCode_value = map[string]int32{
		"VIRTUAL_ACTOR_ERROR_UNSPECIFIED":       0,
		"VIRTUAL_ACTOR_ERROR_NOT_FOUND":         1,
		"VIRTUAL_ACTOR_ERROR_ACTIVATION_FAILED": 2,
	}
)

func (x VirtualActorErrorCode) Enum() *VirtualActorErrorCode {
	p := new(VirtualActorErrorCode)
	*p = x
	return p
}

func (x VirtualActorErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualActorErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[11].Descriptor()
}

func (VirtualActorErrorCode) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[11]
}

func (x VirtualActorErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualActorErrorCode.Descriptor instead.
func (VirtualActorErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{11}
}

type PoolServiceErrorCode int32

const (
	PoolServiceErrorCode_POOL_SERVICE_ERROR_UNSPECIFIED      PoolServiceErrorCode = 0
	PoolServiceErrorCode_POOL_SERVICE_ERROR_POOL_NOT_FOUND   PoolServiceErrorCode = 1
	PoolServiceErrorCode_POOL_SERVICE_ERROR_CHECKOUT_TIMEOUT PoolServiceErrorCode = 2
	PoolServiceErrorCode_POOL_SERVICE_ERROR_POOL_EXHAUSTED   PoolServiceErrorCode = 3
	PoolServiceErrorCode_POOL_SERVICE_ERROR_CIRCUIT_OPEN     PoolServiceErrorCode = 4
	PoolServiceErrorCode_POOL_SERVICE_ERROR_POOL_DRAINING    PoolServiceErrorCode = 5
	PoolServiceErrorCode_POOL_SERVICE_ERROR_INVALID_CONFIG   PoolServiceErrorCode = 6
	PoolServiceErrorCode_POOL_SERVICE_ERROR_ACTOR_ERROR      PoolServiceErrorCode = 7
)

// Enum value maps for PoolServiceErrorCode.
var (
	PoolServiceErrorCode_name = map[int32]string{
		0: "POOL_SERVICE_ERROR_UNSPECIFIED",
		1: "POOL_SERVICE_ERROR_POOL_NOT_FOUND",
		2: "POOL_SERVICE_ERROR_CHECKOUT_TIMEOUT",
		3: "POOL_SERVICE_ERROR_POOL_EXHAUSTED",
		4: "POOL_SERVICE_ERROR_CIRCUIT_OPEN",
		5: "POOL_SERVICE_ERROR_POOL_DRAINING",
		6: "POOL_SERVICE_ERROR_INVALID_CONFIG",
		7: "POOL_SERVICE_ERROR_ACTOR_ERROR",
	}
	PoolServiceErrorCode_value = map[string]int32{
		"POOL_SERVICE_ERROR_UNSPECIFIED":      0,
		"POOL_SERVICE_ERROR_POOL_NOT_FOUND":   1,
		"POOL_SERVICE_ERROR_CHECKOUT_TIMEOUT": 2,
		"POOL_SERVICE_ERROR_POOL_EXHAUSTED":   3,
		"POOL_SERVICE_ERROR_CIRCUIT_OPEN":     4,
		"POOL_SERVICE_ERROR_POOL_DRAINING":    5,
		"POOL_SERVICE_ERROR_INVALID_CONFIG":   6,
		"POOL_SERVICE_ERROR_ACTOR_ERROR":      7,
	}
)

func (x PoolServiceErrorCode) Enum() *PoolServiceErrorCode {
	p := new(PoolServiceErrorCode)
	*p = x
	return p
}

func (x PoolServiceErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PoolServiceErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_actors_types_proto_enumTypes[12].Descriptor()
}

func (PoolServiceErrorCode) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_actors_types_proto_enumTypes[12]
}

func (x PoolServiceErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PoolServiceErrorCode.Descriptor instead.
func (PoolServiceErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{12}
}

// Exit reason details (for EXIT_REASON_ERROR and EXIT_REASON_LINKED)
type ExitReasonDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error message (for EXIT_REASON_ERROR)
	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Linked actor ID (for EXIT_REASON_LINKED)
	LinkedActorId string `protobuf:"bytes,2,opt,name=linked_actor_id,json=linkedActorId,proto3" json:"linked_actor_id,omitempty"`
	// Linked actor's exit reason (for EXIT_REASON_LINKED)
	LinkedReason  ExitReason `protobuf:"varint,3,opt,name=linked_reason,json=linkedReason,proto3,enum=plexspaces.actor.v1.ExitReason" json:"linked_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitReasonDetails) Reset() {
	*x = ExitReasonDetails{}
	mi := &file_plexspaces_v1_actors_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitReasonDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitReasonDetails) ProtoMessage() {}

func (x *ExitReasonDetails) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_actors_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitReasonDetails.ProtoReflect.Descriptor instead.
func (*ExitReasonDetails) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_actors_types_proto_rawDescGZIP(), []int{0}
}

func (x *ExitReasonDetails) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExitReasonDetails) GetLinkedActorId() string {
	if x != nil {
		return x.LinkedActorId
	}
	return ""
}

func (x *ExitReasonDetails) GetLinkedReason() ExitReason {
	if x != nil {
		return x.LinkedReason
	}
	return ExitReason_EXIT_REASON_UNSPECIFIED
}

var File_plexspaces_v1_actors_types_proto protoreflect.FileDescriptor

const file_plexspaces_v1_actors_types_proto_rawDesc = "" +
	"\n" +
	" plexspaces/v1/actors/types.proto\x12\x13plexspaces.actor.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aplexspaces/v1/common.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xba\x01\n" +
	"\x11ExitReasonDetails\x12-\n" +
	"\rerror_message\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10R\ferrorMessage\x120\n" +
	"\x0flinked_actor_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\rlinkedActorId\x12D\n" +
	"\rlinked_reason\x18\x03 \x01(\x0e2\x1f.plexspaces.actor.v1.ExitReasonR\flinkedReason*\x98\x02\n" +
	"\n" +
	"ActorState\x12\x1b\n" +
	"\x17ACTOR_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACTOR_STATE_CREATING\x10\x01\x12\x16\n" +
	"\x12ACTOR_STATE_ACTIVE\x10\x02\x12\x18\n" +
	"\x14ACTOR_STATE_INACTIVE\x10\x03\x12\x1a\n" +
	"\x16ACTOR_STATE_ACTIVATING\x10\x04\x12\x1c\n" +
	"\x18ACTOR_STATE_DEACTIVATING\x10\x05\x12\x18\n" +
	"\x14ACTOR_STATE_STOPPING\x10\x06\x12\x19\n" +
	"\x15ACTOR_STATE_MIGRATING\x10\a\x12\x16\n" +
	"\x12ACTOR_STATE_FAILED\x10\b\x12\x1a\n" +
	"\x16ACTOR_STATE_TERMINATED\x10\t*\xa2\x01\n" +
	"\n" +
	"ExitReason\x12\x1b\n" +
	"\x17EXIT_REASON_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EXIT_REASON_NORMAL\x10\x01\x12\x18\n" +
	"\x14EXIT_REASON_SHUTDOWN\x10\x02\x12\x16\n" +
	"\x12EXIT_REASON_KILLED\x10\x03\x12\x15\n" +
	"\x11EXIT_REASON_ERROR\x10\x04\x12\x16\n" +
	"\x12EXIT_REASON_LINKED\x10\x05*\\\n" +
	"\n" +
	"ExitAction\x12\x1b\n" +
	"\x17EXIT_ACTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EXIT_ACTION_PROPAGATE\x10\x01\x12\x16\n" +
	"\x12EXIT_ACTION_HANDLE\x10\x02*\xdb\x02\n" +
	"\x0eActorErrorCode\x12\x1b\n" +
	"\x17ACTOR_ERROR_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACTOR_ERROR_NOT_FOUND\x10\x01\x12\x1e\n" +
	"\x1aACTOR_ERROR_ALREADY_EXISTS\x10\x02\x12\x1d\n" +
	"\x19ACTOR_ERROR_INVALID_STATE\x10\x03\x12\x17\n" +
	"\x13ACTOR_ERROR_TIMEOUT\x10\x04\x12\x1a\n" +
	"\x16ACTOR_ERROR_TERMINATED\x10\x05\x12\x1b\n" +
	"\x17ACTOR_ERROR_FACET_ERROR\x10\x06\x12\x1d\n" +
	"\x19ACTOR_ERROR_MAILBOX_ERROR\x10\a\x12\x1e\n" +
	"\x1aACTOR_ERROR_BEHAVIOR_ERROR\x10\b\x12\x1d\n" +
	"\x19ACTOR_ERROR_JOURNAL_ERROR\x10\t\x12\"\n" +
	"\x1eACTOR_ERROR_PLACEMENT_CONFLICT\x10\n" +
	"*\xcc\x01\n" +
	"\x11BehaviorErrorCode\x12\x1e\n" +
	"\x1aBEHAVIOR_ERROR_UNSPECIFIED\x10\x00\x12$\n" +
	" BEHAVIOR_ERROR_HANDLER_NOT_FOUND\x10\x01\x12&\n" +
	"\"BEHAVIOR_ERROR_UNSUPPORTED_MESSAGE\x10\x02\x12$\n" +
	" BEHAVIOR_ERROR_TRANSITION_FAILED\x10\x03\x12#\n" +
	"\x1fBEHAVIOR_ERROR_PROCESSING_ERROR\x10\x04*\xbf\x01\n" +
	"\x10ActorIdErrorCode\x12\x1e\n" +
	"\x1aACTOR_ID_ERROR_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bACTOR_ID_ERROR_INVALID_NAME\x10\x01\x12%\n" +
	"!ACTOR_ID_ERROR_INVALID_ACTOR_TYPE\x10\x02\x12 \n" +
	"\x1cACTOR_ID_ERROR_MISSING_FIELD\x10\x03\x12!\n" +
	"\x1dACTOR_ID_ERROR_INVALID_FORMAT\x10\x04*\xfc\x01\n" +
	"\x13SupervisorErrorCode\x12 \n" +
	"\x1cSUPERVISOR_ERROR_UNSPECIFIED\x10\x00\x12'\n" +
	"#SUPERVISOR_ERROR_CHILD_START_FAILED\x10\x01\x12*\n" +
	"&SUPERVISOR_ERROR_MAX_RESTARTS_EXCEEDED\x10\x02\x12$\n" +
	" SUPERVISOR_ERROR_CHILD_NOT_FOUND\x10\x03\x12%\n" +
	"!SUPERVISOR_ERROR_SHUTDOWN_TIMEOUT\x10\x04\x12!\n" +
	"\x1dSUPERVISOR_ERROR_CONFIG_ERROR\x10\x05*\xac\x01\n" +
	"\x12GenServerErrorCode\x12 \n" +
	"\x1cGEN_SERVER_ERROR_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eGEN_SERVER_ERROR_SERIALIZATION\x10\x01\x12\x19\n" +
	"\x15GEN_SERVER_ERROR_CALL\x10\x02\x12\x19\n" +
	"\x15GEN_SERVER_ERROR_CAST\x10\x03\x12\x1a\n" +
	"\x16GEN_SERVER_ERROR_SPAWN\x10\x04*\x8a\x01\n" +
	"\fFsmErrorCode\x12\x19\n" +
	"\x15FSM_ERROR_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FSM_ERROR_SERIALIZATION\x10\x01\x12\x18\n" +
	"\x14FSM_ERROR_TRANSITION\x10\x02\x12\x13\n" +
	"\x0fFSM_ERROR_QUERY\x10\x03\x12\x13\n" +
	"\x0fFSM_ERROR_SPAWN\x10\x04*y\n" +
	"\x0eEventErrorCode\x12\x1b\n" +
	"\x17EVENT_ERROR_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19EVENT_ERROR_SERIALIZATION\x10\x01\x12\x14\n" +
	"\x10EVENT_ERROR_EMIT\x10\x02\x12\x15\n" +
	"\x11EVENT_ERROR_SPAWN\x10\x03*\xa0\x01\n" +
	"\x14WorkflowRefErrorCode\x12\"\n" +
	"\x1eWORKFLOW_REF_ERROR_UNSPECIFIED\x10\x00\x12$\n" +
	" WORKFLOW_REF_ERROR_SERIALIZATION\x10\x01\x12 \n" +
	"\x1cWORKFLOW_REF_ERROR_EXECUTION\x10\x02\x12\x1c\n" +
	"\x18WORKFLOW_REF_ERROR_SPAWN\x10\x03*\x8a\x01\n" +
	"\x15VirtualActorErrorCode\x12#\n" +
	"\x1fVIRTUAL_ACTOR_ERROR_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dVIRTUAL_ACTOR_ERROR_NOT_FOUND\x10\x01\x12)\n" +
	"%VIRTUAL_ACTOR_ERROR_ACTIVATION_FAILED\x10\x02*\xc7\x02\n" +
	"\x14PoolServiceErrorCode\x12\"\n" +
	"\x1ePOOL_SERVICE_ERROR_UNSPECIFIED\x10\x00\x12%\n" +
	"!POOL_SERVICE_ERROR_POOL_NOT_FOUND\x10\x01\x12'\n" +
	"#POOL_SERVICE_ERROR_CHECKOUT_TIMEOUT\x10\x02\x12%\n" +
	"!POOL_SERVICE_ERROR_POOL_EXHAUSTED\x10\x03\x12#\n" +
	"\x1fPOOL_SERVICE_ERROR_CIRCUIT_OPEN\x10\x04\x12$\n" +
	" POOL_SERVICE_ERROR_POOL_DRAINING\x10\x05\x12%\n" +
	"!POOL_SERVICE_ERROR_INVALID_CONFIG\x10\x06\x12\"\n" +
	"\x1ePOOL_SERVICE_ERROR_ACTOR_ERROR\x10\aB\xeb\x01\n" +
	"\x17com.plexspaces.actor.v1B\n" +
	"TypesProtoP\x01ZVgithub.com/bhatti/plexspaces/sdks/go/plexspaces/proto/plexspaces/v1/actors;actorv1\xa2\x02\x03PAX\xaa\x02\x13Plexspaces.Actor.V1\xca\x02\x13Plexspaces\\Actor\\V1\xe2\x02\x1fPlexspaces\\Actor\\V1\\GPBMetadata\xea\x02\x15Plexspaces::Actor::V1b\x06proto3"

var (
	file_plexspaces_v1_actors_types_proto_rawDescOnce sync.Once
	file_plexspaces_v1_actors_types_proto_rawDescData []byte
)

func file_plexspaces_v1_actors_types_proto_rawDescGZIP() []byte {
	file_plexspaces_v1_actors_types_proto_rawDescOnce.Do(func() {
		file_plexspaces_v1_actors_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plexspaces_v1_actors_types_proto_rawDesc), len(file_plexspaces_v1_actors_types_proto_rawDesc)))
	})
	return file_plexspaces_v1_actors_types_proto_rawDescData
}

var file_plexspaces_v1_actors_types_proto_enumTypes = make([]protoimpl.EnumInfo, 13)
var file_plexspaces_v1_actors_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_plexspaces_v1_actors_types_proto_goTypes = []any{
	(ActorState)(0),            // 0: plexspaces.actor.v1.ActorState
	(ExitReason)(0),            // 1: plexspaces.actor.v1.ExitReason
	(ExitAction)(0),            // 2: plexspaces.actor.v1.ExitAction
	(ActorErrorCode)(0),        // 3: plexspaces.actor.v1.ActorErrorCode
	(BehaviorErrorCode)(0),     // 4: plexspaces.actor.v1.BehaviorErrorCode
	(ActorIdErrorCode)(0),      // 5: plexspaces.actor.v1.ActorIdErrorCode
	(SupervisorErrorCode)(0),   // 6: plexspaces.actor.v1.SupervisorErrorCode
	(GenServerErrorCode)(0),    // 7: plexspaces.actor.v1.GenServerErrorCode
	(FsmErrorCode)(0),          // 8: plexspaces.actor.v1.FsmErrorCode
	(EventErrorCode)(0),        // 9: plexspaces.actor.v1.EventErrorCode
	(WorkflowRefErrorCode)(0),  // 10: plexspaces.actor.v1.WorkflowRefErrorCode
	(VirtualActorErrorCode)(0), // 11: plexspaces.actor.v1.VirtualActorErrorCode
	(PoolServiceErrorCode)(0),  // 12: plexspaces.actor.v1.PoolServiceErrorCode
	(*ExitReasonDetails)(nil),  // 13: plexspaces.actor.v1.ExitReasonDetails
}
var file_plexspaces_v1_actors_types_proto_depIdxs = []int32{
	1, // 0: plexspaces.actor.v1.ExitReasonDetails.linked_reason:type_name -> plexspaces.actor.v1.ExitReason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plexspaces_v1_actors_types_proto_init() }
func file_plexspaces_v1_actors_types_proto_init() {
	if File_plexspaces_v1_actors_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plexspaces_v1_actors_types_proto_rawDesc), len(file_plexspaces_v1_actors_types_proto_rawDesc)),
			NumEnums:      13,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plexspaces_v1_actors_types_proto_goTypes,
		DependencyIndexes: file_plexspaces_v1_actors_types_proto_depIdxs,
		EnumInfos:         file_plexspaces_v1_actors_types_proto_enumTypes,
		MessageInfos:      file_plexspaces_v1_actors_types_proto_msgTypes,
	}.Build()
	File_plexspaces_v1_actors_types_proto = out.File
	file_plexspaces_v1_actors_types_proto_goTypes = nil
	file_plexspaces_v1_actors_types_proto_depIdxs = nil
}
