[package]
name = "feature_flags"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[[bin]]
name = "feature_flags"
path = "src/main.rs"

[dependencies]
# PlexSpaces crates
plexspaces-process-groups = { path = "../../../../crates/process-groups" }
plexspaces-keyvalue = { path = "../../../../crates/keyvalue" }
plexspaces-core = { path = "../../../../crates/core" }

# Async runtime
tokio = { version = "1", features = ["full"] }
