// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright (C) 2025 Shahzad A. Bhatti <bhatti@plexobject.com>
//
// This file is part of PlexSpaces.
//
// PlexSpaces is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 2.1 of the License, or
// (at your option) any later version.
//
// PlexSpaces is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with PlexSpaces. If not, see <https://www.gnu.org/licenses/>.

// PlexSpaces Workflow API (Simplified Design)
//
// ## Purpose
// Provides simple, durable workflow orchestration with Temporal/Step Functions-like patterns.
// Workflows are actors with journaling enabled - no separate persistence needed.
//
// ## Architecture
// - **Execution state**: Stored in journal (via DurabilityFacet)
// - **Queryable metadata**: Stored in workflow_definitions and workflow_executions tables
// - **Workflow = Actor + DurabilityFacet + WorkflowBehavior**
//
// ## Key Features
// - Map/reduce parallel execution
// - Conditional logic (Choice steps)
// - Retry policies with exponential backoff
// - Compensation (saga pattern)
// - External signals
// - Full REST/gRPC API
//
// ## Design Decisions
// - **Why workflows are actors**: Reuse existing actor infrastructure (mailbox, supervision, journaling)
// - **Why hybrid storage**: Journal for state (recovery), DB for queries (monitoring)
// - **Why simple step types**: Keep core simple, extend via custom step types
// - **Why REST + gRPC**: gRPC for performance, REST for convenience

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plexspaces/v1/workflow/workflow.proto

package workflowv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/plexobject/plexspaces/sdks/go/plexspaces/proto/plexspaces/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Step types (simplified)
type StepType int32

const (
	StepType_STEP_TYPE_UNSPECIFIED StepType = 0
	StepType_STEP_TYPE_TASK        StepType = 1 // Execute actor method
	StepType_STEP_TYPE_PARALLEL    StepType = 2 // Execute steps in parallel
	StepType_STEP_TYPE_MAP         StepType = 3 // Map over collection (parallel iteration)
	StepType_STEP_TYPE_WAIT        StepType = 4 // Wait for duration
	StepType_STEP_TYPE_CHOICE      StepType = 5 // Conditional branching
	StepType_STEP_TYPE_SIGNAL      StepType = 6 // Wait for external signal
)

// Enum value maps for StepType.
var (
	StepType_name = map[int32]string{
		0: "STEP_TYPE_UNSPECIFIED",
		1: "STEP_TYPE_TASK",
		2: "STEP_TYPE_PARALLEL",
		3: "STEP_TYPE_MAP",
		4: "STEP_TYPE_WAIT",
		5: "STEP_TYPE_CHOICE",
		6: "STEP_TYPE_SIGNAL",
	}
	StepType_value = map[string]int32{
		"STEP_TYPE_UNSPECIFIED": 0,
		"STEP_TYPE_TASK":        1,
		"STEP_TYPE_PARALLEL":    2,
		"STEP_TYPE_MAP":         3,
		"STEP_TYPE_WAIT":        4,
		"STEP_TYPE_CHOICE":      5,
		"STEP_TYPE_SIGNAL":      6,
	}
)

func (x StepType) Enum() *StepType {
	p := new(StepType)
	*p = x
	return p
}

func (x StepType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepType) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_workflow_workflow_proto_enumTypes[0].Descriptor()
}

func (StepType) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_workflow_workflow_proto_enumTypes[0]
}

func (x StepType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepType.Descriptor instead.
func (StepType) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{0}
}

// Execution status
type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_PENDING     ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_RUNNING     ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_COMPLETED   ExecutionStatus = 3
	ExecutionStatus_EXECUTION_STATUS_FAILED      ExecutionStatus = 4
	ExecutionStatus_EXECUTION_STATUS_CANCELLED   ExecutionStatus = 5
	ExecutionStatus_EXECUTION_STATUS_TIMED_OUT   ExecutionStatus = 6
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_PENDING",
		2: "EXECUTION_STATUS_RUNNING",
		3: "EXECUTION_STATUS_COMPLETED",
		4: "EXECUTION_STATUS_FAILED",
		5: "EXECUTION_STATUS_CANCELLED",
		6: "EXECUTION_STATUS_TIMED_OUT",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_PENDING":     1,
		"EXECUTION_STATUS_RUNNING":     2,
		"EXECUTION_STATUS_COMPLETED":   3,
		"EXECUTION_STATUS_FAILED":      4,
		"EXECUTION_STATUS_CANCELLED":   5,
		"EXECUTION_STATUS_TIMED_OUT":   6,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_workflow_workflow_proto_enumTypes[1].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_workflow_workflow_proto_enumTypes[1]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{1}
}

// Step status
type StepStatus int32

const (
	StepStatus_STEP_STATUS_UNSPECIFIED StepStatus = 0
	StepStatus_STEP_STATUS_PENDING     StepStatus = 1
	StepStatus_STEP_STATUS_RUNNING     StepStatus = 2
	StepStatus_STEP_STATUS_COMPLETED   StepStatus = 3
	StepStatus_STEP_STATUS_FAILED      StepStatus = 4
	StepStatus_STEP_STATUS_RETRYING    StepStatus = 5
	StepStatus_STEP_STATUS_CANCELLED   StepStatus = 6
)

// Enum value maps for StepStatus.
var (
	StepStatus_name = map[int32]string{
		0: "STEP_STATUS_UNSPECIFIED",
		1: "STEP_STATUS_PENDING",
		2: "STEP_STATUS_RUNNING",
		3: "STEP_STATUS_COMPLETED",
		4: "STEP_STATUS_FAILED",
		5: "STEP_STATUS_RETRYING",
		6: "STEP_STATUS_CANCELLED",
	}
	StepStatus_value = map[string]int32{
		"STEP_STATUS_UNSPECIFIED": 0,
		"STEP_STATUS_PENDING":     1,
		"STEP_STATUS_RUNNING":     2,
		"STEP_STATUS_COMPLETED":   3,
		"STEP_STATUS_FAILED":      4,
		"STEP_STATUS_RETRYING":    5,
		"STEP_STATUS_CANCELLED":   6,
	}
)

func (x StepStatus) Enum() *StepStatus {
	p := new(StepStatus)
	*p = x
	return p
}

func (x StepStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_workflow_workflow_proto_enumTypes[2].Descriptor()
}

func (StepStatus) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_workflow_workflow_proto_enumTypes[2]
}

func (x StepStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepStatus.Descriptor instead.
func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{2}
}

// Workflow error types
//
// ## Purpose
// Defines error types for workflow operations (storage, serialization, execution).
// Used in error responses and for error handling in workflow service.
type WorkflowError int32

const (
	WorkflowError_WORKFLOW_ERROR_UNSPECIFIED WorkflowError = 0
	// Storage operation failed (database, journal, etc.)
	WorkflowError_WORKFLOW_ERROR_STORAGE WorkflowError = 1
	// Serialization/deserialization failed
	WorkflowError_WORKFLOW_ERROR_SERIALIZATION WorkflowError = 2
	// Workflow or execution not found
	WorkflowError_WORKFLOW_ERROR_NOT_FOUND WorkflowError = 3
	// Invalid workflow definition
	WorkflowError_WORKFLOW_ERROR_INVALID_DEFINITION WorkflowError = 4
	// Execution error (runtime failure)
	WorkflowError_WORKFLOW_ERROR_EXECUTION WorkflowError = 5
)

// Enum value maps for WorkflowError.
var (
	WorkflowError_name = map[int32]string{
		0: "WORKFLOW_ERROR_UNSPECIFIED",
		1: "WORKFLOW_ERROR_STORAGE",
		2: "WORKFLOW_ERROR_SERIALIZATION",
		3: "WORKFLOW_ERROR_NOT_FOUND",
		4: "WORKFLOW_ERROR_INVALID_DEFINITION",
		5: "WORKFLOW_ERROR_EXECUTION",
	}
	WorkflowError_value = map[string]int32{
		"WORKFLOW_ERROR_UNSPECIFIED":        0,
		"WORKFLOW_ERROR_STORAGE":            1,
		"WORKFLOW_ERROR_SERIALIZATION":      2,
		"WORKFLOW_ERROR_NOT_FOUND":          3,
		"WORKFLOW_ERROR_INVALID_DEFINITION": 4,
		"WORKFLOW_ERROR_EXECUTION":          5,
	}
)

func (x WorkflowError) Enum() *WorkflowError {
	p := new(WorkflowError)
	*p = x
	return p
}

func (x WorkflowError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowError) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_workflow_workflow_proto_enumTypes[3].Descriptor()
}

func (WorkflowError) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_workflow_workflow_proto_enumTypes[3]
}

func (x WorkflowError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowError.Descriptor instead.
func (WorkflowError) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{3}
}

// Workflow definition (versioned template)
//
// Stored in database for querying, defines workflow structure as DAG of steps.
type WorkflowDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique definition ID (e.g., "credit-approval")
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Semantic version (e.g., "1.0.0")
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Workflow steps (DAG)
	Steps []*Step `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	// Default timeout for entire workflow
	DefaultTimeout *durationpb.Duration `protobuf:"bytes,5,opt,name=default_timeout,json=defaultTimeout,proto3" json:"default_timeout,omitempty"` // Max 24 hours
	// Default retry policy for steps
	DefaultRetry *RetryConfig `protobuf:"bytes,6,opt,name=default_retry,json=defaultRetry,proto3" json:"default_retry,omitempty"`
	// User-defined labels
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDefinition) Reset() {
	*x = WorkflowDefinition{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDefinition) ProtoMessage() {}

func (x *WorkflowDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDefinition.ProtoReflect.Descriptor instead.
func (*WorkflowDefinition) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowDefinition) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkflowDefinition) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *WorkflowDefinition) GetDefaultTimeout() *durationpb.Duration {
	if x != nil {
		return x.DefaultTimeout
	}
	return nil
}

func (x *WorkflowDefinition) GetDefaultRetry() *RetryConfig {
	if x != nil {
		return x.DefaultRetry
	}
	return nil
}

func (x *WorkflowDefinition) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WorkflowDefinition) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkflowDefinition) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Workflow step definition
//
// Defines a single step in workflow DAG with dependencies, retry, and error handling.
type Step struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique step ID within workflow
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Step type (task, parallel, map, etc.)
	Type StepType `protobuf:"varint,3,opt,name=type,proto3,enum=plexspaces.workflow.v1.StepType" json:"type,omitempty"`
	// Step IDs this depends on (for DAG ordering)
	DependsOn []string `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"` // Max 100 dependencies
	// Step-specific timeout
	Timeout *durationpb.Duration `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"` // Max 1 hour
	// Retry configuration
	Retry *RetryConfig `protobuf:"bytes,6,opt,name=retry,proto3" json:"retry,omitempty"`
	// Step ID to run on error (compensation/saga)
	OnError string `protobuf:"bytes,7,opt,name=on_error,json=onError,proto3" json:"on_error,omitempty"`
	// Type-specific configuration (JSON)
	Config        *structpb.Struct `protobuf:"bytes,8,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *Step) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Step) GetType() StepType {
	if x != nil {
		return x.Type
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (x *Step) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *Step) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Step) GetRetry() *RetryConfig {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *Step) GetOnError() string {
	if x != nil {
		return x.OnError
	}
	return ""
}

func (x *Step) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

// Retry configuration
//
// Exponential backoff retry policy with error type matching.
// When fields are unset (proto3 default: 0 for numbers, empty for repeated), runtime defaults apply:
// - max_attempts: 1 (single attempt, no retries)
// - initial_interval_ms: 100
// - backoff_rate: 2.0 (exponential: delay = initial * rate^(attempt-1) capped at max_interval_ms)
// - max_interval_ms: 30000
// Runtime applies full jitter to delay (multiply by random in (0, 1]) before sleeping between retries.
type RetryConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum retry attempts (1 = single attempt, no retries; unset/0 treated as 1 at runtime)
	MaxAttempts uint32 `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"` // 0 or 1–1000
	// Initial retry interval (milliseconds). Default 100 when unset.
	InitialIntervalMs uint32 `protobuf:"varint,2,opt,name=initial_interval_ms,json=initialIntervalMs,proto3" json:"initial_interval_ms,omitempty"` // 0 or 1–300000
	// Exponential backoff rate (e.g., 2.0 for doubling). Default 2.0 when unset.
	BackoffRate float64 `protobuf:"fixed64,3,opt,name=backoff_rate,json=backoffRate,proto3" json:"backoff_rate,omitempty"`
	// Maximum retry interval (milliseconds). Default 30000 when unset.
	MaxIntervalMs uint32 `protobuf:"varint,4,opt,name=max_interval_ms,json=maxIntervalMs,proto3" json:"max_interval_ms,omitempty"` // 0 or 1–3600000
	// Error types to retry (empty = retry all)
	RetryableErrors []string `protobuf:"bytes,5,rep,name=retryable_errors,json=retryableErrors,proto3" json:"retryable_errors,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetryConfig) Reset() {
	*x = RetryConfig{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryConfig) ProtoMessage() {}

func (x *RetryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryConfig.ProtoReflect.Descriptor instead.
func (*RetryConfig) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *RetryConfig) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryConfig) GetInitialIntervalMs() uint32 {
	if x != nil {
		return x.InitialIntervalMs
	}
	return 0
}

func (x *RetryConfig) GetBackoffRate() float64 {
	if x != nil {
		return x.BackoffRate
	}
	return 0
}

func (x *RetryConfig) GetMaxIntervalMs() uint32 {
	if x != nil {
		return x.MaxIntervalMs
	}
	return 0
}

func (x *RetryConfig) GetRetryableErrors() []string {
	if x != nil {
		return x.RetryableErrors
	}
	return nil
}

// Workflow execution (metadata)
//
// Stored in database for querying. Full state is in journal.
type WorkflowExecution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique execution ID (ULID)
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Workflow definition ID
	DefinitionId string `protobuf:"bytes,2,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	// Workflow definition version
	DefinitionVersion string `protobuf:"bytes,3,opt,name=definition_version,json=definitionVersion,proto3" json:"definition_version,omitempty"`
	// Current execution status
	Status ExecutionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=plexspaces.workflow.v1.ExecutionStatus" json:"status,omitempty"`
	// Currently executing step ID
	CurrentStepId string `protobuf:"bytes,5,opt,name=current_step_id,json=currentStepId,proto3" json:"current_step_id,omitempty"`
	// Initial workflow input
	Input *structpb.Struct `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	// Final workflow output (if completed)
	Output *structpb.Struct `protobuf:"bytes,7,opt,name=output,proto3" json:"output,omitempty"`
	// Error message (if failed)
	Error string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// Node executing this workflow
	NodeId string `protobuf:"bytes,9,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Start timestamp
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Completion timestamp
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Last update timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// User-defined labels
	Labels        map[string]string `protobuf:"bytes,14,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecution) Reset() {
	*x = WorkflowExecution{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecution) ProtoMessage() {}

func (x *WorkflowExecution) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecution.ProtoReflect.Descriptor instead.
func (*WorkflowExecution) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowExecution) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *WorkflowExecution) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *WorkflowExecution) GetDefinitionVersion() string {
	if x != nil {
		return x.DefinitionVersion
	}
	return ""
}

func (x *WorkflowExecution) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *WorkflowExecution) GetCurrentStepId() string {
	if x != nil {
		return x.CurrentStepId
	}
	return ""
}

func (x *WorkflowExecution) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *WorkflowExecution) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *WorkflowExecution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkflowExecution) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WorkflowExecution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkflowExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *WorkflowExecution) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *WorkflowExecution) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WorkflowExecution) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Step execution (metadata)
//
// Stored in database for history/monitoring. Full state in journal.
type StepExecution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique step execution ID (ULID)
	StepExecutionId string `protobuf:"bytes,1,opt,name=step_execution_id,json=stepExecutionId,proto3" json:"step_execution_id,omitempty"`
	// Parent workflow execution ID
	ExecutionId string `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Step definition ID
	StepId string `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Step status
	Status StepStatus `protobuf:"varint,4,opt,name=status,proto3,enum=plexspaces.workflow.v1.StepStatus" json:"status,omitempty"`
	// Step input
	Input *structpb.Struct `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	// Step output
	Output *structpb.Struct `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	// Error message (if failed)
	Error string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	// Retry attempt number
	Attempt uint32 `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"` // Max 1000 attempts
	// Start timestamp
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Completion timestamp
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepExecution) Reset() {
	*x = StepExecution{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepExecution) ProtoMessage() {}

func (x *StepExecution) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepExecution.ProtoReflect.Descriptor instead.
func (*StepExecution) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *StepExecution) GetStepExecutionId() string {
	if x != nil {
		return x.StepExecutionId
	}
	return ""
}

func (x *StepExecution) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StepExecution) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepExecution) GetStatus() StepStatus {
	if x != nil {
		return x.Status
	}
	return StepStatus_STEP_STATUS_UNSPECIFIED
}

func (x *StepExecution) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *StepExecution) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *StepExecution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StepExecution) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *StepExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StepExecution) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type CreateDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *WorkflowDefinition    `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDefinitionRequest) Reset() {
	*x = CreateDefinitionRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDefinitionRequest) ProtoMessage() {}

func (x *CreateDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDefinitionRequest) GetDefinition() *WorkflowDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type CreateDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *WorkflowDefinition    `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDefinitionResponse) Reset() {
	*x = CreateDefinitionResponse{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDefinitionResponse) ProtoMessage() {}

func (x *CreateDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDefinitionResponse.ProtoReflect.Descriptor instead.
func (*CreateDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDefinitionResponse) GetDefinition() *WorkflowDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type GetDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // Empty = latest version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefinitionRequest) Reset() {
	*x = GetDefinitionRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefinitionRequest) ProtoMessage() {}

func (x *GetDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *GetDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDefinitionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *WorkflowDefinition    `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefinitionResponse) Reset() {
	*x = GetDefinitionResponse{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefinitionResponse) ProtoMessage() {}

func (x *GetDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefinitionResponse.ProtoReflect.Descriptor instead.
func (*GetDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *GetDefinitionResponse) GetDefinition() *WorkflowDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type ListDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	LabelFilter   map[string]string      `protobuf:"bytes,2,rep,name=label_filter,json=labelFilter,proto3" json:"label_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NamePrefix    string                 `protobuf:"bytes,3,opt,name=name_prefix,json=namePrefix,proto3" json:"name_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefinitionsRequest) Reset() {
	*x = ListDefinitionsRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefinitionsRequest) ProtoMessage() {}

func (x *ListDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *ListDefinitionsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListDefinitionsRequest) GetLabelFilter() map[string]string {
	if x != nil {
		return x.LabelFilter
	}
	return nil
}

func (x *ListDefinitionsRequest) GetNamePrefix() string {
	if x != nil {
		return x.NamePrefix
	}
	return ""
}

type ListDefinitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definitions   []*WorkflowDefinition  `protobuf:"bytes,1,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefinitionsResponse) Reset() {
	*x = ListDefinitionsResponse{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefinitionsResponse) ProtoMessage() {}

func (x *ListDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *ListDefinitionsResponse) GetDefinitions() []*WorkflowDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *ListDefinitionsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpdateDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *WorkflowDefinition    `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDefinitionRequest) Reset() {
	*x = UpdateDefinitionRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefinitionRequest) ProtoMessage() {}

func (x *UpdateDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefinitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateDefinitionRequest) GetDefinition() *WorkflowDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type UpdateDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *WorkflowDefinition    `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDefinitionResponse) Reset() {
	*x = UpdateDefinitionResponse{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefinitionResponse) ProtoMessage() {}

func (x *UpdateDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefinitionResponse.ProtoReflect.Descriptor instead.
func (*UpdateDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDefinitionResponse) GetDefinition() *WorkflowDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type DeleteDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // Empty = delete all versions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDefinitionRequest) Reset() {
	*x = DeleteDefinitionRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDefinitionRequest) ProtoMessage() {}

func (x *DeleteDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDefinitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteDefinitionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StartExecutionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DefinitionId      string                 `protobuf:"bytes,1,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	DefinitionVersion string                 `protobuf:"bytes,2,opt,name=definition_version,json=definitionVersion,proto3" json:"definition_version,omitempty"` // Empty = latest version
	Input             *structpb.Struct       `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	ExecutionId       string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"` // Optional - auto-generate if empty
	Labels            map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartExecutionRequest) Reset() {
	*x = StartExecutionRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartExecutionRequest) ProtoMessage() {}

func (x *StartExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartExecutionRequest.ProtoReflect.Descriptor instead.
func (*StartExecutionRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *StartExecutionRequest) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *StartExecutionRequest) GetDefinitionVersion() string {
	if x != nil {
		return x.DefinitionVersion
	}
	return ""
}

func (x *StartExecutionRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *StartExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StartExecutionRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type StartExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartExecutionResponse) Reset() {
	*x = StartExecutionResponse{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartExecutionResponse) ProtoMessage() {}

func (x *StartExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartExecutionResponse.ProtoReflect.Descriptor instead.
func (*StartExecutionResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{15}
}

func (x *StartExecutionResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *GetExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *WorkflowExecution     `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionResponse) Reset() {
	*x = GetExecutionResponse{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionResponse) ProtoMessage() {}

func (x *GetExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{17}
}

func (x *GetExecutionResponse) GetExecution() *WorkflowExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type ListExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	DefinitionId  string                 `protobuf:"bytes,2,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=plexspaces.workflow.v1.ExecutionStatus" json:"status,omitempty"`
	LabelFilter   map[string]string      `protobuf:"bytes,4,rep,name=label_filter,json=labelFilter,proto3" json:"label_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartedAfter  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_after,json=startedAfter,proto3" json:"started_after,omitempty"`
	StartedBefore *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_before,json=startedBefore,proto3" json:"started_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsRequest) Reset() {
	*x = ListExecutionsRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsRequest) ProtoMessage() {}

func (x *ListExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{18}
}

func (x *ListExecutionsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListExecutionsRequest) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *ListExecutionsRequest) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ListExecutionsRequest) GetLabelFilter() map[string]string {
	if x != nil {
		return x.LabelFilter
	}
	return nil
}

func (x *ListExecutionsRequest) GetStartedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAfter
	}
	return nil
}

func (x *ListExecutionsRequest) GetStartedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedBefore
	}
	return nil
}

type ListExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*WorkflowExecution   `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsResponse) Reset() {
	*x = ListExecutionsResponse{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsResponse) ProtoMessage() {}

func (x *ListExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{19}
}

func (x *ListExecutionsResponse) GetExecutions() []*WorkflowExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *ListExecutionsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type CancelExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionRequest) Reset() {
	*x = CancelExecutionRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionRequest) ProtoMessage() {}

func (x *CancelExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionRequest.ProtoReflect.Descriptor instead.
func (*CancelExecutionRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{20}
}

func (x *CancelExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CancelExecutionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SignalExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	SignalName    string                 `protobuf:"bytes,2,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	Data          *structpb.Value        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalExecutionRequest) Reset() {
	*x = SignalExecutionRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalExecutionRequest) ProtoMessage() {}

func (x *SignalExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalExecutionRequest.ProtoReflect.Descriptor instead.
func (*SignalExecutionRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{21}
}

func (x *SignalExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SignalExecutionRequest) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *SignalExecutionRequest) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	QueryName     string                 `protobuf:"bytes,2,opt,name=query_name,json=queryName,proto3" json:"query_name,omitempty"` // "status", "context", "current_step"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryExecutionRequest) Reset() {
	*x = QueryExecutionRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExecutionRequest) ProtoMessage() {}

func (x *QueryExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExecutionRequest.ProtoReflect.Descriptor instead.
func (*QueryExecutionRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{22}
}

func (x *QueryExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *QueryExecutionRequest) GetQueryName() string {
	if x != nil {
		return x.QueryName
	}
	return ""
}

type QueryExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *structpb.Value        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryExecutionResponse) Reset() {
	*x = QueryExecutionResponse{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExecutionResponse) ProtoMessage() {}

func (x *QueryExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExecutionResponse.ProtoReflect.Descriptor instead.
func (*QueryExecutionResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{23}
}

func (x *QueryExecutionResponse) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetStepExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStepExecutionsRequest) Reset() {
	*x = GetStepExecutionsRequest{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStepExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStepExecutionsRequest) ProtoMessage() {}

func (x *GetStepExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStepExecutionsRequest.ProtoReflect.Descriptor instead.
func (*GetStepExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{24}
}

func (x *GetStepExecutionsRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetStepExecutionsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetStepExecutionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StepExecutions []*StepExecution       `protobuf:"bytes,1,rep,name=step_executions,json=stepExecutions,proto3" json:"step_executions,omitempty"`
	Page           *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStepExecutionsResponse) Reset() {
	*x = GetStepExecutionsResponse{}
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStepExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStepExecutionsResponse) ProtoMessage() {}

func (x *GetStepExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_workflow_workflow_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStepExecutionsResponse.ProtoReflect.Descriptor instead.
func (*GetStepExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP(), []int{25}
}

func (x *GetStepExecutionsResponse) GetStepExecutions() []*StepExecution {
	if x != nil {
		return x.StepExecutions
	}
	return nil
}

func (x *GetStepExecutionsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_plexspaces_v1_workflow_workflow_proto protoreflect.FileDescriptor

const file_plexspaces_v1_workflow_workflow_proto_rawDesc = "" +
	"\n" +
	"%plexspaces/v1/workflow/workflow.proto\x12\x16plexspaces.workflow.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aplexspaces/v1/common.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xe1\x05\n" +
	"\x12WorkflowDefinition\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x12!\n" +
	"\x04name\x18\x02 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12&\n" +
	"\aversion\x18\x03 \x01(\tB\f\xe0A\x02\xbaH\x06r\x04\x10\x01\x18@R\aversion\x12B\n" +
	"\x05steps\x18\x04 \x03(\v2\x1c.plexspaces.workflow.v1.StepB\x0e\xe0A\x02\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\x05steps\x12P\n" +
	"\x0fdefault_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationB\f\xbaH\t\xaa\x01\x06\"\x04\b\x80\xa3\x05R\x0edefaultTimeout\x12H\n" +
	"\rdefault_retry\x18\x06 \x01(\v2#.plexspaces.workflow.v1.RetryConfigR\fdefaultRetry\x12N\n" +
	"\x06labels\x18\a \x03(\v26.plexspaces.workflow.v1.WorkflowDefinition.LabelsEntryR\x06labels\x12>\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:v\x92As\n" +
	"q*\x13Workflow Definition2<Versioned workflow template defining steps and configuration\xd2\x01\x02id\xd2\x01\x04name\xd2\x01\aversion\xd2\x01\x05steps\"\xe2\x03\n" +
	"\x04Step\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x12!\n" +
	"\x04name\x18\x02 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x129\n" +
	"\x04type\x18\x03 \x01(\x0e2 .plexspaces.workflow.v1.StepTypeB\x03\xe0A\x02R\x04type\x12'\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\tB\b\xbaH\x05\x92\x01\x02\x10dR\tdependsOn\x12@\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xaa\x01\x05\"\x03\b\x90\x1cR\atimeout\x129\n" +
	"\x05retry\x18\x06 \x01(\v2#.plexspaces.workflow.v1.RetryConfigR\x05retry\x12#\n" +
	"\bon_error\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\aonError\x12/\n" +
	"\x06config\x18\b \x01(\v2\x17.google.protobuf.StructR\x06config:a\x92A^\n" +
	"\\*\rWorkflow Step28Single step in workflow with type-specific configuration\xd2\x01\x02id\xd2\x01\x04name\xd2\x01\x04type\"\x89\x03\n" +
	"\vRetryConfig\x12+\n" +
	"\fmax_attempts\x18\x01 \x01(\rB\b\xbaH\x05*\x03\x18\xe8\aR\vmaxAttempts\x129\n" +
	"\x13initial_interval_ms\x18\x02 \x01(\rB\t\xbaH\x06*\x04\x18\xe0\xa7\x12R\x11initialIntervalMs\x12:\n" +
	"\fbackoff_rate\x18\x03 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00$@)\x00\x00\x00\x00\x00\x00\xf0?R\vbackoffRate\x122\n" +
	"\x0fmax_interval_ms\x18\x04 \x01(\rB\n" +
	"\xbaH\a*\x05\x18\x80\xdd\xdb\x01R\rmaxIntervalMs\x12:\n" +
	"\x10retryable_errors\x18\x05 \x03(\tB\x0f\xbaH\f\x92\x01\t\x10d\"\x05r\x03\x18\x80\x02R\x0fretryableErrors:f\x92Ac\n" +
	"a*\x13Retry Configuration2JExponential backoff retry policy. Unset max_attempts means 1 (no retries).\"\xeb\a\n" +
	"\x11WorkflowExecution\x12.\n" +
	"\fexecution_id\x18\x01 \x01(\tB\v\xe0A\x03\xbaH\x05r\x03\x18\xff\x01R\vexecutionId\x122\n" +
	"\rdefinition_id\x18\x02 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\fdefinitionId\x12;\n" +
	"\x12definition_version\x18\x03 \x01(\tB\f\xe0A\x02\xbaH\x06r\x04\x10\x01\x18@R\x11definitionVersion\x12D\n" +
	"\x06status\x18\x04 \x01(\x0e2'.plexspaces.workflow.v1.ExecutionStatusB\x03\xe0A\x03R\x06status\x123\n" +
	"\x0fcurrent_step_id\x18\x05 \x01(\tB\v\xe0A\x03\xbaH\x05r\x03\x18\xff\x01R\rcurrentStepId\x12-\n" +
	"\x05input\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x05input\x124\n" +
	"\x06output\x18\a \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x03R\x06output\x12!\n" +
	"\x05error\x18\b \x01(\tB\v\xe0A\x03\xbaH\x05r\x03\x18\x80\x10R\x05error\x12$\n" +
	"\anode_id\x18\t \x01(\tB\v\xe0A\x03\xbaH\x05r\x03\x18\xff\x01R\x06nodeId\x12>\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tstartedAt\x12B\n" +
	"\fcompleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\vcompletedAt\x12>\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAt\x12M\n" +
	"\x06labels\x18\x0e \x03(\v25.plexspaces.workflow.v1.WorkflowExecution.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:~\x92A{\n" +
	"y*\x12Workflow Execution2&Running or completed workflow instance\xd2\x01\fexecution_id\xd2\x01\rdefinition_id\xd2\x01\x12definition_version\xd2\x01\x06status\"\xa4\x04\n" +
	"\rStepExecution\x124\n" +
	"\x11step_execution_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\x0fstepExecutionId\x12+\n" +
	"\fexecution_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\vexecutionId\x12!\n" +
	"\astep_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\x06stepId\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".plexspaces.workflow.v1.StepStatusR\x06status\x12-\n" +
	"\x05input\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05input\x12/\n" +
	"\x06output\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06output\x12\x1e\n" +
	"\x05error\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10R\x05error\x12\"\n" +
	"\aattempt\x18\b \x01(\rB\b\xbaH\x05*\x03\x18\xe8\aR\aattempt\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt:3\x92A0\n" +
	".*\x0eStep Execution2\x1cSingle step execution record\"j\n" +
	"\x17CreateDefinitionRequest\x12O\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2*.plexspaces.workflow.v1.WorkflowDefinitionB\x03\xe0A\x02R\n" +
	"definition\"f\n" +
	"\x18CreateDefinitionResponse\x12J\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2*.plexspaces.workflow.v1.WorkflowDefinitionR\n" +
	"definition\"X\n" +
	"\x14GetDefinitionRequest\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x12!\n" +
	"\aversion\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@R\aversion\"c\n" +
	"\x15GetDefinitionResponse\x12J\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2*.plexspaces.workflow.v1.WorkflowDefinitionR\n" +
	"definition\"\x9e\x02\n" +
	"\x16ListDefinitionsRequest\x125\n" +
	"\x04page\x18\x01 \x01(\v2!.plexspaces.common.v1.PageRequestR\x04page\x12b\n" +
	"\flabel_filter\x18\x02 \x03(\v2?.plexspaces.workflow.v1.ListDefinitionsRequest.LabelFilterEntryR\vlabelFilter\x12)\n" +
	"\vname_prefix\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\n" +
	"namePrefix\x1a>\n" +
	"\x10LabelFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\x17ListDefinitionsResponse\x12W\n" +
	"\vdefinitions\x18\x01 \x03(\v2*.plexspaces.workflow.v1.WorkflowDefinitionB\t\xbaH\x06\x92\x01\x03\x10\x90NR\vdefinitions\x126\n" +
	"\x04page\x18\x02 \x01(\v2\".plexspaces.common.v1.PageResponseR\x04page\"j\n" +
	"\x17UpdateDefinitionRequest\x12O\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2*.plexspaces.workflow.v1.WorkflowDefinitionB\x03\xe0A\x02R\n" +
	"definition\"f\n" +
	"\x18UpdateDefinitionResponse\x12J\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2*.plexspaces.workflow.v1.WorkflowDefinitionR\n" +
	"definition\"[\n" +
	"\x17DeleteDefinitionRequest\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x12!\n" +
	"\aversion\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@R\aversion\"\xed\x02\n" +
	"\x15StartExecutionRequest\x122\n" +
	"\rdefinition_id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\fdefinitionId\x126\n" +
	"\x12definition_version\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@R\x11definitionVersion\x12-\n" +
	"\x05input\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05input\x12+\n" +
	"\fexecution_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\vexecutionId\x12Q\n" +
	"\x06labels\x18\x05 \x03(\v29.plexspaces.workflow.v1.StartExecutionRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x16StartExecutionResponse\x12+\n" +
	"\fexecution_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\vexecutionId\"G\n" +
	"\x13GetExecutionRequest\x120\n" +
	"\fexecution_id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\vexecutionId\"_\n" +
	"\x14GetExecutionResponse\x12G\n" +
	"\texecution\x18\x01 \x01(\v2).plexspaces.workflow.v1.WorkflowExecutionR\texecution\"\xe5\x03\n" +
	"\x15ListExecutionsRequest\x125\n" +
	"\x04page\x18\x01 \x01(\v2!.plexspaces.common.v1.PageRequestR\x04page\x12-\n" +
	"\rdefinition_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\fdefinitionId\x12?\n" +
	"\x06status\x18\x03 \x01(\x0e2'.plexspaces.workflow.v1.ExecutionStatusR\x06status\x12a\n" +
	"\flabel_filter\x18\x04 \x03(\v2>.plexspaces.workflow.v1.ListExecutionsRequest.LabelFilterEntryR\vlabelFilter\x12?\n" +
	"\rstarted_after\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fstartedAfter\x12A\n" +
	"\x0estarted_before\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rstartedBefore\x1a>\n" +
	"\x10LabelFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\x16ListExecutionsResponse\x12T\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2).plexspaces.workflow.v1.WorkflowExecutionB\t\xbaH\x06\x92\x01\x03\x10\x90NR\n" +
	"executions\x126\n" +
	"\x04page\x18\x02 \x01(\v2\".plexspaces.common.v1.PageResponseR\x04page\"l\n" +
	"\x16CancelExecutionRequest\x120\n" +
	"\fexecution_id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\vexecutionId\x12 \n" +
	"\x06reason\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bR\x06reason\"\xa6\x01\n" +
	"\x16SignalExecutionRequest\x120\n" +
	"\fexecution_id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\vexecutionId\x12.\n" +
	"\vsignal_name\x18\x02 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\n" +
	"signalName\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x04data\"w\n" +
	"\x15QueryExecutionRequest\x120\n" +
	"\fexecution_id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\vexecutionId\x12,\n" +
	"\n" +
	"query_name\x18\x02 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\x80\x01R\tqueryName\"H\n" +
	"\x16QueryExecutionResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06result\"\x83\x01\n" +
	"\x18GetStepExecutionsRequest\x120\n" +
	"\fexecution_id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\vexecutionId\x125\n" +
	"\x04page\x18\x02 \x01(\v2!.plexspaces.common.v1.PageRequestR\x04page\"\xae\x01\n" +
	"\x19GetStepExecutionsResponse\x12Y\n" +
	"\x0fstep_executions\x18\x01 \x03(\v2%.plexspaces.workflow.v1.StepExecutionB\t\xbaH\x06\x92\x01\x03\x10\x90NR\x0estepExecutions\x126\n" +
	"\x04page\x18\x02 \x01(\v2\".plexspaces.common.v1.PageResponseR\x04page*\xa4\x01\n" +
	"\bStepType\x12\x19\n" +
	"\x15STEP_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTEP_TYPE_TASK\x10\x01\x12\x16\n" +
	"\x12STEP_TYPE_PARALLEL\x10\x02\x12\x11\n" +
	"\rSTEP_TYPE_MAP\x10\x03\x12\x12\n" +
	"\x0eSTEP_TYPE_WAIT\x10\x04\x12\x14\n" +
	"\x10STEP_TYPE_CHOICE\x10\x05\x12\x14\n" +
	"\x10STEP_TYPE_SIGNAL\x10\x06*\xec\x01\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EXECUTION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18EXECUTION_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17EXECUTION_STATUS_FAILED\x10\x04\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_CANCELLED\x10\x05\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_TIMED_OUT\x10\x06*\xc3\x01\n" +
	"\n" +
	"StepStatus\x12\x1b\n" +
	"\x17STEP_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STEP_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13STEP_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15STEP_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12STEP_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14STEP_STATUS_RETRYING\x10\x05\x12\x19\n" +
	"\x15STEP_STATUS_CANCELLED\x10\x06*\xd0\x01\n" +
	"\rWorkflowError\x12\x1e\n" +
	"\x1aWORKFLOW_ERROR_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WORKFLOW_ERROR_STORAGE\x10\x01\x12 \n" +
	"\x1cWORKFLOW_ERROR_SERIALIZATION\x10\x02\x12\x1c\n" +
	"\x18WORKFLOW_ERROR_NOT_FOUND\x10\x03\x12%\n" +
	"!WORKFLOW_ERROR_INVALID_DEFINITION\x10\x04\x12\x1c\n" +
	"\x18WORKFLOW_ERROR_EXECUTION\x10\x052\x84\x19\n" +
	"\x0fWorkflowService\x12\x81\x02\n" +
	"\x10CreateDefinition\x12/.plexspaces.workflow.v1.CreateDefinitionRequest\x1a0.plexspaces.workflow.v1.CreateDefinitionResponse\"\x89\x01\x92A^\n" +
	"\vDefinitions\x12\x1aCreate Workflow Definition\x1a3Create a new versioned workflow definition template\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/workflows/definitions\x12\x91\x02\n" +
	"\rGetDefinition\x12,.plexspaces.workflow.v1.GetDefinitionRequest\x1a-.plexspaces.workflow.v1.GetDefinitionResponse\"\xa2\x01\x92Ab\n" +
	"\vDefinitions\x12\x17Get Workflow Definition\x1a:Retrieve workflow definition by ID and version (or latest)\x82\xd3\xe4\x93\x027\x125/api/v1/workflows/definitions/{id}/versions/{version}\x12\xfe\x01\n" +
	"\x0fListDefinitions\x12..plexspaces.workflow.v1.ListDefinitionsRequest\x1a/.plexspaces.workflow.v1.ListDefinitionsResponse\"\x89\x01\x92Aa\n" +
	"\vDefinitions\x12\x19List Workflow Definitions\x1a7List workflow definitions with filtering and pagination\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/workflows/definitions\x12\x9f\x02\n" +
	"\x10UpdateDefinition\x12/.plexspaces.workflow.v1.UpdateDefinitionRequest\x1a0.plexspaces.workflow.v1.UpdateDefinitionResponse\"\xa7\x01\x92AN\n" +
	"\vDefinitions\x12\x1aUpdate Workflow Definition\x1a#Update existing workflow definition\x82\xd3\xe4\x93\x02P:\x01*\x1aK/api/v1/workflows/definitions/{definition.id}/versions/{definition.version}\x12\x93\x02\n" +
	"\x10DeleteDefinition\x12/.plexspaces.workflow.v1.DeleteDefinitionRequest\x1a\x1b.plexspaces.common.v1.Empty\"\xb0\x01\x92Ap\n" +
	"\vDefinitions\x12\x1aDelete Workflow Definition\x1aEDelete workflow definition version (or all versions if version empty)\x82\xd3\xe4\x93\x027*5/api/v1/workflows/definitions/{id}/versions/{version}\x12\xf2\x01\n" +
	"\x0eStartExecution\x12-.plexspaces.workflow.v1.StartExecutionRequest\x1a..plexspaces.workflow.v1.StartExecutionResponse\"\x80\x01\x92AV\n" +
	"\n" +
	"Executions\x12\x18Start Workflow Execution\x1a.Start a new workflow execution from definition\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/workflows/executions\x12\xe8\x01\n" +
	"\fGetExecution\x12+.plexspaces.workflow.v1.GetExecutionRequest\x1a,.plexspaces.workflow.v1.GetExecutionResponse\"}\x92AG\n" +
	"\n" +
	"Executions\x12\x16Get Workflow Execution\x1a!Retrieve workflow execution by ID\x82\xd3\xe4\x93\x02-\x12+/api/v1/workflows/executions/{execution_id}\x12\xf7\x01\n" +
	"\x0eListExecutions\x12-.plexspaces.workflow.v1.ListExecutionsRequest\x1a..plexspaces.workflow.v1.ListExecutionsResponse\"\x85\x01\x92A^\n" +
	"\n" +
	"Executions\x12\x18List Workflow Executions\x1a6List workflow executions with filtering and pagination\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/workflows/executions\x12\xeb\x01\n" +
	"\x0fCancelExecution\x12..plexspaces.workflow.v1.CancelExecutionRequest\x1a\x1b.plexspaces.common.v1.Empty\"\x8a\x01\x92AJ\n" +
	"\n" +
	"Executions\x12\x19Cancel Workflow Execution\x1a!Cancel running workflow execution\x82\xd3\xe4\x93\x027:\x01*\"2/api/v1/workflows/executions/{execution_id}/cancel\x12\x84\x02\n" +
	"\x0fSignalExecution\x12..plexspaces.workflow.v1.SignalExecutionRequest\x1a\x1b.plexspaces.common.v1.Empty\"\xa3\x01\x92Ab\n" +
	"\n" +
	"Executions\x12\x17Send Signal to Workflow\x1a;Send external signal to running workflow (for signal steps)\x82\xd3\xe4\x93\x028:\x01*\"3/api/v1/workflows/executions/{execution_id}/signals\x12\x97\x02\n" +
	"\x0eQueryExecution\x12-.plexspaces.workflow.v1.QueryExecutionRequest\x1a..plexspaces.workflow.v1.QueryExecutionResponse\"\xa5\x01\x92Af\n" +
	"\n" +
	"Executions\x12\x18Query Workflow Execution\x1a>Query workflow execution state (status, context, current step)\x82\xd3\xe4\x93\x026:\x01*\"1/api/v1/workflows/executions/{execution_id}/query\x12\x81\x02\n" +
	"\x11GetStepExecutions\x120.plexspaces.workflow.v1.GetStepExecutionsRequest\x1a1.plexspaces.workflow.v1.GetStepExecutionsResponse\"\x86\x01\x92AJ\n" +
	"\n" +
	"Executions\x12\x13Get Step Executions\x1a'Get step execution history for workflow\x82\xd3\xe4\x93\x023\x121/api/v1/workflows/executions/{execution_id}/steps\x1a3\x92A0\x12.Simple, durable workflow orchestration serviceB\xdf\x04\x92A\xd9\x02\x12~\n" +
	"\x17PlexSpaces Workflow API\x12*Simple, durable workflow orchestration API\"2\n" +
	"\n" +
	"PlexSpaces\x12$https://github.com/bhatti/plexspaces2\x031.0*\x02\x02\x012\x10application/json:\x10application/jsonR9\n" +
	"\x03400\x122\n" +
	"\x0fInvalid request\x12\x1f\n" +
	"\x1d\x1a\x1b.plexspaces.common.v1.ErrorR3\n" +
	"\x03404\x12,\n" +
	"\tNot found\x12\x1f\n" +
	"\x1d\x1a\x1b.plexspaces.common.v1.ErrorR?\n" +
	"\x03500\x128\n" +
	"\x15Internal server error\x12\x1f\n" +
	"\x1d\x1a\x1b.plexspaces.common.v1.Error\n" +
	"\x1acom.plexspaces.workflow.v1B\rWorkflowProtoP\x01Z[github.com/plexobject/plexspaces/sdks/go/plexspaces/proto/plexspaces/v1/workflow;workflowv1\xa2\x02\x03PWX\xaa\x02\x16Plexspaces.Workflow.V1\xca\x02\x16Plexspaces\\Workflow\\V1\xe2\x02\"Plexspaces\\Workflow\\V1\\GPBMetadata\xea\x02\x18Plexspaces::Workflow::V1b\x06proto3"

var (
	file_plexspaces_v1_workflow_workflow_proto_rawDescOnce sync.Once
	file_plexspaces_v1_workflow_workflow_proto_rawDescData []byte
)

func file_plexspaces_v1_workflow_workflow_proto_rawDescGZIP() []byte {
	file_plexspaces_v1_workflow_workflow_proto_rawDescOnce.Do(func() {
		file_plexspaces_v1_workflow_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plexspaces_v1_workflow_workflow_proto_rawDesc), len(file_plexspaces_v1_workflow_workflow_proto_rawDesc)))
	})
	return file_plexspaces_v1_workflow_workflow_proto_rawDescData
}

var file_plexspaces_v1_workflow_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_plexspaces_v1_workflow_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_plexspaces_v1_workflow_workflow_proto_goTypes = []any{
	(StepType)(0),                     // 0: plexspaces.workflow.v1.StepType
	(ExecutionStatus)(0),              // 1: plexspaces.workflow.v1.ExecutionStatus
	(StepStatus)(0),                   // 2: plexspaces.workflow.v1.StepStatus
	(WorkflowError)(0),                // 3: plexspaces.workflow.v1.WorkflowError
	(*WorkflowDefinition)(nil),        // 4: plexspaces.workflow.v1.WorkflowDefinition
	(*Step)(nil),                      // 5: plexspaces.workflow.v1.Step
	(*RetryConfig)(nil),               // 6: plexspaces.workflow.v1.RetryConfig
	(*WorkflowExecution)(nil),         // 7: plexspaces.workflow.v1.WorkflowExecution
	(*StepExecution)(nil),             // 8: plexspaces.workflow.v1.StepExecution
	(*CreateDefinitionRequest)(nil),   // 9: plexspaces.workflow.v1.CreateDefinitionRequest
	(*CreateDefinitionResponse)(nil),  // 10: plexspaces.workflow.v1.CreateDefinitionResponse
	(*GetDefinitionRequest)(nil),      // 11: plexspaces.workflow.v1.GetDefinitionRequest
	(*GetDefinitionResponse)(nil),     // 12: plexspaces.workflow.v1.GetDefinitionResponse
	(*ListDefinitionsRequest)(nil),    // 13: plexspaces.workflow.v1.ListDefinitionsRequest
	(*ListDefinitionsResponse)(nil),   // 14: plexspaces.workflow.v1.ListDefinitionsResponse
	(*UpdateDefinitionRequest)(nil),   // 15: plexspaces.workflow.v1.UpdateDefinitionRequest
	(*UpdateDefinitionResponse)(nil),  // 16: plexspaces.workflow.v1.UpdateDefinitionResponse
	(*DeleteDefinitionRequest)(nil),   // 17: plexspaces.workflow.v1.DeleteDefinitionRequest
	(*StartExecutionRequest)(nil),     // 18: plexspaces.workflow.v1.StartExecutionRequest
	(*StartExecutionResponse)(nil),    // 19: plexspaces.workflow.v1.StartExecutionResponse
	(*GetExecutionRequest)(nil),       // 20: plexspaces.workflow.v1.GetExecutionRequest
	(*GetExecutionResponse)(nil),      // 21: plexspaces.workflow.v1.GetExecutionResponse
	(*ListExecutionsRequest)(nil),     // 22: plexspaces.workflow.v1.ListExecutionsRequest
	(*ListExecutionsResponse)(nil),    // 23: plexspaces.workflow.v1.ListExecutionsResponse
	(*CancelExecutionRequest)(nil),    // 24: plexspaces.workflow.v1.CancelExecutionRequest
	(*SignalExecutionRequest)(nil),    // 25: plexspaces.workflow.v1.SignalExecutionRequest
	(*QueryExecutionRequest)(nil),     // 26: plexspaces.workflow.v1.QueryExecutionRequest
	(*QueryExecutionResponse)(nil),    // 27: plexspaces.workflow.v1.QueryExecutionResponse
	(*GetStepExecutionsRequest)(nil),  // 28: plexspaces.workflow.v1.GetStepExecutionsRequest
	(*GetStepExecutionsResponse)(nil), // 29: plexspaces.workflow.v1.GetStepExecutionsResponse
	nil,                               // 30: plexspaces.workflow.v1.WorkflowDefinition.LabelsEntry
	nil,                               // 31: plexspaces.workflow.v1.WorkflowExecution.LabelsEntry
	nil,                               // 32: plexspaces.workflow.v1.ListDefinitionsRequest.LabelFilterEntry
	nil,                               // 33: plexspaces.workflow.v1.StartExecutionRequest.LabelsEntry
	nil,                               // 34: plexspaces.workflow.v1.ListExecutionsRequest.LabelFilterEntry
	(*durationpb.Duration)(nil),       // 35: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),     // 36: google.protobuf.Timestamp
	(*structpb.Struct)(nil),           // 37: google.protobuf.Struct
	(*v1.PageRequest)(nil),            // 38: plexspaces.common.v1.PageRequest
	(*v1.PageResponse)(nil),           // 39: plexspaces.common.v1.PageResponse
	(*structpb.Value)(nil),            // 40: google.protobuf.Value
	(*v1.Empty)(nil),                  // 41: plexspaces.common.v1.Empty
}
var file_plexspaces_v1_workflow_workflow_proto_depIdxs = []int32{
	5,  // 0: plexspaces.workflow.v1.WorkflowDefinition.steps:type_name -> plexspaces.workflow.v1.Step
	35, // 1: plexspaces.workflow.v1.WorkflowDefinition.default_timeout:type_name -> google.protobuf.Duration
	6,  // 2: plexspaces.workflow.v1.WorkflowDefinition.default_retry:type_name -> plexspaces.workflow.v1.RetryConfig
	30, // 3: plexspaces.workflow.v1.WorkflowDefinition.labels:type_name -> plexspaces.workflow.v1.WorkflowDefinition.LabelsEntry
	36, // 4: plexspaces.workflow.v1.WorkflowDefinition.created_at:type_name -> google.protobuf.Timestamp
	36, // 5: plexspaces.workflow.v1.WorkflowDefinition.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: plexspaces.workflow.v1.Step.type:type_name -> plexspaces.workflow.v1.StepType
	35, // 7: plexspaces.workflow.v1.Step.timeout:type_name -> google.protobuf.Duration
	6,  // 8: plexspaces.workflow.v1.Step.retry:type_name -> plexspaces.workflow.v1.RetryConfig
	37, // 9: plexspaces.workflow.v1.Step.config:type_name -> google.protobuf.Struct
	1,  // 10: plexspaces.workflow.v1.WorkflowExecution.status:type_name -> plexspaces.workflow.v1.ExecutionStatus
	37, // 11: plexspaces.workflow.v1.WorkflowExecution.input:type_name -> google.protobuf.Struct
	37, // 12: plexspaces.workflow.v1.WorkflowExecution.output:type_name -> google.protobuf.Struct
	36, // 13: plexspaces.workflow.v1.WorkflowExecution.created_at:type_name -> google.protobuf.Timestamp
	36, // 14: plexspaces.workflow.v1.WorkflowExecution.started_at:type_name -> google.protobuf.Timestamp
	36, // 15: plexspaces.workflow.v1.WorkflowExecution.completed_at:type_name -> google.protobuf.Timestamp
	36, // 16: plexspaces.workflow.v1.WorkflowExecution.updated_at:type_name -> google.protobuf.Timestamp
	31, // 17: plexspaces.workflow.v1.WorkflowExecution.labels:type_name -> plexspaces.workflow.v1.WorkflowExecution.LabelsEntry
	2,  // 18: plexspaces.workflow.v1.StepExecution.status:type_name -> plexspaces.workflow.v1.StepStatus
	37, // 19: plexspaces.workflow.v1.StepExecution.input:type_name -> google.protobuf.Struct
	37, // 20: plexspaces.workflow.v1.StepExecution.output:type_name -> google.protobuf.Struct
	36, // 21: plexspaces.workflow.v1.StepExecution.started_at:type_name -> google.protobuf.Timestamp
	36, // 22: plexspaces.workflow.v1.StepExecution.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 23: plexspaces.workflow.v1.CreateDefinitionRequest.definition:type_name -> plexspaces.workflow.v1.WorkflowDefinition
	4,  // 24: plexspaces.workflow.v1.CreateDefinitionResponse.definition:type_name -> plexspaces.workflow.v1.WorkflowDefinition
	4,  // 25: plexspaces.workflow.v1.GetDefinitionResponse.definition:type_name -> plexspaces.workflow.v1.WorkflowDefinition
	38, // 26: plexspaces.workflow.v1.ListDefinitionsRequest.page:type_name -> plexspaces.common.v1.PageRequest
	32, // 27: plexspaces.workflow.v1.ListDefinitionsRequest.label_filter:type_name -> plexspaces.workflow.v1.ListDefinitionsRequest.LabelFilterEntry
	4,  // 28: plexspaces.workflow.v1.ListDefinitionsResponse.definitions:type_name -> plexspaces.workflow.v1.WorkflowDefinition
	39, // 29: plexspaces.workflow.v1.ListDefinitionsResponse.page:type_name -> plexspaces.common.v1.PageResponse
	4,  // 30: plexspaces.workflow.v1.UpdateDefinitionRequest.definition:type_name -> plexspaces.workflow.v1.WorkflowDefinition
	4,  // 31: plexspaces.workflow.v1.UpdateDefinitionResponse.definition:type_name -> plexspaces.workflow.v1.WorkflowDefinition
	37, // 32: plexspaces.workflow.v1.StartExecutionRequest.input:type_name -> google.protobuf.Struct
	33, // 33: plexspaces.workflow.v1.StartExecutionRequest.labels:type_name -> plexspaces.workflow.v1.StartExecutionRequest.LabelsEntry
	7,  // 34: plexspaces.workflow.v1.GetExecutionResponse.execution:type_name -> plexspaces.workflow.v1.WorkflowExecution
	38, // 35: plexspaces.workflow.v1.ListExecutionsRequest.page:type_name -> plexspaces.common.v1.PageRequest
	1,  // 36: plexspaces.workflow.v1.ListExecutionsRequest.status:type_name -> plexspaces.workflow.v1.ExecutionStatus
	34, // 37: plexspaces.workflow.v1.ListExecutionsRequest.label_filter:type_name -> plexspaces.workflow.v1.ListExecutionsRequest.LabelFilterEntry
	36, // 38: plexspaces.workflow.v1.ListExecutionsRequest.started_after:type_name -> google.protobuf.Timestamp
	36, // 39: plexspaces.workflow.v1.ListExecutionsRequest.started_before:type_name -> google.protobuf.Timestamp
	7,  // 40: plexspaces.workflow.v1.ListExecutionsResponse.executions:type_name -> plexspaces.workflow.v1.WorkflowExecution
	39, // 41: plexspaces.workflow.v1.ListExecutionsResponse.page:type_name -> plexspaces.common.v1.PageResponse
	40, // 42: plexspaces.workflow.v1.SignalExecutionRequest.data:type_name -> google.protobuf.Value
	40, // 43: plexspaces.workflow.v1.QueryExecutionResponse.result:type_name -> google.protobuf.Value
	38, // 44: plexspaces.workflow.v1.GetStepExecutionsRequest.page:type_name -> plexspaces.common.v1.PageRequest
	8,  // 45: plexspaces.workflow.v1.GetStepExecutionsResponse.step_executions:type_name -> plexspaces.workflow.v1.StepExecution
	39, // 46: plexspaces.workflow.v1.GetStepExecutionsResponse.page:type_name -> plexspaces.common.v1.PageResponse
	9,  // 47: plexspaces.workflow.v1.WorkflowService.CreateDefinition:input_type -> plexspaces.workflow.v1.CreateDefinitionRequest
	11, // 48: plexspaces.workflow.v1.WorkflowService.GetDefinition:input_type -> plexspaces.workflow.v1.GetDefinitionRequest
	13, // 49: plexspaces.workflow.v1.WorkflowService.ListDefinitions:input_type -> plexspaces.workflow.v1.ListDefinitionsRequest
	15, // 50: plexspaces.workflow.v1.WorkflowService.UpdateDefinition:input_type -> plexspaces.workflow.v1.UpdateDefinitionRequest
	17, // 51: plexspaces.workflow.v1.WorkflowService.DeleteDefinition:input_type -> plexspaces.workflow.v1.DeleteDefinitionRequest
	18, // 52: plexspaces.workflow.v1.WorkflowService.StartExecution:input_type -> plexspaces.workflow.v1.StartExecutionRequest
	20, // 53: plexspaces.workflow.v1.WorkflowService.GetExecution:input_type -> plexspaces.workflow.v1.GetExecutionRequest
	22, // 54: plexspaces.workflow.v1.WorkflowService.ListExecutions:input_type -> plexspaces.workflow.v1.ListExecutionsRequest
	24, // 55: plexspaces.workflow.v1.WorkflowService.CancelExecution:input_type -> plexspaces.workflow.v1.CancelExecutionRequest
	25, // 56: plexspaces.workflow.v1.WorkflowService.SignalExecution:input_type -> plexspaces.workflow.v1.SignalExecutionRequest
	26, // 57: plexspaces.workflow.v1.WorkflowService.QueryExecution:input_type -> plexspaces.workflow.v1.QueryExecutionRequest
	28, // 58: plexspaces.workflow.v1.WorkflowService.GetStepExecutions:input_type -> plexspaces.workflow.v1.GetStepExecutionsRequest
	10, // 59: plexspaces.workflow.v1.WorkflowService.CreateDefinition:output_type -> plexspaces.workflow.v1.CreateDefinitionResponse
	12, // 60: plexspaces.workflow.v1.WorkflowService.GetDefinition:output_type -> plexspaces.workflow.v1.GetDefinitionResponse
	14, // 61: plexspaces.workflow.v1.WorkflowService.ListDefinitions:output_type -> plexspaces.workflow.v1.ListDefinitionsResponse
	16, // 62: plexspaces.workflow.v1.WorkflowService.UpdateDefinition:output_type -> plexspaces.workflow.v1.UpdateDefinitionResponse
	41, // 63: plexspaces.workflow.v1.WorkflowService.DeleteDefinition:output_type -> plexspaces.common.v1.Empty
	19, // 64: plexspaces.workflow.v1.WorkflowService.StartExecution:output_type -> plexspaces.workflow.v1.StartExecutionResponse
	21, // 65: plexspaces.workflow.v1.WorkflowService.GetExecution:output_type -> plexspaces.workflow.v1.GetExecutionResponse
	23, // 66: plexspaces.workflow.v1.WorkflowService.ListExecutions:output_type -> plexspaces.workflow.v1.ListExecutionsResponse
	41, // 67: plexspaces.workflow.v1.WorkflowService.CancelExecution:output_type -> plexspaces.common.v1.Empty
	41, // 68: plexspaces.workflow.v1.WorkflowService.SignalExecution:output_type -> plexspaces.common.v1.Empty
	27, // 69: plexspaces.workflow.v1.WorkflowService.QueryExecution:output_type -> plexspaces.workflow.v1.QueryExecutionResponse
	29, // 70: plexspaces.workflow.v1.WorkflowService.GetStepExecutions:output_type -> plexspaces.workflow.v1.GetStepExecutionsResponse
	59, // [59:71] is the sub-list for method output_type
	47, // [47:59] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_plexspaces_v1_workflow_workflow_proto_init() }
func file_plexspaces_v1_workflow_workflow_proto_init() {
	if File_plexspaces_v1_workflow_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plexspaces_v1_workflow_workflow_proto_rawDesc), len(file_plexspaces_v1_workflow_workflow_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plexspaces_v1_workflow_workflow_proto_goTypes,
		DependencyIndexes: file_plexspaces_v1_workflow_workflow_proto_depIdxs,
		EnumInfos:         file_plexspaces_v1_workflow_workflow_proto_enumTypes,
		MessageInfos:      file_plexspaces_v1_workflow_workflow_proto_msgTypes,
	}.Build()
	File_plexspaces_v1_workflow_workflow_proto = out.File
	file_plexspaces_v1_workflow_workflow_proto_goTypes = nil
	file_plexspaces_v1_workflow_workflow_proto_depIdxs = nil
}
