// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright (C) 2025 PlexSpaces Contributors
//
// Re-exports of proto-generated TypeScript types for SDK consumers.
//
// These types are generated by `make proto-typescript` (ts-proto, onlyTypes=true) and
// committed to sdks/typescript/src/generated/proto/.  The WIT JSON boundary in host.ts
// is unchanged — these types exist so TypeScript callers can pass typed objects instead
// of plain JSON when constructing messages and configs.
//
// Usage:
//   import type { RetryConfig, ErrorDetail, ActorConfig } from '@plexspaces/sdk/proto';
//
// If generated/proto does not yet exist (before first `make proto-typescript` run), this
// file exports empty type stubs so the SDK still compiles.

// ── Workflow types ────────────────────────────────────────────────────────────
export type { RetryConfig } from './generated/proto/plexspaces/v1/workflow/workflow';

// ── Common / error types ──────────────────────────────────────────────────────
export type { ErrorDetail, Message, RequestContext, Facet } from './generated/proto/plexspaces/v1/common';

// ── Actor runtime / config ────────────────────────────────────────────────────
export type { ActorConfig } from './generated/proto/plexspaces/v1/actors/actor_runtime';
