// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright (C) 2025 Shahzad A. Bhatti <bhatti@plexobject.com>
//
// This file is part of PlexSpaces.
//
// PlexSpaces is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 2.1 of the License, or
// (at your option) any later version.
//
// PlexSpaces is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with PlexSpaces. If not, see <https://www.gnu.org/licenses/>.

// PlexSpaces Application API
//
// ## Purpose
// Defines the Application abstraction for PlexSpaces, following Erlang/OTP principles.
// Applications are business logic layers that run on PlexSpaces nodes.
//
// ## Architecture Context
// In PlexSpaces (following Erlang/OTP):
// - **Node** = Infrastructure layer (gRPC, actor registry, remoting, health)
// - **Application** = Business logic layer (supervision trees, workers, domain actors)
// - **Release** = Docker image with Node binary as entry point
//
// ## Design Principles
// 1. Multi-tenant: Multiple applications per node (application-level deployment)
// 2. Clear separation of concerns - Node provides infra, Application implements logic
// 3. Independent lifecycle - Applications start/stop without restarting node
// 4. AWS Lambda-like deployment model - deploy entire applications, not individual actors
//
// ## Component Interactions
// - Used by: Node (to load and manage applications)
// - Depends on: common.proto (Metadata, Timestamp), node.proto (ReleaseSpec), wasm.proto (WasmModule)
// - Related: node.proto (Node infrastructure)
//
// ## Design Decisions
// - Why ApplicationConfig in proto: Can be parsed from TOML and validated
// - Why HealthStatus enum: Standard states for Kubernetes probes
// - Why ShutdownStrategy: Support both graceful and immediate shutdown patterns
// - Why ApplicationSpec: Defines supervision tree structure (Erlang/OTP style)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plexspaces/v1/application/application.proto

package applicationv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/plexobject/plexspaces/sdks/go/plexspaces/proto/plexspaces/v1"
	wasm "github.com/plexobject/plexspaces/sdks/go/plexspaces/proto/plexspaces/v1/wasm"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Application type
type ApplicationType int32

const (
	// Unspecified (invalid)
	ApplicationType_APPLICATION_TYPE_UNSPECIFIED ApplicationType = 0
	// Library application (just modules, no processes)
	// e.g., plexspaces-core
	ApplicationType_APPLICATION_TYPE_LIBRARY ApplicationType = 1
	// Active application (has supervision tree and processes)
	// e.g., byzantine-generals, heat-diffusion
	ApplicationType_APPLICATION_TYPE_ACTIVE ApplicationType = 2
)

// Enum value maps for ApplicationType.
var (
	ApplicationType_name = map[int32]string{
		0: "APPLICATION_TYPE_UNSPECIFIED",
		1: "APPLICATION_TYPE_LIBRARY",
		2: "APPLICATION_TYPE_ACTIVE",
	}
	ApplicationType_value = map[string]int32{
		"APPLICATION_TYPE_UNSPECIFIED": 0,
		"APPLICATION_TYPE_LIBRARY":     1,
		"APPLICATION_TYPE_ACTIVE":      2,
	}
)

func (x ApplicationType) Enum() *ApplicationType {
	p := new(ApplicationType)
	*p = x
	return p
}

func (x ApplicationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationType) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_application_application_proto_enumTypes[0].Descriptor()
}

func (ApplicationType) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_application_application_proto_enumTypes[0]
}

func (x ApplicationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationType.Descriptor instead.
func (ApplicationType) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{0}
}

// Supervision strategy (Erlang/OTP)
type SupervisionStrategy int32

const (
	// Unspecified (default to one_for_one)
	SupervisionStrategy_SUPERVISION_STRATEGY_UNSPECIFIED SupervisionStrategy = 0
	// One-for-One: Only restart failed child
	// If child A crashes, restart only A
	SupervisionStrategy_SUPERVISION_STRATEGY_ONE_FOR_ONE SupervisionStrategy = 1
	// One-for-All: Restart all children if one fails
	// If child A crashes, restart A, B, C
	SupervisionStrategy_SUPERVISION_STRATEGY_ONE_FOR_ALL SupervisionStrategy = 2
	// Rest-for-One: Restart failed child and those started after it
	// If child B crashes (started after A), restart B, C (not A)
	SupervisionStrategy_SUPERVISION_STRATEGY_REST_FOR_ONE SupervisionStrategy = 3
)

// Enum value maps for SupervisionStrategy.
var (
	SupervisionStrategy_name = map[int32]string{
		0: "SUPERVISION_STRATEGY_UNSPECIFIED",
		1: "SUPERVISION_STRATEGY_ONE_FOR_ONE",
		2: "SUPERVISION_STRATEGY_ONE_FOR_ALL",
		3: "SUPERVISION_STRATEGY_REST_FOR_ONE",
	}
	SupervisionStrategy_value = map[string]int32{
		"SUPERVISION_STRATEGY_UNSPECIFIED":  0,
		"SUPERVISION_STRATEGY_ONE_FOR_ONE":  1,
		"SUPERVISION_STRATEGY_ONE_FOR_ALL":  2,
		"SUPERVISION_STRATEGY_REST_FOR_ONE": 3,
	}
)

func (x SupervisionStrategy) Enum() *SupervisionStrategy {
	p := new(SupervisionStrategy)
	*p = x
	return p
}

func (x SupervisionStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SupervisionStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_application_application_proto_enumTypes[1].Descriptor()
}

func (SupervisionStrategy) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_application_application_proto_enumTypes[1]
}

func (x SupervisionStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SupervisionStrategy.Descriptor instead.
func (SupervisionStrategy) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{1}
}

// Child type
type ChildType int32

const (
	// Unspecified (invalid)
	ChildType_CHILD_TYPE_UNSPECIFIED ChildType = 0
	// Worker process (actor)
	ChildType_CHILD_TYPE_WORKER ChildType = 1
	// Supervisor process (manages other children)
	ChildType_CHILD_TYPE_SUPERVISOR ChildType = 2
)

// Enum value maps for ChildType.
var (
	ChildType_name = map[int32]string{
		0: "CHILD_TYPE_UNSPECIFIED",
		1: "CHILD_TYPE_WORKER",
		2: "CHILD_TYPE_SUPERVISOR",
	}
	ChildType_value = map[string]int32{
		"CHILD_TYPE_UNSPECIFIED": 0,
		"CHILD_TYPE_WORKER":      1,
		"CHILD_TYPE_SUPERVISOR":  2,
	}
)

func (x ChildType) Enum() *ChildType {
	p := new(ChildType)
	*p = x
	return p
}

func (x ChildType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChildType) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_application_application_proto_enumTypes[2].Descriptor()
}

func (ChildType) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_application_application_proto_enumTypes[2]
}

func (x ChildType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChildType.Descriptor instead.
func (ChildType) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{2}
}

// Restart policy (Erlang/OTP)
type RestartPolicy int32

const (
	// Unspecified (default to permanent)
	RestartPolicy_RESTART_POLICY_UNSPECIFIED RestartPolicy = 0
	// Permanent: Always restart on failure
	// Use for critical long-running processes
	RestartPolicy_RESTART_POLICY_PERMANENT RestartPolicy = 1
	// Transient: Restart only if abnormal exit (error)
	// Don't restart if normal exit (shutdown)
	// Use for tasks that may complete successfully
	RestartPolicy_RESTART_POLICY_TRANSIENT RestartPolicy = 2
	// Temporary: Never restart
	// Use for one-shot tasks
	RestartPolicy_RESTART_POLICY_TEMPORARY RestartPolicy = 3
)

// Enum value maps for RestartPolicy.
var (
	RestartPolicy_name = map[int32]string{
		0: "RESTART_POLICY_UNSPECIFIED",
		1: "RESTART_POLICY_PERMANENT",
		2: "RESTART_POLICY_TRANSIENT",
		3: "RESTART_POLICY_TEMPORARY",
	}
	RestartPolicy_value = map[string]int32{
		"RESTART_POLICY_UNSPECIFIED": 0,
		"RESTART_POLICY_PERMANENT":   1,
		"RESTART_POLICY_TRANSIENT":   2,
		"RESTART_POLICY_TEMPORARY":   3,
	}
)

func (x RestartPolicy) Enum() *RestartPolicy {
	p := new(RestartPolicy)
	*p = x
	return p
}

func (x RestartPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestartPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_application_application_proto_enumTypes[3].Descriptor()
}

func (RestartPolicy) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_application_application_proto_enumTypes[3]
}

func (x RestartPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestartPolicy.Descriptor instead.
func (RestartPolicy) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{3}
}

// Shutdown strategy for application.
//
// ## Purpose
// Determines how application shutdown is handled.
//
// ## Strategies
// - GRACEFUL: Wait for in-flight work to complete (up to timeout)
// - IMMEDIATE: Stop immediately without draining work
//
// ## Design Notes
// - Default is GRACEFUL for production safety
// - IMMEDIATE useful for dev/test or when work is not critical
type ShutdownStrategy int32

const (
	// Unspecified (defaults to GRACEFUL)
	ShutdownStrategy_SHUTDOWN_STRATEGY_UNSPECIFIED ShutdownStrategy = 0
	// Wait for in-flight work to complete (up to shutdown_timeout)
	//
	// Shutdown sequence:
	// 1. Stop accepting new work
	// 2. Drain in-flight messages/tasks
	// 3. Save durable state (if applicable)
	// 4. Stop supervision tree and actors
	// 5. Disconnect from external services
	ShutdownStrategy_SHUTDOWN_STRATEGY_GRACEFUL ShutdownStrategy = 1
	// Stop immediately without draining work
	//
	// Shutdown sequence:
	// 1. Stop supervision tree immediately
	// 2. Terminate actors (may lose in-flight work)
	// 3. Exit
	ShutdownStrategy_SHUTDOWN_STRATEGY_IMMEDIATE ShutdownStrategy = 2
)

// Enum value maps for ShutdownStrategy.
var (
	ShutdownStrategy_name = map[int32]string{
		0: "SHUTDOWN_STRATEGY_UNSPECIFIED",
		1: "SHUTDOWN_STRATEGY_GRACEFUL",
		2: "SHUTDOWN_STRATEGY_IMMEDIATE",
	}
	ShutdownStrategy_value = map[string]int32{
		"SHUTDOWN_STRATEGY_UNSPECIFIED": 0,
		"SHUTDOWN_STRATEGY_GRACEFUL":    1,
		"SHUTDOWN_STRATEGY_IMMEDIATE":   2,
	}
)

func (x ShutdownStrategy) Enum() *ShutdownStrategy {
	p := new(ShutdownStrategy)
	*p = x
	return p
}

func (x ShutdownStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShutdownStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_application_application_proto_enumTypes[4].Descriptor()
}

func (ShutdownStrategy) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_application_application_proto_enumTypes[4]
}

func (x ShutdownStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShutdownStrategy.Descriptor instead.
func (ShutdownStrategy) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{4}
}

// Health status for application.
//
// ## Purpose
// Represents the health state of an application for monitoring and orchestration.
// Used for Kubernetes liveness/readiness probes and load balancing decisions.
//
// ## States
// - HEALTHY: Application functioning normally (ready to accept traffic)
// - DEGRADED: Running but reduced capacity (e.g., some workers down, still accepts traffic)
// - UNHEALTHY: Not functioning (should trigger restart/failover, do not route traffic)
//
// ## Design Notes
// - Maps to Kubernetes probe states (healthy = ready, unhealthy = not ready)
// - DEGRADED allows partial operation (some failures tolerated)
type HealthStatus int32

const (
	// Unspecified (should not be used, defaults to UNHEALTHY for safety)
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	// Application is functioning normally
	//
	// - All critical components running
	// - Can accept full workload
	// - Ready for traffic
	HealthStatus_HEALTH_STATUS_HEALTHY HealthStatus = 1
	// Application is running but with reduced capacity
	//
	// - Some non-critical components failed
	// - Still accepting work but at reduced rate
	// - Example: 2 of 5 workers down (still functional)
	HealthStatus_HEALTH_STATUS_DEGRADED HealthStatus = 2
	// Application is not functioning
	//
	// - Critical components failed
	// - Cannot process work reliably
	// - Should trigger restart or failover
	HealthStatus_HEALTH_STATUS_UNHEALTHY HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_application_application_proto_enumTypes[5].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_application_application_proto_enumTypes[5]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{5}
}

// Application state in lifecycle.
//
// ## Purpose
// Track application lifecycle state for management and monitoring.
//
// ## State Transitions
// ```
// CREATED -> STARTING -> RUNNING -> STOPPING -> STOPPED
//
//	|
//	+-> FAILED (restart or stop)
//
// ```
//
// ## Design Notes
// - CREATED: Config loaded, not yet started
// - STARTING: start() called, spawning resources
// - RUNNING: Fully operational
// - STOPPING: stop() called, draining work
// - STOPPED: Cleanly shut down
// - FAILED: Crashed or failed health checks
type ApplicationState int32

const (
	// Unspecified
	ApplicationState_APPLICATION_STATE_UNSPECIFIED ApplicationState = 0
	// Configuration loaded, not yet started
	ApplicationState_APPLICATION_STATE_CREATED ApplicationState = 1
	// start() called, spawning supervision tree and actors
	ApplicationState_APPLICATION_STATE_STARTING ApplicationState = 2
	// Fully operational and processing work
	ApplicationState_APPLICATION_STATE_RUNNING ApplicationState = 3
	// stop() called, draining in-flight work
	ApplicationState_APPLICATION_STATE_STOPPING ApplicationState = 4
	// Cleanly shut down
	ApplicationState_APPLICATION_STATE_STOPPED ApplicationState = 5
	// Crashed or failed health checks (may restart)
	ApplicationState_APPLICATION_STATE_FAILED ApplicationState = 6
)

// Enum value maps for ApplicationState.
var (
	ApplicationState_name = map[int32]string{
		0: "APPLICATION_STATE_UNSPECIFIED",
		1: "APPLICATION_STATE_CREATED",
		2: "APPLICATION_STATE_STARTING",
		3: "APPLICATION_STATE_RUNNING",
		4: "APPLICATION_STATE_STOPPING",
		5: "APPLICATION_STATE_STOPPED",
		6: "APPLICATION_STATE_FAILED",
	}
	ApplicationState_value = map[string]int32{
		"APPLICATION_STATE_UNSPECIFIED": 0,
		"APPLICATION_STATE_CREATED":     1,
		"APPLICATION_STATE_STARTING":    2,
		"APPLICATION_STATE_RUNNING":     3,
		"APPLICATION_STATE_STOPPING":    4,
		"APPLICATION_STATE_STOPPED":     5,
		"APPLICATION_STATE_FAILED":      6,
	}
)

func (x ApplicationState) Enum() *ApplicationState {
	p := new(ApplicationState)
	*p = x
	return p
}

func (x ApplicationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationState) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_application_application_proto_enumTypes[6].Descriptor()
}

func (ApplicationState) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_application_application_proto_enumTypes[6]
}

func (x ApplicationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationState.Descriptor instead.
func (ApplicationState) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{6}
}

// Application status (for deployment service)
type ApplicationStatus int32

const (
	// Unspecified
	ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED ApplicationStatus = 0
	// Loading (reading config)
	ApplicationStatus_APPLICATION_STATUS_LOADING ApplicationStatus = 1
	// Starting (calling start())
	ApplicationStatus_APPLICATION_STATUS_STARTING ApplicationStatus = 2
	// Running (active)
	ApplicationStatus_APPLICATION_STATUS_RUNNING ApplicationStatus = 3
	// Stopping (graceful shutdown)
	ApplicationStatus_APPLICATION_STATUS_STOPPING ApplicationStatus = 4
	// Stopped (gracefully)
	ApplicationStatus_APPLICATION_STATUS_STOPPED ApplicationStatus = 5
	// Failed (error during start/run)
	ApplicationStatus_APPLICATION_STATUS_FAILED ApplicationStatus = 6
)

// Enum value maps for ApplicationStatus.
var (
	ApplicationStatus_name = map[int32]string{
		0: "APPLICATION_STATUS_UNSPECIFIED",
		1: "APPLICATION_STATUS_LOADING",
		2: "APPLICATION_STATUS_STARTING",
		3: "APPLICATION_STATUS_RUNNING",
		4: "APPLICATION_STATUS_STOPPING",
		5: "APPLICATION_STATUS_STOPPED",
		6: "APPLICATION_STATUS_FAILED",
	}
	ApplicationStatus_value = map[string]int32{
		"APPLICATION_STATUS_UNSPECIFIED": 0,
		"APPLICATION_STATUS_LOADING":     1,
		"APPLICATION_STATUS_STARTING":    2,
		"APPLICATION_STATUS_RUNNING":     3,
		"APPLICATION_STATUS_STOPPING":    4,
		"APPLICATION_STATUS_STOPPED":     5,
		"APPLICATION_STATUS_FAILED":      6,
	}
)

func (x ApplicationStatus) Enum() *ApplicationStatus {
	p := new(ApplicationStatus)
	*p = x
	return p
}

func (x ApplicationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_application_application_proto_enumTypes[7].Descriptor()
}

func (ApplicationStatus) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_application_application_proto_enumTypes[7]
}

func (x ApplicationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationStatus.Descriptor instead.
func (ApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{7}
}

// Application specification (Erlang/OTP .app file equivalent)
//
// ## Purpose
// Complete definition of a PlexSpaces application. Analogous to
// Erlang .app files, defines metadata, dependencies, supervision tree,
// and deployment configuration (enabled, auto_start, shutdown settings).
//
// ## Why This Exists
// - Reusable components with clear boundaries
// - Dependency management (start in correct order)
// - Declarative supervision tree
// - Supports both library and active applications
// - Unified configuration (ApplicationConfig has been merged into this message)
//
// ## TOML Mapping Example
// ```toml
// [[applications]]
// name = "my-app"
// version = "1.0.0"
// description = "My application"
// type = "active"
// dependencies = ["plexspaces-core"]
// enabled = true
// auto_start = true
// shutdown_timeout_seconds = 60
// shutdown_strategy = "graceful"
// ```
type ApplicationSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application name (unique identifier within node)
	// Examples: "byzantine-generals", "genomics-coordinator"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Tenant ID for multi-tenancy isolation.
	// Extracted from JWT token during deployment.
	// All actors spawned by this application will be scoped to this tenant.
	// This is the source of truth for tenant isolation - ActorFactory enforces it.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Namespace for actor isolation within a tenant.
	// All actors spawned by this application will be registered in this namespace.
	// If empty, defaults to application_id during deployment.
	// Examples: "bank-test", "genomics-prod", "dev-sandbox"
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Application version (semantic versioning)
	// Examples: "0.1.0", "1.2.3"
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Human-readable description
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Application type (library or active)
	Type ApplicationType `protobuf:"varint,6,opt,name=type,proto3,enum=plexspaces.application.v1.ApplicationType" json:"type,omitempty"`
	// Dependencies (other applications that must start first)
	// e.g., ["plexspaces-core", "plexspaces-tuplespace"]
	Dependencies []string `protobuf:"bytes,7,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	// Application-level environment variables
	Env map[string]string `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Supervision tree (only for active applications)
	Supervisor *SupervisorSpec `protobuf:"bytes,9,opt,name=supervisor,proto3,oneof" json:"supervisor,omitempty"`
	// Whether application is enabled (false = skip loading)
	// Default: true
	Enabled bool `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Whether to start application automatically on node boot
	// Default: true
	// Future: false allows manual start via ApplicationService API
	AutoStart bool `protobuf:"varint,11,opt,name=auto_start,json=autoStart,proto3" json:"auto_start,omitempty"`
	// Shutdown timeout (force kill if exceeded)
	// Default: 60 seconds
	ShutdownTimeout *durationpb.Duration `protobuf:"bytes,12,opt,name=shutdown_timeout,json=shutdownTimeout,proto3" json:"shutdown_timeout,omitempty"`
	// Shutdown strategy (graceful or immediate)
	// Default: GRACEFUL
	ShutdownStrategy ShutdownStrategy `protobuf:"varint,13,opt,name=shutdown_strategy,json=shutdownStrategy,proto3,enum=plexspaces.application.v1.ShutdownStrategy" json:"shutdown_strategy,omitempty"`
	// Application metadata (tags, labels, annotations)
	// Examples:
	// - environment: "production"
	// - team: "genomics"
	// - criticality: "high"
	Metadata *v1.Metadata `protobuf:"bytes,14,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Seed nodes (gRPC addresses) to connect to when this application is deployed.
	// The node will connect to these addresses if not already connected, so
	// leader-worker and scatter/gather can use workers on other nodes.
	// Example: ["localhost:8091", "localhost:8093"]
	SeedNodes []string `protobuf:"bytes,15,rep,name=seed_nodes,json=seedNodes,proto3" json:"seed_nodes,omitempty"`
	// External service links this application expects at deploy time (validated against node catalog).
	RequiredServiceLinks []*ApplicationServiceLinkRequirement `protobuf:"bytes,16,rep,name=required_service_links,json=requiredServiceLinks,proto3" json:"required_service_links,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ApplicationSpec) Reset() {
	*x = ApplicationSpec{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationSpec) ProtoMessage() {}

func (x *ApplicationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationSpec.ProtoReflect.Descriptor instead.
func (*ApplicationSpec) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationSpec) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ApplicationSpec) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ApplicationSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ApplicationSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApplicationSpec) GetType() ApplicationType {
	if x != nil {
		return x.Type
	}
	return ApplicationType_APPLICATION_TYPE_UNSPECIFIED
}

func (x *ApplicationSpec) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ApplicationSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ApplicationSpec) GetSupervisor() *SupervisorSpec {
	if x != nil {
		return x.Supervisor
	}
	return nil
}

func (x *ApplicationSpec) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ApplicationSpec) GetAutoStart() bool {
	if x != nil {
		return x.AutoStart
	}
	return false
}

func (x *ApplicationSpec) GetShutdownTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownTimeout
	}
	return nil
}

func (x *ApplicationSpec) GetShutdownStrategy() ShutdownStrategy {
	if x != nil {
		return x.ShutdownStrategy
	}
	return ShutdownStrategy_SHUTDOWN_STRATEGY_UNSPECIFIED
}

func (x *ApplicationSpec) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ApplicationSpec) GetSeedNodes() []string {
	if x != nil {
		return x.SeedNodes
	}
	return nil
}

func (x *ApplicationSpec) GetRequiredServiceLinks() []*ApplicationServiceLinkRequirement {
	if x != nil {
		return x.RequiredServiceLinks
	}
	return nil
}

// Reference to a runtime service link by logical name (see RuntimeConfig.service_links).
type ApplicationServiceLinkRequirement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LinkName       string                 `protobuf:"bytes,1,opt,name=link_name,json=linkName,proto3" json:"link_name,omitempty"`
	PolicyTemplate *string                `protobuf:"bytes,2,opt,name=policy_template,json=policyTemplate,proto3,oneof" json:"policy_template,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplicationServiceLinkRequirement) Reset() {
	*x = ApplicationServiceLinkRequirement{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationServiceLinkRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationServiceLinkRequirement) ProtoMessage() {}

func (x *ApplicationServiceLinkRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationServiceLinkRequirement.ProtoReflect.Descriptor instead.
func (*ApplicationServiceLinkRequirement) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicationServiceLinkRequirement) GetLinkName() string {
	if x != nil {
		return x.LinkName
	}
	return ""
}

func (x *ApplicationServiceLinkRequirement) GetPolicyTemplate() string {
	if x != nil && x.PolicyTemplate != nil {
		return *x.PolicyTemplate
	}
	return ""
}

// Supervisor specification (Erlang/OTP supervisor)
//
// ## Purpose
// Defines a supervision tree node. Supervisors manage child processes
// (workers or other supervisors) with fault tolerance strategies.
//
// ## Why This Exists
// - Fault tolerance (automatic restarts)
// - Organized process hierarchy
// - Declarative restart strategies
// - Local supervision only (simpler than distributed)
type SupervisorSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Supervision strategy
	Strategy SupervisionStrategy `protobuf:"varint,1,opt,name=strategy,proto3,enum=plexspaces.application.v1.SupervisionStrategy" json:"strategy,omitempty"`
	// Maximum restarts allowed
	MaxRestarts uint32 `protobuf:"varint,2,opt,name=max_restarts,json=maxRestarts,proto3" json:"max_restarts,omitempty"`
	// Time window for restart counting (seconds)
	MaxRestartWindow *durationpb.Duration `protobuf:"bytes,3,opt,name=max_restart_window,json=maxRestartWindow,proto3" json:"max_restart_window,omitempty"`
	// Child processes
	Children      []*ChildSpec `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisorSpec) Reset() {
	*x = SupervisorSpec{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorSpec) ProtoMessage() {}

func (x *SupervisorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorSpec.ProtoReflect.Descriptor instead.
func (*SupervisorSpec) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{2}
}

func (x *SupervisorSpec) GetStrategy() SupervisionStrategy {
	if x != nil {
		return x.Strategy
	}
	return SupervisionStrategy_SUPERVISION_STRATEGY_UNSPECIFIED
}

func (x *SupervisorSpec) GetMaxRestarts() uint32 {
	if x != nil {
		return x.MaxRestarts
	}
	return 0
}

func (x *SupervisorSpec) GetMaxRestartWindow() *durationpb.Duration {
	if x != nil {
		return x.MaxRestartWindow
	}
	return nil
}

func (x *SupervisorSpec) GetChildren() []*ChildSpec {
	if x != nil {
		return x.Children
	}
	return nil
}

// Child process specification
//
// ## Purpose
// Defines a child process (worker or supervisor) managed by a supervisor.
//
// ## Why This Exists
// - Clear child identity and lifecycle
// - Restart policy per child
// - Shutdown timeout specification
// - Support for nested supervisors
type ChildSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique child identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Child type (worker or supervisor)
	Type ChildType `protobuf:"varint,2,opt,name=type,proto3,enum=plexspaces.application.v1.ChildType" json:"type,omitempty"`
	// Arguments to pass to start function
	Args map[string]string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Restart policy
	Restart RestartPolicy `protobuf:"varint,4,opt,name=restart,proto3,enum=plexspaces.application.v1.RestartPolicy" json:"restart,omitempty"`
	// Shutdown timeout
	ShutdownTimeout *durationpb.Duration `protobuf:"bytes,5,opt,name=shutdown_timeout,json=shutdownTimeout,proto3" json:"shutdown_timeout,omitempty"`
	// Nested supervisor (if type=SUPERVISOR)
	Supervisor *SupervisorSpec `protobuf:"bytes,6,opt,name=supervisor,proto3,oneof" json:"supervisor,omitempty"`
	// Facet configuration (for automatic attachment during actor creation)
	// Facets are attached in priority order (high priority first) before actor.init() is called
	// All facets are automatically restored during supervisor restart
	// Phase 1: Unified Lifecycle - Multiple facets support
	Facets []*v1.Facet `protobuf:"bytes,7,rep,name=facets,proto3" json:"facets,omitempty"`
	// OTP-style behavior kind for logging and observability (e.g. "GenServer", "GenEvent", "GenStateMachine", "Workflow").
	// When set, process_message spans and actor registration logs show this instead of the child id.
	BehaviorKind  *string `protobuf:"bytes,8,opt,name=behavior_kind,json=behaviorKind,proto3,oneof" json:"behavior_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildSpec) Reset() {
	*x = ChildSpec{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildSpec) ProtoMessage() {}

func (x *ChildSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildSpec.ProtoReflect.Descriptor instead.
func (*ChildSpec) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{3}
}

func (x *ChildSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChildSpec) GetType() ChildType {
	if x != nil {
		return x.Type
	}
	return ChildType_CHILD_TYPE_UNSPECIFIED
}

func (x *ChildSpec) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ChildSpec) GetRestart() RestartPolicy {
	if x != nil {
		return x.Restart
	}
	return RestartPolicy_RESTART_POLICY_UNSPECIFIED
}

func (x *ChildSpec) GetShutdownTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownTimeout
	}
	return nil
}

func (x *ChildSpec) GetSupervisor() *SupervisorSpec {
	if x != nil {
		return x.Supervisor
	}
	return nil
}

func (x *ChildSpec) GetFacets() []*v1.Facet {
	if x != nil {
		return x.Facets
	}
	return nil
}

func (x *ChildSpec) GetBehaviorKind() string {
	if x != nil && x.BehaviorKind != nil {
		return *x.BehaviorKind
	}
	return ""
}

// Application instance (runtime representation).
//
// ## Purpose
// Runtime state of a running application instance.
//
// ## Design Notes
// - config: Static configuration from TOML
// - state: Current lifecycle state
// - health: Current health status
// - started_at: When application started
// - statistics: Runtime metrics (messages processed, actors spawned, etc.)
type Application struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application specification (merged from ApplicationConfig)
	Spec *ApplicationSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// Current lifecycle state
	State ApplicationState `protobuf:"varint,2,opt,name=state,proto3,enum=plexspaces.application.v1.ApplicationState" json:"state,omitempty"`
	// Current health status
	Health HealthStatus `protobuf:"varint,3,opt,name=health,proto3,enum=plexspaces.application.v1.HealthStatus" json:"health,omitempty"`
	// When application started
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Application statistics (runtime metrics)
	Statistics    *ApplicationStatistics `protobuf:"bytes,5,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{4}
}

func (x *Application) GetSpec() *ApplicationSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Application) GetState() ApplicationState {
	if x != nil {
		return x.State
	}
	return ApplicationState_APPLICATION_STATE_UNSPECIFIED
}

func (x *Application) GetHealth() HealthStatus {
	if x != nil {
		return x.Health
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *Application) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Application) GetStatistics() *ApplicationStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

// Application runtime statistics.
//
// ## Purpose
// Track runtime metrics for monitoring and debugging.
//
// ## Design Notes
// - Counters are cumulative since application start
// - Gauges represent current state
type ApplicationStatistics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of actors spawned by this application
	ActorsSpawned uint64 `protobuf:"varint,1,opt,name=actors_spawned,json=actorsSpawned,proto3" json:"actors_spawned,omitempty"`
	// Number of actors currently active
	ActorsActive uint64 `protobuf:"varint,2,opt,name=actors_active,json=actorsActive,proto3" json:"actors_active,omitempty"`
	// Number of messages processed
	MessagesProcessed uint64 `protobuf:"varint,3,opt,name=messages_processed,json=messagesProcessed,proto3" json:"messages_processed,omitempty"`
	// Number of errors encountered
	ErrorsTotal uint64 `protobuf:"varint,4,opt,name=errors_total,json=errorsTotal,proto3" json:"errors_total,omitempty"`
	// Number of restarts (if supervised)
	Restarts      uint32 `protobuf:"varint,5,opt,name=restarts,proto3" json:"restarts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationStatistics) Reset() {
	*x = ApplicationStatistics{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationStatistics) ProtoMessage() {}

func (x *ApplicationStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationStatistics.ProtoReflect.Descriptor instead.
func (*ApplicationStatistics) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{5}
}

func (x *ApplicationStatistics) GetActorsSpawned() uint64 {
	if x != nil {
		return x.ActorsSpawned
	}
	return 0
}

func (x *ApplicationStatistics) GetActorsActive() uint64 {
	if x != nil {
		return x.ActorsActive
	}
	return 0
}

func (x *ApplicationStatistics) GetMessagesProcessed() uint64 {
	if x != nil {
		return x.MessagesProcessed
	}
	return 0
}

func (x *ApplicationStatistics) GetErrorsTotal() uint64 {
	if x != nil {
		return x.ErrorsTotal
	}
	return 0
}

func (x *ApplicationStatistics) GetRestarts() uint32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

// Application state (runtime) - for deployment service
//
// ## Purpose
// Represents runtime state of a running application.
type ApplicationRuntimeState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Current state
	Status ApplicationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=plexspaces.application.v1.ApplicationStatus" json:"status,omitempty"`
	// Start timestamp
	StartTimestampMs int64 `protobuf:"varint,3,opt,name=start_timestamp_ms,json=startTimestampMs,proto3" json:"start_timestamp_ms,omitempty"`
	// Root supervisor PID (if active application)
	SupervisorPid *string `protobuf:"bytes,4,opt,name=supervisor_pid,json=supervisorPid,proto3,oneof" json:"supervisor_pid,omitempty"`
	// Environment variables
	Env           map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationRuntimeState) Reset() {
	*x = ApplicationRuntimeState{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationRuntimeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationRuntimeState) ProtoMessage() {}

func (x *ApplicationRuntimeState) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationRuntimeState.ProtoReflect.Descriptor instead.
func (*ApplicationRuntimeState) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{6}
}

func (x *ApplicationRuntimeState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationRuntimeState) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

func (x *ApplicationRuntimeState) GetStartTimestampMs() int64 {
	if x != nil {
		return x.StartTimestampMs
	}
	return 0
}

func (x *ApplicationRuntimeState) GetSupervisorPid() string {
	if x != nil && x.SupervisorPid != nil {
		return *x.SupervisorPid
	}
	return ""
}

func (x *ApplicationRuntimeState) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// Deploy application request
type DeployApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application identifier (unique per node)
	ApplicationId string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// Application name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Application version
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// WASM module (if WASM application)
	// If provided, application code is loaded from WASM.
	// If not provided, application must be pre-registered (native Rust).
	WasmModule *wasm.WasmModule `protobuf:"bytes,4,opt,name=wasm_module,json=wasmModule,proto3,oneof" json:"wasm_module,omitempty"`
	// Application configuration
	// Defines supervision tree, dependencies, environment variables, etc.
	Config *ApplicationSpec `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	// Initial state (optional, for stateful applications)
	// Passed to application's start() method.
	InitialState  []byte `protobuf:"bytes,7,opt,name=initial_state,json=initialState,proto3" json:"initial_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployApplicationRequest) Reset() {
	*x = DeployApplicationRequest{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployApplicationRequest) ProtoMessage() {}

func (x *DeployApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeployApplicationRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{7}
}

func (x *DeployApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *DeployApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployApplicationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeployApplicationRequest) GetWasmModule() *wasm.WasmModule {
	if x != nil {
		return x.WasmModule
	}
	return nil
}

func (x *DeployApplicationRequest) GetConfig() *ApplicationSpec {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DeployApplicationRequest) GetInitialState() []byte {
	if x != nil {
		return x.InitialState
	}
	return nil
}

// Deploy application response
type DeployApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success flag
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Application ID (may differ from request if auto-generated)
	ApplicationId string `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// Application status after deployment
	Status ApplicationStatus `protobuf:"varint,3,opt,name=status,proto3,enum=plexspaces.application.v1.ApplicationStatus" json:"status,omitempty"`
	// Error details (if success=false)
	Error         *string `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployApplicationResponse) Reset() {
	*x = DeployApplicationResponse{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployApplicationResponse) ProtoMessage() {}

func (x *DeployApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployApplicationResponse.ProtoReflect.Descriptor instead.
func (*DeployApplicationResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{8}
}

func (x *DeployApplicationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployApplicationResponse) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *DeployApplicationResponse) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

func (x *DeployApplicationResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Undeploy application request
type UndeployApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID to undeploy
	ApplicationId string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// Graceful shutdown timeout (optional, uses app config default if not provided)
	Timeout       *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeployApplicationRequest) Reset() {
	*x = UndeployApplicationRequest{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeployApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeployApplicationRequest) ProtoMessage() {}

func (x *UndeployApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeployApplicationRequest.ProtoReflect.Descriptor instead.
func (*UndeployApplicationRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{9}
}

func (x *UndeployApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *UndeployApplicationRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// Undeploy application response
type UndeployApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success flag
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error details (if success=false)
	Error         *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeployApplicationResponse) Reset() {
	*x = UndeployApplicationResponse{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeployApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeployApplicationResponse) ProtoMessage() {}

func (x *UndeployApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeployApplicationResponse.ProtoReflect.Descriptor instead.
func (*UndeployApplicationResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{10}
}

func (x *UndeployApplicationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UndeployApplicationResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// List applications request
type ListApplicationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by status (optional, empty = all applications)
	StatusFilter  *ApplicationStatus `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=plexspaces.application.v1.ApplicationStatus,oneof" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{11}
}

func (x *ListApplicationsRequest) GetStatusFilter() ApplicationStatus {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

// List applications response
type ListApplicationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of deployed applications
	Applications  []*ApplicationInfo `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{12}
}

func (x *ListApplicationsResponse) GetApplications() []*ApplicationInfo {
	if x != nil {
		return x.Applications
	}
	return nil
}

// Application information
type ApplicationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID
	ApplicationId string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// Application name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Application version
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Current status
	Status ApplicationStatus `protobuf:"varint,4,opt,name=status,proto3,enum=plexspaces.application.v1.ApplicationStatus" json:"status,omitempty"`
	// When the application was deployed
	DeployedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	// Application metrics (optional)
	Metrics       *ApplicationMetrics `protobuf:"bytes,6,opt,name=metrics,proto3,oneof" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationInfo) Reset() {
	*x = ApplicationInfo{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationInfo) ProtoMessage() {}

func (x *ApplicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationInfo.ProtoReflect.Descriptor instead.
func (*ApplicationInfo) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{13}
}

func (x *ApplicationInfo) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApplicationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ApplicationInfo) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

func (x *ApplicationInfo) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

func (x *ApplicationInfo) GetMetrics() *ApplicationMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Application metrics
type ApplicationMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Actor counts by role/type within the application on this node.
	// Examples:
	// - leader: 1
	// - worker: 8
	// - supervisor: 1
	ActorCounts map[string]uint64 `protobuf:"bytes,1,rep,name=actor_counts,json=actorCounts,proto3" json:"actor_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Number of supervisors
	SupervisorCount uint32 `protobuf:"varint,2,opt,name=supervisor_count,json=supervisorCount,proto3" json:"supervisor_count,omitempty"`
	// Uptime in seconds
	UptimeSeconds uint64 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Total messages processed by this application on this node.
	MessageCount uint64 `protobuf:"varint,4,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	// Total errors observed by this application on this node.
	ErrorCount uint64 `protobuf:"varint,5,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	// General-purpose counters for application-defined metrics.
	// Examples:
	// - tuple_operations: 690
	// - scatter_gather_rounds: 30
	// - ts_write_count: 64
	// - ts_read_count: 64
	CounterMetrics map[string]uint64 `protobuf:"bytes,6,rep,name=counter_metrics,json=counterMetrics,proto3" json:"counter_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Cumulative latency totals in milliseconds by metric type.
	// Examples:
	// - compute: 511
	// - coordination: 65419
	// - worker: 65930
	LatencyTotalsMs map[string]uint64 `protobuf:"bytes,7,rep,name=latency_totals_ms,json=latencyTotalsMs,proto3" json:"latency_totals_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Maximum observed latency in milliseconds by metric type.
	LatencyMaxMs map[string]uint64 `protobuf:"bytes,8,rep,name=latency_max_ms,json=latencyMaxMs,proto3" json:"latency_max_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Number of latency samples contributing to latency_totals_ms for each type.
	LatencySamples map[string]uint64 `protobuf:"bytes,9,rep,name=latency_samples,json=latencySamples,proto3" json:"latency_samples,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplicationMetrics) Reset() {
	*x = ApplicationMetrics{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationMetrics) ProtoMessage() {}

func (x *ApplicationMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationMetrics.ProtoReflect.Descriptor instead.
func (*ApplicationMetrics) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{14}
}

func (x *ApplicationMetrics) GetActorCounts() map[string]uint64 {
	if x != nil {
		return x.ActorCounts
	}
	return nil
}

func (x *ApplicationMetrics) GetSupervisorCount() uint32 {
	if x != nil {
		return x.SupervisorCount
	}
	return 0
}

func (x *ApplicationMetrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ApplicationMetrics) GetMessageCount() uint64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *ApplicationMetrics) GetErrorCount() uint64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *ApplicationMetrics) GetCounterMetrics() map[string]uint64 {
	if x != nil {
		return x.CounterMetrics
	}
	return nil
}

func (x *ApplicationMetrics) GetLatencyTotalsMs() map[string]uint64 {
	if x != nil {
		return x.LatencyTotalsMs
	}
	return nil
}

func (x *ApplicationMetrics) GetLatencyMaxMs() map[string]uint64 {
	if x != nil {
		return x.LatencyMaxMs
	}
	return nil
}

func (x *ApplicationMetrics) GetLatencySamples() map[string]uint64 {
	if x != nil {
		return x.LatencySamples
	}
	return nil
}

// Get application status request
type GetApplicationStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID
	ApplicationId string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationStatusRequest) Reset() {
	*x = GetApplicationStatusRequest{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationStatusRequest) ProtoMessage() {}

func (x *GetApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{15}
}

func (x *GetApplicationStatusRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

// Get application status response
type GetApplicationStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application information
	Application *ApplicationInfo `protobuf:"bytes,1,opt,name=application,proto3,oneof" json:"application,omitempty"`
	// Detailed application state
	State *ApplicationRuntimeState `protobuf:"bytes,2,opt,name=state,proto3,oneof" json:"state,omitempty"`
	// Error if application not found
	Error *string `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// Node ID that served this status response.
	NodeId string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Node address that served this status response.
	NodeAddress   string `protobuf:"bytes,5,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationStatusResponse) Reset() {
	*x = GetApplicationStatusResponse{}
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationStatusResponse) ProtoMessage() {}

func (x *GetApplicationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_application_application_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationStatusResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_application_application_proto_rawDescGZIP(), []int{16}
}

func (x *GetApplicationStatusResponse) GetApplication() *ApplicationInfo {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *GetApplicationStatusResponse) GetState() *ApplicationRuntimeState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GetApplicationStatusResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetApplicationStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetApplicationStatusResponse) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

var File_plexspaces_v1_application_application_proto protoreflect.FileDescriptor

const file_plexspaces_v1_application_application_proto_rawDesc = "" +
	"\n" +
	"+plexspaces/v1/application/application.proto\x12\x19plexspaces.application.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aplexspaces/v1/common.proto\x1a\x1dplexspaces/v1/wasm/wasm.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xf4\a\n" +
	"\x0fApplicationSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12>\n" +
	"\x04type\x18\x06 \x01(\x0e2*.plexspaces.application.v1.ApplicationTypeR\x04type\x12\"\n" +
	"\fdependencies\x18\a \x03(\tR\fdependencies\x12E\n" +
	"\x03env\x18\b \x03(\v23.plexspaces.application.v1.ApplicationSpec.EnvEntryR\x03env\x12N\n" +
	"\n" +
	"supervisor\x18\t \x01(\v2).plexspaces.application.v1.SupervisorSpecH\x00R\n" +
	"supervisor\x88\x01\x01\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"auto_start\x18\v \x01(\bR\tautoStart\x12D\n" +
	"\x10shutdown_timeout\x18\f \x01(\v2\x19.google.protobuf.DurationR\x0fshutdownTimeout\x12X\n" +
	"\x11shutdown_strategy\x18\r \x01(\x0e2+.plexspaces.application.v1.ShutdownStrategyR\x10shutdownStrategy\x12:\n" +
	"\bmetadata\x18\x0e \x01(\v2\x1e.plexspaces.common.v1.MetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"seed_nodes\x18\x0f \x03(\tR\tseedNodes\x12\xdf\x01\n" +
	"\x16required_service_links\x18\x10 \x03(\v2<.plexspaces.application.v1.ApplicationServiceLinkRequirementBk\x92A\\2ZLinks that must exist in RuntimeConfig.service_links (or equivalent) when the app deploys.\xe0A\x01\xbaH\x06\x92\x01\x03\x10\x80\x01R\x14requiredServiceLinks\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_supervisor\"\xdc\x03\n" +
	"!ApplicationServiceLinkRequirement\x12\x8b\x01\n" +
	"\tlink_name\x18\x01 \x01(\tBn\x92A@2.Must match ServiceLinkConfig.name on the node.J\x0e\"payments-api\"\xe0A\x02\xbaH%r#\x10\x01\x18\x80\x022\x1c^[a-zA-Z0-9][a-zA-Z0-9._-]*$R\blinkName\x12\x88\x01\n" +
	"\x0fpolicy_template\x18\x02 \x01(\tBZ\x92AL2JOptional RuntimeConfig.outbound_policy_templates key merged for this link.\xe0A\x01\xbaH\x05r\x03\x18\x80\x01H\x00R\x0epolicyTemplate\x88\x01\x01:\x89\x01\x92A\x85\x01\n" +
	"\x82\x01*!ApplicationServiceLinkRequirement2]Application-level requirement for a named outbound service link and optional policy template.B\x12\n" +
	"\x10_policy_template\"\x8a\x02\n" +
	"\x0eSupervisorSpec\x12J\n" +
	"\bstrategy\x18\x01 \x01(\x0e2..plexspaces.application.v1.SupervisionStrategyR\bstrategy\x12!\n" +
	"\fmax_restarts\x18\x02 \x01(\rR\vmaxRestarts\x12G\n" +
	"\x12max_restart_window\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x10maxRestartWindow\x12@\n" +
	"\bchildren\x18\x04 \x03(\v2$.plexspaces.application.v1.ChildSpecR\bchildren\"\xac\x04\n" +
	"\tChildSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.plexspaces.application.v1.ChildTypeR\x04type\x12B\n" +
	"\x04args\x18\x03 \x03(\v2..plexspaces.application.v1.ChildSpec.ArgsEntryR\x04args\x12B\n" +
	"\arestart\x18\x04 \x01(\x0e2(.plexspaces.application.v1.RestartPolicyR\arestart\x12D\n" +
	"\x10shutdown_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x0fshutdownTimeout\x12N\n" +
	"\n" +
	"supervisor\x18\x06 \x01(\v2).plexspaces.application.v1.SupervisorSpecH\x00R\n" +
	"supervisor\x88\x01\x01\x123\n" +
	"\x06facets\x18\a \x03(\v2\x1b.plexspaces.common.v1.FacetR\x06facets\x12(\n" +
	"\rbehavior_kind\x18\b \x01(\tH\x01R\fbehaviorKind\x88\x01\x01\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_supervisorB\x10\n" +
	"\x0e_behavior_kind\"\xde\x02\n" +
	"\vApplication\x12>\n" +
	"\x04spec\x18\x01 \x01(\v2*.plexspaces.application.v1.ApplicationSpecR\x04spec\x12A\n" +
	"\x05state\x18\x02 \x01(\x0e2+.plexspaces.application.v1.ApplicationStateR\x05state\x12?\n" +
	"\x06health\x18\x03 \x01(\x0e2'.plexspaces.application.v1.HealthStatusR\x06health\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12P\n" +
	"\n" +
	"statistics\x18\x05 \x01(\v20.plexspaces.application.v1.ApplicationStatisticsR\n" +
	"statistics\"\xd1\x01\n" +
	"\x15ApplicationStatistics\x12%\n" +
	"\x0eactors_spawned\x18\x01 \x01(\x04R\ractorsSpawned\x12#\n" +
	"\ractors_active\x18\x02 \x01(\x04R\factorsActive\x12-\n" +
	"\x12messages_processed\x18\x03 \x01(\x04R\x11messagesProcessed\x12!\n" +
	"\ferrors_total\x18\x04 \x01(\x04R\verrorsTotal\x12\x1a\n" +
	"\brestarts\x18\x05 \x01(\rR\brestarts\"\xe7\x02\n" +
	"\x17ApplicationRuntimeState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12D\n" +
	"\x06status\x18\x02 \x01(\x0e2,.plexspaces.application.v1.ApplicationStatusR\x06status\x12,\n" +
	"\x12start_timestamp_ms\x18\x03 \x01(\x03R\x10startTimestampMs\x12*\n" +
	"\x0esupervisor_pid\x18\x04 \x01(\tH\x00R\rsupervisorPid\x88\x01\x01\x12M\n" +
	"\x03env\x18\x05 \x03(\v2;.plexspaces.application.v1.ApplicationRuntimeState.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_supervisor_pid\"\xae\x02\n" +
	"\x18DeployApplicationRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12D\n" +
	"\vwasm_module\x18\x04 \x01(\v2\x1e.plexspaces.wasm.v1.WasmModuleH\x00R\n" +
	"wasmModule\x88\x01\x01\x12B\n" +
	"\x06config\x18\x05 \x01(\v2*.plexspaces.application.v1.ApplicationSpecR\x06config\x12#\n" +
	"\rinitial_state\x18\a \x01(\fR\finitialStateB\x0e\n" +
	"\f_wasm_module\"\xc7\x01\n" +
	"\x19DeployApplicationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12D\n" +
	"\x06status\x18\x03 \x01(\x0e2,.plexspaces.application.v1.ApplicationStatusR\x06status\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x89\x01\n" +
	"\x1aUndeployApplicationRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x128\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x00R\atimeout\x88\x01\x01B\n" +
	"\n" +
	"\b_timeout\"\\\n" +
	"\x1bUndeployApplicationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x83\x01\n" +
	"\x17ListApplicationsRequest\x12V\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2,.plexspaces.application.v1.ApplicationStatusH\x00R\fstatusFilter\x88\x01\x01B\x10\n" +
	"\x0e_status_filter\"j\n" +
	"\x18ListApplicationsResponse\x12N\n" +
	"\fapplications\x18\x01 \x03(\v2*.plexspaces.application.v1.ApplicationInfoR\fapplications\"\xc3\x02\n" +
	"\x0fApplicationInfo\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12D\n" +
	"\x06status\x18\x04 \x01(\x0e2,.plexspaces.application.v1.ApplicationStatusR\x06status\x12;\n" +
	"\vdeployed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\x12L\n" +
	"\ametrics\x18\x06 \x01(\v2-.plexspaces.application.v1.ApplicationMetricsH\x00R\ametrics\x88\x01\x01B\n" +
	"\n" +
	"\b_metrics\"\x89\b\n" +
	"\x12ApplicationMetrics\x12a\n" +
	"\factor_counts\x18\x01 \x03(\v2>.plexspaces.application.v1.ApplicationMetrics.ActorCountsEntryR\vactorCounts\x12)\n" +
	"\x10supervisor_count\x18\x02 \x01(\rR\x0fsupervisorCount\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x04R\ruptimeSeconds\x12#\n" +
	"\rmessage_count\x18\x04 \x01(\x04R\fmessageCount\x12\x1f\n" +
	"\verror_count\x18\x05 \x01(\x04R\n" +
	"errorCount\x12j\n" +
	"\x0fcounter_metrics\x18\x06 \x03(\v2A.plexspaces.application.v1.ApplicationMetrics.CounterMetricsEntryR\x0ecounterMetrics\x12n\n" +
	"\x11latency_totals_ms\x18\a \x03(\v2B.plexspaces.application.v1.ApplicationMetrics.LatencyTotalsMsEntryR\x0flatencyTotalsMs\x12e\n" +
	"\x0elatency_max_ms\x18\b \x03(\v2?.plexspaces.application.v1.ApplicationMetrics.LatencyMaxMsEntryR\flatencyMaxMs\x12j\n" +
	"\x0flatency_samples\x18\t \x03(\v2A.plexspaces.application.v1.ApplicationMetrics.LatencySamplesEntryR\x0elatencySamples\x1a>\n" +
	"\x10ActorCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aA\n" +
	"\x13CounterMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aB\n" +
	"\x14LatencyTotalsMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a?\n" +
	"\x11LatencyMaxMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aA\n" +
	"\x13LatencySamplesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"D\n" +
	"\x1bGetApplicationStatusRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"\xbb\x02\n" +
	"\x1cGetApplicationStatusResponse\x12Q\n" +
	"\vapplication\x18\x01 \x01(\v2*.plexspaces.application.v1.ApplicationInfoH\x00R\vapplication\x88\x01\x01\x12M\n" +
	"\x05state\x18\x02 \x01(\v22.plexspaces.application.v1.ApplicationRuntimeStateH\x01R\x05state\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x02R\x05error\x88\x01\x01\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12!\n" +
	"\fnode_address\x18\x05 \x01(\tR\vnodeAddressB\x0e\n" +
	"\f_applicationB\b\n" +
	"\x06_stateB\b\n" +
	"\x06_error*n\n" +
	"\x0fApplicationType\x12 \n" +
	"\x1cAPPLICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18APPLICATION_TYPE_LIBRARY\x10\x01\x12\x1b\n" +
	"\x17APPLICATION_TYPE_ACTIVE\x10\x02*\xae\x01\n" +
	"\x13SupervisionStrategy\x12$\n" +
	" SUPERVISION_STRATEGY_UNSPECIFIED\x10\x00\x12$\n" +
	" SUPERVISION_STRATEGY_ONE_FOR_ONE\x10\x01\x12$\n" +
	" SUPERVISION_STRATEGY_ONE_FOR_ALL\x10\x02\x12%\n" +
	"!SUPERVISION_STRATEGY_REST_FOR_ONE\x10\x03*Y\n" +
	"\tChildType\x12\x1a\n" +
	"\x16CHILD_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CHILD_TYPE_WORKER\x10\x01\x12\x19\n" +
	"\x15CHILD_TYPE_SUPERVISOR\x10\x02*\x89\x01\n" +
	"\rRestartPolicy\x12\x1e\n" +
	"\x1aRESTART_POLICY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RESTART_POLICY_PERMANENT\x10\x01\x12\x1c\n" +
	"\x18RESTART_POLICY_TRANSIENT\x10\x02\x12\x1c\n" +
	"\x18RESTART_POLICY_TEMPORARY\x10\x03*v\n" +
	"\x10ShutdownStrategy\x12!\n" +
	"\x1dSHUTDOWN_STRATEGY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSHUTDOWN_STRATEGY_GRACEFUL\x10\x01\x12\x1f\n" +
	"\x1bSHUTDOWN_STRATEGY_IMMEDIATE\x10\x02*\x81\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x03*\xf0\x01\n" +
	"\x10ApplicationState\x12!\n" +
	"\x1dAPPLICATION_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19APPLICATION_STATE_CREATED\x10\x01\x12\x1e\n" +
	"\x1aAPPLICATION_STATE_STARTING\x10\x02\x12\x1d\n" +
	"\x19APPLICATION_STATE_RUNNING\x10\x03\x12\x1e\n" +
	"\x1aAPPLICATION_STATE_STOPPING\x10\x04\x12\x1d\n" +
	"\x19APPLICATION_STATE_STOPPED\x10\x05\x12\x1c\n" +
	"\x18APPLICATION_STATE_FAILED\x10\x06*\xf8\x01\n" +
	"\x11ApplicationStatus\x12\"\n" +
	"\x1eAPPLICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aAPPLICATION_STATUS_LOADING\x10\x01\x12\x1f\n" +
	"\x1bAPPLICATION_STATUS_STARTING\x10\x02\x12\x1e\n" +
	"\x1aAPPLICATION_STATUS_RUNNING\x10\x03\x12\x1f\n" +
	"\x1bAPPLICATION_STATUS_STOPPING\x10\x04\x12\x1e\n" +
	"\x1aAPPLICATION_STATUS_STOPPED\x10\x05\x12\x1d\n" +
	"\x19APPLICATION_STATUS_FAILED\x10\x062\xc8\x05\n" +
	"\x12ApplicationService\x12\x9f\x01\n" +
	"\x11DeployApplication\x123.plexspaces.application.v1.DeployApplicationRequest\x1a4.plexspaces.application.v1.DeployApplicationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/applications\x12\xb3\x01\n" +
	"\x13UndeployApplication\x125.plexspaces.application.v1.UndeployApplicationRequest\x1a6.plexspaces.application.v1.UndeployApplicationResponse\"-\x82\xd3\xe4\x93\x02'*%/api/v1/applications/{application_id}\x12\x99\x01\n" +
	"\x10ListApplications\x122.plexspaces.application.v1.ListApplicationsRequest\x1a3.plexspaces.application.v1.ListApplicationsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/applications\x12\xbd\x01\n" +
	"\x14GetApplicationStatus\x126.plexspaces.application.v1.GetApplicationStatusRequest\x1a7.plexspaces.application.v1.GetApplicationStatusResponse\"4\x82\xd3\xe4\x93\x02.\x12,/api/v1/applications/{application_id}/statusB\x9a\x02\n" +
	"\x1dcom.plexspaces.application.v1B\x10ApplicationProtoP\x01Zagithub.com/plexobject/plexspaces/sdks/go/plexspaces/proto/plexspaces/v1/application;applicationv1\xa2\x02\x03PAX\xaa\x02\x19Plexspaces.Application.V1\xca\x02\x19Plexspaces\\Application\\V1\xe2\x02%Plexspaces\\Application\\V1\\GPBMetadata\xea\x02\x1bPlexspaces::Application::V1b\x06proto3"

var (
	file_plexspaces_v1_application_application_proto_rawDescOnce sync.Once
	file_plexspaces_v1_application_application_proto_rawDescData []byte
)

func file_plexspaces_v1_application_application_proto_rawDescGZIP() []byte {
	file_plexspaces_v1_application_application_proto_rawDescOnce.Do(func() {
		file_plexspaces_v1_application_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plexspaces_v1_application_application_proto_rawDesc), len(file_plexspaces_v1_application_application_proto_rawDesc)))
	})
	return file_plexspaces_v1_application_application_proto_rawDescData
}

var file_plexspaces_v1_application_application_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_plexspaces_v1_application_application_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_plexspaces_v1_application_application_proto_goTypes = []any{
	(ApplicationType)(0),                      // 0: plexspaces.application.v1.ApplicationType
	(SupervisionStrategy)(0),                  // 1: plexspaces.application.v1.SupervisionStrategy
	(ChildType)(0),                            // 2: plexspaces.application.v1.ChildType
	(RestartPolicy)(0),                        // 3: plexspaces.application.v1.RestartPolicy
	(ShutdownStrategy)(0),                     // 4: plexspaces.application.v1.ShutdownStrategy
	(HealthStatus)(0),                         // 5: plexspaces.application.v1.HealthStatus
	(ApplicationState)(0),                     // 6: plexspaces.application.v1.ApplicationState
	(ApplicationStatus)(0),                    // 7: plexspaces.application.v1.ApplicationStatus
	(*ApplicationSpec)(nil),                   // 8: plexspaces.application.v1.ApplicationSpec
	(*ApplicationServiceLinkRequirement)(nil), // 9: plexspaces.application.v1.ApplicationServiceLinkRequirement
	(*SupervisorSpec)(nil),                    // 10: plexspaces.application.v1.SupervisorSpec
	(*ChildSpec)(nil),                         // 11: plexspaces.application.v1.ChildSpec
	(*Application)(nil),                       // 12: plexspaces.application.v1.Application
	(*ApplicationStatistics)(nil),             // 13: plexspaces.application.v1.ApplicationStatistics
	(*ApplicationRuntimeState)(nil),           // 14: plexspaces.application.v1.ApplicationRuntimeState
	(*DeployApplicationRequest)(nil),          // 15: plexspaces.application.v1.DeployApplicationRequest
	(*DeployApplicationResponse)(nil),         // 16: plexspaces.application.v1.DeployApplicationResponse
	(*UndeployApplicationRequest)(nil),        // 17: plexspaces.application.v1.UndeployApplicationRequest
	(*UndeployApplicationResponse)(nil),       // 18: plexspaces.application.v1.UndeployApplicationResponse
	(*ListApplicationsRequest)(nil),           // 19: plexspaces.application.v1.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),          // 20: plexspaces.application.v1.ListApplicationsResponse
	(*ApplicationInfo)(nil),                   // 21: plexspaces.application.v1.ApplicationInfo
	(*ApplicationMetrics)(nil),                // 22: plexspaces.application.v1.ApplicationMetrics
	(*GetApplicationStatusRequest)(nil),       // 23: plexspaces.application.v1.GetApplicationStatusRequest
	(*GetApplicationStatusResponse)(nil),      // 24: plexspaces.application.v1.GetApplicationStatusResponse
	nil,                                       // 25: plexspaces.application.v1.ApplicationSpec.EnvEntry
	nil,                                       // 26: plexspaces.application.v1.ChildSpec.ArgsEntry
	nil,                                       // 27: plexspaces.application.v1.ApplicationRuntimeState.EnvEntry
	nil,                                       // 28: plexspaces.application.v1.ApplicationMetrics.ActorCountsEntry
	nil,                                       // 29: plexspaces.application.v1.ApplicationMetrics.CounterMetricsEntry
	nil,                                       // 30: plexspaces.application.v1.ApplicationMetrics.LatencyTotalsMsEntry
	nil,                                       // 31: plexspaces.application.v1.ApplicationMetrics.LatencyMaxMsEntry
	nil,                                       // 32: plexspaces.application.v1.ApplicationMetrics.LatencySamplesEntry
	(*durationpb.Duration)(nil),               // 33: google.protobuf.Duration
	(*v1.Metadata)(nil),                       // 34: plexspaces.common.v1.Metadata
	(*v1.Facet)(nil),                          // 35: plexspaces.common.v1.Facet
	(*timestamppb.Timestamp)(nil),             // 36: google.protobuf.Timestamp
	(*wasm.WasmModule)(nil),                   // 37: plexspaces.wasm.v1.WasmModule
}
var file_plexspaces_v1_application_application_proto_depIdxs = []int32{
	0,  // 0: plexspaces.application.v1.ApplicationSpec.type:type_name -> plexspaces.application.v1.ApplicationType
	25, // 1: plexspaces.application.v1.ApplicationSpec.env:type_name -> plexspaces.application.v1.ApplicationSpec.EnvEntry
	10, // 2: plexspaces.application.v1.ApplicationSpec.supervisor:type_name -> plexspaces.application.v1.SupervisorSpec
	33, // 3: plexspaces.application.v1.ApplicationSpec.shutdown_timeout:type_name -> google.protobuf.Duration
	4,  // 4: plexspaces.application.v1.ApplicationSpec.shutdown_strategy:type_name -> plexspaces.application.v1.ShutdownStrategy
	34, // 5: plexspaces.application.v1.ApplicationSpec.metadata:type_name -> plexspaces.common.v1.Metadata
	9,  // 6: plexspaces.application.v1.ApplicationSpec.required_service_links:type_name -> plexspaces.application.v1.ApplicationServiceLinkRequirement
	1,  // 7: plexspaces.application.v1.SupervisorSpec.strategy:type_name -> plexspaces.application.v1.SupervisionStrategy
	33, // 8: plexspaces.application.v1.SupervisorSpec.max_restart_window:type_name -> google.protobuf.Duration
	11, // 9: plexspaces.application.v1.SupervisorSpec.children:type_name -> plexspaces.application.v1.ChildSpec
	2,  // 10: plexspaces.application.v1.ChildSpec.type:type_name -> plexspaces.application.v1.ChildType
	26, // 11: plexspaces.application.v1.ChildSpec.args:type_name -> plexspaces.application.v1.ChildSpec.ArgsEntry
	3,  // 12: plexspaces.application.v1.ChildSpec.restart:type_name -> plexspaces.application.v1.RestartPolicy
	33, // 13: plexspaces.application.v1.ChildSpec.shutdown_timeout:type_name -> google.protobuf.Duration
	10, // 14: plexspaces.application.v1.ChildSpec.supervisor:type_name -> plexspaces.application.v1.SupervisorSpec
	35, // 15: plexspaces.application.v1.ChildSpec.facets:type_name -> plexspaces.common.v1.Facet
	8,  // 16: plexspaces.application.v1.Application.spec:type_name -> plexspaces.application.v1.ApplicationSpec
	6,  // 17: plexspaces.application.v1.Application.state:type_name -> plexspaces.application.v1.ApplicationState
	5,  // 18: plexspaces.application.v1.Application.health:type_name -> plexspaces.application.v1.HealthStatus
	36, // 19: plexspaces.application.v1.Application.started_at:type_name -> google.protobuf.Timestamp
	13, // 20: plexspaces.application.v1.Application.statistics:type_name -> plexspaces.application.v1.ApplicationStatistics
	7,  // 21: plexspaces.application.v1.ApplicationRuntimeState.status:type_name -> plexspaces.application.v1.ApplicationStatus
	27, // 22: plexspaces.application.v1.ApplicationRuntimeState.env:type_name -> plexspaces.application.v1.ApplicationRuntimeState.EnvEntry
	37, // 23: plexspaces.application.v1.DeployApplicationRequest.wasm_module:type_name -> plexspaces.wasm.v1.WasmModule
	8,  // 24: plexspaces.application.v1.DeployApplicationRequest.config:type_name -> plexspaces.application.v1.ApplicationSpec
	7,  // 25: plexspaces.application.v1.DeployApplicationResponse.status:type_name -> plexspaces.application.v1.ApplicationStatus
	33, // 26: plexspaces.application.v1.UndeployApplicationRequest.timeout:type_name -> google.protobuf.Duration
	7,  // 27: plexspaces.application.v1.ListApplicationsRequest.status_filter:type_name -> plexspaces.application.v1.ApplicationStatus
	21, // 28: plexspaces.application.v1.ListApplicationsResponse.applications:type_name -> plexspaces.application.v1.ApplicationInfo
	7,  // 29: plexspaces.application.v1.ApplicationInfo.status:type_name -> plexspaces.application.v1.ApplicationStatus
	36, // 30: plexspaces.application.v1.ApplicationInfo.deployed_at:type_name -> google.protobuf.Timestamp
	22, // 31: plexspaces.application.v1.ApplicationInfo.metrics:type_name -> plexspaces.application.v1.ApplicationMetrics
	28, // 32: plexspaces.application.v1.ApplicationMetrics.actor_counts:type_name -> plexspaces.application.v1.ApplicationMetrics.ActorCountsEntry
	29, // 33: plexspaces.application.v1.ApplicationMetrics.counter_metrics:type_name -> plexspaces.application.v1.ApplicationMetrics.CounterMetricsEntry
	30, // 34: plexspaces.application.v1.ApplicationMetrics.latency_totals_ms:type_name -> plexspaces.application.v1.ApplicationMetrics.LatencyTotalsMsEntry
	31, // 35: plexspaces.application.v1.ApplicationMetrics.latency_max_ms:type_name -> plexspaces.application.v1.ApplicationMetrics.LatencyMaxMsEntry
	32, // 36: plexspaces.application.v1.ApplicationMetrics.latency_samples:type_name -> plexspaces.application.v1.ApplicationMetrics.LatencySamplesEntry
	21, // 37: plexspaces.application.v1.GetApplicationStatusResponse.application:type_name -> plexspaces.application.v1.ApplicationInfo
	14, // 38: plexspaces.application.v1.GetApplicationStatusResponse.state:type_name -> plexspaces.application.v1.ApplicationRuntimeState
	15, // 39: plexspaces.application.v1.ApplicationService.DeployApplication:input_type -> plexspaces.application.v1.DeployApplicationRequest
	17, // 40: plexspaces.application.v1.ApplicationService.UndeployApplication:input_type -> plexspaces.application.v1.UndeployApplicationRequest
	19, // 41: plexspaces.application.v1.ApplicationService.ListApplications:input_type -> plexspaces.application.v1.ListApplicationsRequest
	23, // 42: plexspaces.application.v1.ApplicationService.GetApplicationStatus:input_type -> plexspaces.application.v1.GetApplicationStatusRequest
	16, // 43: plexspaces.application.v1.ApplicationService.DeployApplication:output_type -> plexspaces.application.v1.DeployApplicationResponse
	18, // 44: plexspaces.application.v1.ApplicationService.UndeployApplication:output_type -> plexspaces.application.v1.UndeployApplicationResponse
	20, // 45: plexspaces.application.v1.ApplicationService.ListApplications:output_type -> plexspaces.application.v1.ListApplicationsResponse
	24, // 46: plexspaces.application.v1.ApplicationService.GetApplicationStatus:output_type -> plexspaces.application.v1.GetApplicationStatusResponse
	43, // [43:47] is the sub-list for method output_type
	39, // [39:43] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_plexspaces_v1_application_application_proto_init() }
func file_plexspaces_v1_application_application_proto_init() {
	if File_plexspaces_v1_application_application_proto != nil {
		return
	}
	file_plexspaces_v1_application_application_proto_msgTypes[0].OneofWrappers = []any{}
	file_plexspaces_v1_application_application_proto_msgTypes[1].OneofWrappers = []any{}
	file_plexspaces_v1_application_application_proto_msgTypes[3].OneofWrappers = []any{}
	file_plexspaces_v1_application_application_proto_msgTypes[6].OneofWrappers = []any{}
	file_plexspaces_v1_application_application_proto_msgTypes[7].OneofWrappers = []any{}
	file_plexspaces_v1_application_application_proto_msgTypes[8].OneofWrappers = []any{}
	file_plexspaces_v1_application_application_proto_msgTypes[9].OneofWrappers = []any{}
	file_plexspaces_v1_application_application_proto_msgTypes[10].OneofWrappers = []any{}
	file_plexspaces_v1_application_application_proto_msgTypes[11].OneofWrappers = []any{}
	file_plexspaces_v1_application_application_proto_msgTypes[13].OneofWrappers = []any{}
	file_plexspaces_v1_application_application_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plexspaces_v1_application_application_proto_rawDesc), len(file_plexspaces_v1_application_application_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plexspaces_v1_application_application_proto_goTypes,
		DependencyIndexes: file_plexspaces_v1_application_application_proto_depIdxs,
		EnumInfos:         file_plexspaces_v1_application_application_proto_enumTypes,
		MessageInfos:      file_plexspaces_v1_application_application_proto_msgTypes,
	}.Build()
	File_plexspaces_v1_application_application_proto = out.File
	file_plexspaces_v1_application_application_proto_goTypes = nil
	file_plexspaces_v1_application_application_proto_depIdxs = nil
}
