// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 Shahzad A. Bhatti <bhatti@plexobject.com>
//
// This file is part of PlexSpaces.
//
// PlexSpaces is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 2.1 of the License, or
// (at your option) any later version.
//
// PlexSpaces is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with PlexSpaces. If not, see <https://www.gnu.org/licenses/>.

// PlexSpaces WebAssembly Runtime API
//
// ## Purpose
// Defines the WebAssembly actor runtime for PlexSpaces, enabling polyglot
// actors with sandboxed execution, dynamic deployment, and portable code.
//
// ## Architecture Context
// This proto file implements WASM as the universal actor runtime:
// - **Walking Skeleton Phase 6** (Week 11-12): WASM runtime foundation
// - **Core Principle**: Compile all actors to WASM for portability
// - **JavaNow Evolution**: Replaces mobile agents with code caching + state migration
// - **Polyglot Support**: Rust, JavaScript (Javy), Go (TinyGo), Python (componentize-py)
//
// ## Integration Points
// - **Actor System**: WASM actors implement ActorBehavior trait
// - **Durability**: Integrates with existing journaling system (Priority 0)
// - **TupleSpace**: WASM actors access TupleSpace via host functions
// - **Firecracker**: Separate concern - launches entire applications in VMs (not actor-level)
//
// ## Component Interactions
// - Used by: ActorService (spawn WASM actors), NodeService (module distribution)
// - Depends on: actor.proto (ActorId, ActorBehavior), common.proto (Metadata)
// - Provides: WasmRuntimeService (module deployment, instantiation)
//
// ## Design Decisions
// 1. **wasmtime Runtime**: Production-ready, Component Model support (User Decision A1)
// 2. **Component Model ABI**: Type-safe, composable, future-proof (User Decision A2)
// 3. **Language Priority**: Rust → JavaScript → Go (User Decision A3)
// 4. **Hybrid Distribution**: Pull with pre-warming (Design Question 4)
// 5. **Basic Resource Limits**: Memory + fuel metering (User Decision A6)
// 6. **WASI Capabilities**: Standard I/O model (User Decision A7)
// 7. **Explicit Migration**: Simplest approach, aligns with core tenet (User Decision A8)
// 8. **Balanced Performance**: Cold < 100ms, warm < 10ms (User Decision A10)
//
// ## Performance Targets
// - **Cold Start**: < 100ms (module compilation + instantiation)
// - **Warm Start**: < 10ms (instance from pool)
// - **Migration**: < 10ms (state transfer only, code cached everywhere)
// - **Memory Efficiency**: 2MB per actor (32x better than JavaNow's 64MB)
// - **Throughput**: > 10,000 actors per node, > 100,000 messages/sec
//
// ## References
// - Walking Skeleton Phase 6 (CLAUDE.md)
// - JavaNow Modernization Roadmap (docs/WASM_DESIGN_QUESTIONS.md)
// - WASI Preview 2: https://github.com/WebAssembly/WASI
// - Component Model: https://github.com/WebAssembly/component-model

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plexspaces/v1/wasm/wasm.proto

package wasmv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/bhatti/PlexSpaces/sdks/go/plexspaces/proto/plexspaces/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WASM runtime error codes
//
// ## Purpose
// Defines error categories for WASM operations. Used for gRPC status codes
// and error reporting across language boundaries.
//
// ## Why This Exists
// - **Proto-First**: Errors are part of the API contract (not Rust-only)
// - **Multi-Language**: Error types available in all supported languages (TypeScript, Python SDKs)
// - **gRPC Compatibility**: Maps to gRPC status codes for proper error handling
// - **Structured Errors**: Clients can handle specific error types programmatically
//
// ## Design Notes
// - Error codes are stable (don't reorder or change values)
// - New error codes can be added at the end
// - OK = 0 for consistency with gRPC conventions
type WasmErrorCode int32

const (
	// Success (not an error)
	WasmErrorCode_WASM_ERROR_CODE_OK WasmErrorCode = 0
	// Module compilation failed
	//
	// Causes: Invalid WASM bytecode, unsupported features, syntax errors
	// Recovery: Fix WASM module, use compatible toolchain
	WasmErrorCode_WASM_ERROR_CODE_COMPILATION_FAILED WasmErrorCode = 1
	// Module instantiation failed
	//
	// Causes: Import resolution errors, initialization errors, memory allocation failure
	// Recovery: Check module dependencies, ensure host functions available
	WasmErrorCode_WASM_ERROR_CODE_INSTANTIATION_FAILED WasmErrorCode = 2
	// Resource limit exceeded (memory, fuel, CPU time)
	//
	// Causes: Actor exceeded memory/fuel/time quota
	// Recovery: Increase limits or optimize actor code
	WasmErrorCode_WASM_ERROR_CODE_RESOURCE_LIMIT_EXCEEDED WasmErrorCode = 3
	// Capability denied (missing permission)
	//
	// Causes: Actor attempted unauthorized operation (filesystem, network, spawn)
	// Recovery: Grant capability or remove unauthorized code
	WasmErrorCode_WASM_ERROR_CODE_CAPABILITY_DENIED WasmErrorCode = 4
	// Host function call failed
	//
	// Causes: Host function error (send_message failed, tuplespace_write failed)
	// Recovery: Check host function arguments, retry
	WasmErrorCode_WASM_ERROR_CODE_HOST_FUNCTION_ERROR WasmErrorCode = 5
	// Actor function call failed
	//
	// Causes: Actor's exported function (init, handle_message) threw error or trapped
	// Recovery: Fix actor code, check logs
	WasmErrorCode_WASM_ERROR_CODE_ACTOR_FUNCTION_ERROR WasmErrorCode = 6
	// Module cache error
	//
	// Causes: Cache lookup failed, eviction error, storage backend error
	// Recovery: Retry, check cache backend health
	WasmErrorCode_WASM_ERROR_CODE_CACHE_ERROR WasmErrorCode = 7
	// Module hash mismatch (integrity check failed)
	//
	// Causes: Module bytes corrupted during transfer, malicious modification
	// Recovery: Re-deploy module, check network integrity
	WasmErrorCode_WASM_ERROR_CODE_HASH_MISMATCH WasmErrorCode = 8
	// Module not found
	//
	// Causes: Module not deployed, evicted from cache, wrong name/version
	// Recovery: Deploy module first, check name/version
	WasmErrorCode_WASM_ERROR_CODE_MODULE_NOT_FOUND WasmErrorCode = 9
	// Serialization/deserialization error
	//
	// Causes: Invalid protobuf, incompatible schema version
	// Recovery: Check message format, ensure compatible versions
	WasmErrorCode_WASM_ERROR_CODE_SERIALIZATION_ERROR WasmErrorCode = 10
	// Internal wasmtime runtime error
	//
	// Causes: wasmtime internal error, runtime bug
	// Recovery: Check logs, report bug, try different wasmtime version
	WasmErrorCode_WASM_ERROR_CODE_WASMTIME_ERROR WasmErrorCode = 11
)

// Enum value maps for WasmErrorCode.
var (
	WasmErrorCode_name = map[int32]string{
		0:  "WASM_ERROR_CODE_OK",
		1:  "WASM_ERROR_CODE_COMPILATION_FAILED",
		2:  "WASM_ERROR_CODE_INSTANTIATION_FAILED",
		3:  "WASM_ERROR_CODE_RESOURCE_LIMIT_EXCEEDED",
		4:  "WASM_ERROR_CODE_CAPABILITY_DENIED",
		5:  "WASM_ERROR_CODE_HOST_FUNCTION_ERROR",
		6:  "WASM_ERROR_CODE_ACTOR_FUNCTION_ERROR",
		7:  "WASM_ERROR_CODE_CACHE_ERROR",
		8:  "WASM_ERROR_CODE_HASH_MISMATCH",
		9:  "WASM_ERROR_CODE_MODULE_NOT_FOUND",
		10: "WASM_ERROR_CODE_SERIALIZATION_ERROR",
		11: "WASM_ERROR_CODE_WASMTIME_ERROR",
	}
	WasmErrorCode_value = map[string]int32{
		"WASM_ERROR_CODE_OK":                      0,
		"WASM_ERROR_CODE_COMPILATION_FAILED":      1,
		"WASM_ERROR_CODE_INSTANTIATION_FAILED":    2,
		"WASM_ERROR_CODE_RESOURCE_LIMIT_EXCEEDED": 3,
		"WASM_ERROR_CODE_CAPABILITY_DENIED":       4,
		"WASM_ERROR_CODE_HOST_FUNCTION_ERROR":     5,
		"WASM_ERROR_CODE_ACTOR_FUNCTION_ERROR":    6,
		"WASM_ERROR_CODE_CACHE_ERROR":             7,
		"WASM_ERROR_CODE_HASH_MISMATCH":           8,
		"WASM_ERROR_CODE_MODULE_NOT_FOUND":        9,
		"WASM_ERROR_CODE_SERIALIZATION_ERROR":     10,
		"WASM_ERROR_CODE_WASMTIME_ERROR":          11,
	}
)

func (x WasmErrorCode) Enum() *WasmErrorCode {
	p := new(WasmErrorCode)
	*p = x
	return p
}

func (x WasmErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WasmErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_wasm_wasm_proto_enumTypes[0].Descriptor()
}

func (WasmErrorCode) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_wasm_wasm_proto_enumTypes[0]
}

func (x WasmErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WasmErrorCode.Descriptor instead.
func (WasmErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{0}
}

// Pre-warm strategy
type DeployWasmModuleRequest_PreWarmStrategy int32

const (
	// No pre-warming - nodes fetch on-demand (lazy)
	DeployWasmModuleRequest_NONE DeployWasmModuleRequest_PreWarmStrategy = 0
	// Announce to all nodes - they decide whether to pre-fetch
	DeployWasmModuleRequest_ANNOUNCE DeployWasmModuleRequest_PreWarmStrategy = 1
	// Push to all nodes immediately (eager)
	DeployWasmModuleRequest_PUSH_ALL DeployWasmModuleRequest_PreWarmStrategy = 2
	// Push to subset of nodes (e.g., based on tags)
	DeployWasmModuleRequest_PUSH_TAGGED DeployWasmModuleRequest_PreWarmStrategy = 3
)

// Enum value maps for DeployWasmModuleRequest_PreWarmStrategy.
var (
	DeployWasmModuleRequest_PreWarmStrategy_name = map[int32]string{
		0: "NONE",
		1: "ANNOUNCE",
		2: "PUSH_ALL",
		3: "PUSH_TAGGED",
	}
	DeployWasmModuleRequest_PreWarmStrategy_value = map[string]int32{
		"NONE":        0,
		"ANNOUNCE":    1,
		"PUSH_ALL":    2,
		"PUSH_TAGGED": 3,
	}
)

func (x DeployWasmModuleRequest_PreWarmStrategy) Enum() *DeployWasmModuleRequest_PreWarmStrategy {
	p := new(DeployWasmModuleRequest_PreWarmStrategy)
	*p = x
	return p
}

func (x DeployWasmModuleRequest_PreWarmStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployWasmModuleRequest_PreWarmStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_plexspaces_v1_wasm_wasm_proto_enumTypes[1].Descriptor()
}

func (DeployWasmModuleRequest_PreWarmStrategy) Type() protoreflect.EnumType {
	return &file_plexspaces_v1_wasm_wasm_proto_enumTypes[1]
}

func (x DeployWasmModuleRequest_PreWarmStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployWasmModuleRequest_PreWarmStrategy.Descriptor instead.
func (DeployWasmModuleRequest_PreWarmStrategy) EnumDescriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{6, 0}
}

// Outbound HTTP request sent by actor-world host.http-fetch.
//
// The WIT operation keeps link/method/path as typed arguments and exchanges
// request metadata/body as protobuf bytes so polyglot SDKs can share one model.
type HttpFetchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request headers to merge with service-link defaults and auth headers.
	Headers map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Raw request body bytes.
	Body          []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpFetchRequest) Reset() {
	*x = HttpFetchRequest{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpFetchRequest) ProtoMessage() {}

func (x *HttpFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpFetchRequest.ProtoReflect.Descriptor instead.
func (*HttpFetchRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{0}
}

func (x *HttpFetchRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpFetchRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Outbound HTTP response returned by actor-world host.http-fetch.
type HttpFetchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status code.
	Status uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Response headers.
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Raw response body bytes.
	Body          []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpFetchResponse) Reset() {
	*x = HttpFetchResponse{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpFetchResponse) ProtoMessage() {}

func (x *HttpFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpFetchResponse.ProtoReflect.Descriptor instead.
func (*HttpFetchResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{1}
}

func (x *HttpFetchResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpFetchResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpFetchResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// WebAssembly module definition
//
// ## Purpose
// Represents a compiled WebAssembly module that can be deployed to nodes
// and instantiated as actors. Modules are immutable and content-addressed
// for caching and deduplication.
//
// ## Why This Exists
// - Enables dynamic code deployment (like Java classloader)
// - Content-addressed hash allows efficient caching across nodes
// - Metadata enables version management and dependency tracking
// - Separation of code (module) and state (actor instance) enables fast migration
//
// ## Design Notes
// - `module_bytes` is the compiled WASM binary (Component Model format)
// - `module_hash` is SHA-256 for cache lookup and verification
// - `wit_interface` is optional WIT definition for tooling/debugging
// - Modules are immutable - updates create new versions with different hashes
type WasmModule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module name (e.g., "counter-actor", "chat-room-actor")
	//
	// Used for human-readable identification and registry lookups.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Module version (semantic versioning: "1.2.3")
	//
	// Enables gradual rollout and rollback of actor code.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Compiled WebAssembly Component Model bytes
	//
	// This is the actual WASM binary that will be loaded and instantiated.
	// Must be a valid WASM Component Model module (not legacy WASM).
	ModuleBytes []byte `protobuf:"bytes,3,opt,name=module_bytes,json=moduleBytes,proto3" json:"module_bytes,omitempty"`
	// SHA-256 hash of module_bytes (for content-addressable caching)
	//
	// Format: hex-encoded 64-character string
	// Example: "a1b2c3d4e5f6..."
	//
	// Why content-addressed:
	// - Deduplication: Same module hash = same module, cache once
	// - Verification: Ensure module integrity during distribution
	// - Efficient lookup: Nodes can check cache before downloading
	ModuleHash string `protobuf:"bytes,4,opt,name=module_hash,json=moduleHash,proto3" json:"module_hash,omitempty"`
	// WIT (WebAssembly Interface Types) interface definition (optional)
	//
	// Human-readable interface for tooling, debugging, and documentation.
	// Not required for runtime (Component Model is self-describing).
	WitInterface string `protobuf:"bytes,5,opt,name=wit_interface,json=witInterface,proto3" json:"wit_interface,omitempty"`
	// Supported languages (e.g., "rust", "javascript", "go")
	//
	// Indicates source language for debugging and tooling.
	SourceLanguages []string `protobuf:"bytes,6,rep,name=source_languages,json=sourceLanguages,proto3" json:"source_languages,omitempty"`
	// Module metadata (tags, labels, annotations)
	//
	// Examples:
	// - tags: ["production", "stateless", "compute-intensive"]
	// - labels: {"team": "backend", "service": "payment"}
	Metadata *v1.Metadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Upload timestamp (when module was first deployed to registry)
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Module size in bytes (uncompressed)
	//
	// Used for bandwidth estimation and pre-warming decisions.
	SizeBytes uint64 `protobuf:"varint,9,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Schema version for forward/backward compatibility
	VersionNumber uint32 `protobuf:"varint,10,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WasmModule) Reset() {
	*x = WasmModule{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasmModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmModule) ProtoMessage() {}

func (x *WasmModule) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmModule.ProtoReflect.Descriptor instead.
func (*WasmModule) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{2}
}

func (x *WasmModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WasmModule) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WasmModule) GetModuleBytes() []byte {
	if x != nil {
		return x.ModuleBytes
	}
	return nil
}

func (x *WasmModule) GetModuleHash() string {
	if x != nil {
		return x.ModuleHash
	}
	return ""
}

func (x *WasmModule) GetWitInterface() string {
	if x != nil {
		return x.WitInterface
	}
	return ""
}

func (x *WasmModule) GetSourceLanguages() []string {
	if x != nil {
		return x.SourceLanguages
	}
	return nil
}

func (x *WasmModule) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WasmModule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WasmModule) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *WasmModule) GetVersionNumber() uint32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

// Resource limits for WASM actor instances
//
// ## Purpose
// Defines resource constraints for WASM actors to prevent resource exhaustion
// and ensure fair scheduling. Enforced by wasmtime runtime.
//
// ## Why This Exists
// - Memory limits prevent OOM crashes (multi-tenant safety)
// - Fuel metering prevents infinite loops (gas-style execution limits)
// - Time limits prevent hung actors
// - Stack limits prevent stack overflow
//
// ## Design Notes
// - Limits are per-instance (each actor has own quota)
// - Fuel is like Ethereum gas - metered during execution
// - Defaults chosen for balanced workloads (can override per-actor)
type ResourceLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum linear memory size in bytes (default: 16MB)
	//
	// WASM linear memory is contiguous, growable.
	// 16MB default balances:
	// - Enough for most actors (2MB-8MB typical)
	// - 64 actors per GB of RAM
	// - 32x more efficient than JavaNow (64MB per actor)
	MaxMemoryBytes uint64 `protobuf:"varint,1,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	// Maximum stack size in bytes (default: 512KB)
	//
	// Stack overflow protection. Most actors use < 100KB.
	MaxStackBytes uint64 `protobuf:"varint,2,opt,name=max_stack_bytes,json=maxStackBytes,proto3" json:"max_stack_bytes,omitempty"`
	// Maximum fuel units (gas-style execution limit)
	//
	// Fuel is consumed during execution (ops, memory access, calls).
	// Default: 10 billion units = ~1 second CPU time
	// Zero = unlimited (not recommended for untrusted code)
	MaxFuel uint64 `protobuf:"varint,3,opt,name=max_fuel,json=maxFuel,proto3" json:"max_fuel,omitempty"`
	// Maximum execution time per message (optional)
	//
	// If set, actor handler must complete within this duration.
	// Default: None (rely on fuel metering instead)
	MaxExecutionTime *durationpb.Duration `protobuf:"bytes,4,opt,name=max_execution_time,json=maxExecutionTime,proto3" json:"max_execution_time,omitempty"`
	// Maximum table elements (for indirect calls)
	//
	// Default: 10,000 (enough for most actors)
	MaxTableElements uint32 `protobuf:"varint,5,opt,name=max_table_elements,json=maxTableElements,proto3" json:"max_table_elements,omitempty"`
	// Maximum number of instances in instance pool
	//
	// For warm start optimization. Default: 10 per actor type.
	MaxPooledInstances uint32 `protobuf:"varint,6,opt,name=max_pooled_instances,json=maxPooledInstances,proto3" json:"max_pooled_instances,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceLimits) GetMaxMemoryBytes() uint64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxStackBytes() uint64 {
	if x != nil {
		return x.MaxStackBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxFuel() uint64 {
	if x != nil {
		return x.MaxFuel
	}
	return 0
}

func (x *ResourceLimits) GetMaxExecutionTime() *durationpb.Duration {
	if x != nil {
		return x.MaxExecutionTime
	}
	return nil
}

func (x *ResourceLimits) GetMaxTableElements() uint32 {
	if x != nil {
		return x.MaxTableElements
	}
	return 0
}

func (x *ResourceLimits) GetMaxPooledInstances() uint32 {
	if x != nil {
		return x.MaxPooledInstances
	}
	return 0
}

// WASI capabilities for WASM actors
//
// ## Purpose
// Defines what host resources a WASM actor can access. Based on WASI Preview 2
// capability-based security model.
//
// ## Why This Exists
// - **Principle of Least Privilege**: Actors only get capabilities they need
// - **Facets Pattern Revival**: JavaNow-inspired capability composition
// - **Security**: Sandboxed actors cannot access unauthorized resources
// - **Auditing**: Capabilities are explicit and logged
//
// ## Design Notes
// - Capabilities are granted at instantiation time (immutable per instance)
// - WASI capabilities (filesystem, network, clocks) use WASI standard
// - PlexSpaces capabilities (tuplespace, actors) are custom host functions
// - Denied by default (opt-in model)
type WasmCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allow filesystem access (WASI filesystem interface)
	//
	// If true, actor can use WASI file operations (open, read, write).
	// Paths are virtualized (actor cannot access arbitrary host paths).
	AllowFilesystem bool `protobuf:"varint,1,opt,name=allow_filesystem,json=allowFilesystem,proto3" json:"allow_filesystem,omitempty"`
	// Filesystem root path (if filesystem access allowed)
	//
	// Actor's root is mapped to this host path (chroot-style).
	// Example: "/actors/{actor_id}/data"
	FilesystemRoot string `protobuf:"bytes,2,opt,name=filesystem_root,json=filesystemRoot,proto3" json:"filesystem_root,omitempty"`
	// Allow network access (WASI sockets interface)
	//
	// If true, actor can make outbound network connections.
	// Inbound connections not supported (actors receive messages via mailbox).
	AllowNetwork bool `protobuf:"varint,3,opt,name=allow_network,json=allowNetwork,proto3" json:"allow_network,omitempty"`
	// Allow environment variables (WASI environment interface)
	//
	// If true, actor can read environment variables.
	// Useful for configuration (but TupleSpace config preferred).
	AllowEnv bool `protobuf:"varint,4,opt,name=allow_env,json=allowEnv,proto3" json:"allow_env,omitempty"`
	// Allow random number generation (WASI random interface)
	//
	// If true, actor can use cryptographically secure random.
	// Generally safe to allow.
	AllowRandom bool `protobuf:"varint,5,opt,name=allow_random,json=allowRandom,proto3" json:"allow_random,omitempty"`
	// Allow clock access (WASI clocks interface)
	//
	// If true, actor can read monotonic and wall-clock time.
	// Required for timeouts, timestamps.
	AllowClocks bool `protobuf:"varint,6,opt,name=allow_clocks,json=allowClocks,proto3" json:"allow_clocks,omitempty"`
	// Allow TupleSpace operations (PlexSpaces-specific)
	//
	// If true, actor can call host functions: tuplespace_write, tuplespace_read, etc.
	// Most actors need this for coordination.
	AllowTuplespace bool `protobuf:"varint,7,opt,name=allow_tuplespace,json=allowTuplespace,proto3" json:"allow_tuplespace,omitempty"`
	// Allow actor spawning (PlexSpaces-specific)
	//
	// If true, actor can spawn new actors via spawn_actor host function.
	// Useful for supervisor actors, not needed for leaf actors.
	AllowSpawnActors bool `protobuf:"varint,8,opt,name=allow_spawn_actors,json=allowSpawnActors,proto3" json:"allow_spawn_actors,omitempty"`
	// Allow message sending (PlexSpaces-specific)
	//
	// If true, actor can send messages to other actors via send_message host function.
	// Almost all actors need this (inter-actor communication).
	AllowSendMessages bool `protobuf:"varint,9,opt,name=allow_send_messages,json=allowSendMessages,proto3" json:"allow_send_messages,omitempty"`
	// Allow logging (PlexSpaces-specific)
	//
	// If true, actor can emit logs via log host function.
	// Useful for debugging, not required for production actors.
	AllowLogging  bool `protobuf:"varint,10,opt,name=allow_logging,json=allowLogging,proto3" json:"allow_logging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WasmCapabilities) Reset() {
	*x = WasmCapabilities{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasmCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmCapabilities) ProtoMessage() {}

func (x *WasmCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmCapabilities.ProtoReflect.Descriptor instead.
func (*WasmCapabilities) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{4}
}

func (x *WasmCapabilities) GetAllowFilesystem() bool {
	if x != nil {
		return x.AllowFilesystem
	}
	return false
}

func (x *WasmCapabilities) GetFilesystemRoot() string {
	if x != nil {
		return x.FilesystemRoot
	}
	return ""
}

func (x *WasmCapabilities) GetAllowNetwork() bool {
	if x != nil {
		return x.AllowNetwork
	}
	return false
}

func (x *WasmCapabilities) GetAllowEnv() bool {
	if x != nil {
		return x.AllowEnv
	}
	return false
}

func (x *WasmCapabilities) GetAllowRandom() bool {
	if x != nil {
		return x.AllowRandom
	}
	return false
}

func (x *WasmCapabilities) GetAllowClocks() bool {
	if x != nil {
		return x.AllowClocks
	}
	return false
}

func (x *WasmCapabilities) GetAllowTuplespace() bool {
	if x != nil {
		return x.AllowTuplespace
	}
	return false
}

func (x *WasmCapabilities) GetAllowSpawnActors() bool {
	if x != nil {
		return x.AllowSpawnActors
	}
	return false
}

func (x *WasmCapabilities) GetAllowSendMessages() bool {
	if x != nil {
		return x.AllowSendMessages
	}
	return false
}

func (x *WasmCapabilities) GetAllowLogging() bool {
	if x != nil {
		return x.AllowLogging
	}
	return false
}

// WASM actor configuration
//
// ## Purpose
// Combines resource limits and capabilities into a complete configuration
// for instantiating a WASM actor. Can be templated per actor type.
//
// ## Why This Exists
// - **Reusable Profiles**: Define once, apply to many actors
// - **Security Policies**: Enforce organizational security requirements
// - **Resource Management**: Prevent resource exhaustion
//
// ## Design Notes
// - Can create profiles: "untrusted" (minimal caps), "trusted" (full caps)
// - Immutable after instantiation (cannot escalate privileges)
type WasmConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource limits for this actor
	Limits *ResourceLimits `protobuf:"bytes,1,opt,name=limits,proto3" json:"limits,omitempty"`
	// Capabilities granted to this actor
	Capabilities *WasmCapabilities `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Configuration name (e.g., "default", "untrusted", "compute-intensive")
	//
	// Allows reusing configurations across actors.
	ProfileName string `protobuf:"bytes,3,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	// Enable instance pooling for warm starts
	//
	// If true, pre-instantiate instances for faster spawning.
	// Trade-off: Memory usage vs latency.
	EnablePooling bool `protobuf:"varint,4,opt,name=enable_pooling,json=enablePooling,proto3" json:"enable_pooling,omitempty"`
	// Enable ahead-of-time (AOT) compilation
	//
	// If true, compile module to native code on deployment.
	// Trade-off: Deployment time vs execution speed.
	EnableAot bool `protobuf:"varint,5,opt,name=enable_aot,json=enableAot,proto3" json:"enable_aot,omitempty"`
	// Enable checkpoint/restore durability (load on init, save on terminate).
	//
	// Off by default for performance. When true, actor state is loaded from
	// journal on init and saved on terminate (Cloudflare Durable Objects pattern).
	DurabilityEnabled bool `protobuf:"varint,6,opt,name=durability_enabled,json=durabilityEnabled,proto3" json:"durability_enabled,omitempty"`
	// Use pre-instantiated instance pool (InstancePool) when spawning actors.
	//
	// On by default. When true, runtime may checkout from a per-module pool instead
	// of instantiating each time (faster spawn when pool has capacity). Requires
	// deploy-path integration; until then, only engine-level pooling (enable_pooling)
	// is active for HTTP/deploy.
	UseInstancePool bool `protobuf:"varint,7,opt,name=use_instance_pool,json=useInstancePool,proto3" json:"use_instance_pool,omitempty"`
	// Maximum concurrent instantiations (initial + re-instantiation) when pooling is enabled.
	//
	// Limits total concurrent Wasmtime instantiations to avoid hitting Wasmtime's memory-stripe
	// limit (default 10). Per-actor re-instantiation lock serializes per actor; this global cap
	// prevents N actors from re-instantiating at once. Default: 8 (stays under Wasmtime's limit
	// with headroom). Only used when enable_pooling is true.
	//
	// When 0 or not set, uses code default of 8.
	MaxConcurrentInstantiations uint32 `protobuf:"varint,8,opt,name=max_concurrent_instantiations,json=maxConcurrentInstantiations,proto3" json:"max_concurrent_instantiations,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *WasmConfig) Reset() {
	*x = WasmConfig{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasmConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmConfig) ProtoMessage() {}

func (x *WasmConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmConfig.ProtoReflect.Descriptor instead.
func (*WasmConfig) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{5}
}

func (x *WasmConfig) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *WasmConfig) GetCapabilities() *WasmCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *WasmConfig) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *WasmConfig) GetEnablePooling() bool {
	if x != nil {
		return x.EnablePooling
	}
	return false
}

func (x *WasmConfig) GetEnableAot() bool {
	if x != nil {
		return x.EnableAot
	}
	return false
}

func (x *WasmConfig) GetDurabilityEnabled() bool {
	if x != nil {
		return x.DurabilityEnabled
	}
	return false
}

func (x *WasmConfig) GetUseInstancePool() bool {
	if x != nil {
		return x.UseInstancePool
	}
	return false
}

func (x *WasmConfig) GetMaxConcurrentInstantiations() uint32 {
	if x != nil {
		return x.MaxConcurrentInstantiations
	}
	return 0
}

// Deploy WASM module request
//
// ## Purpose
// Uploads a WASM module to the cluster registry and optionally pre-warms
// nodes by pushing the module to their caches.
//
// ## Why This Exists
// - **Hybrid Distribution**: Push announces availability, nodes can pull
// - **Pre-warming**: Reduce cold start latency by pre-fetching modules
// - **Version Management**: Deploy new versions without disrupting running actors
//
// ## Design Notes
// - Module stored in cluster registry (e.g., S3, Redis, etcd)
// - Nodes notified of new module (can pre-fetch if heuristics match)
// - Idempotent: Re-deploying same module (same hash) is no-op
type DeployWasmModuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WASM module to deploy
	Module *WasmModule `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// How to distribute module to nodes
	PreWarm DeployWasmModuleRequest_PreWarmStrategy `protobuf:"varint,2,opt,name=pre_warm,json=preWarm,proto3,enum=plexspaces.wasm.v1.DeployWasmModuleRequest_PreWarmStrategy" json:"pre_warm,omitempty"`
	// Node tags for PUSH_TAGGED strategy (e.g., ["us-east-1", "production"])
	TargetNodeTags []string `protobuf:"bytes,3,rep,name=target_node_tags,json=targetNodeTags,proto3" json:"target_node_tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeployWasmModuleRequest) Reset() {
	*x = DeployWasmModuleRequest{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployWasmModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployWasmModuleRequest) ProtoMessage() {}

func (x *DeployWasmModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployWasmModuleRequest.ProtoReflect.Descriptor instead.
func (*DeployWasmModuleRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{6}
}

func (x *DeployWasmModuleRequest) GetModule() *WasmModule {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *DeployWasmModuleRequest) GetPreWarm() DeployWasmModuleRequest_PreWarmStrategy {
	if x != nil {
		return x.PreWarm
	}
	return DeployWasmModuleRequest_NONE
}

func (x *DeployWasmModuleRequest) GetTargetNodeTags() []string {
	if x != nil {
		return x.TargetNodeTags
	}
	return nil
}

// Deploy WASM module response
type DeployWasmModuleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Was deployment successful?
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Module hash (for cache lookup)
	ModuleHash string `protobuf:"bytes,2,opt,name=module_hash,json=moduleHash,proto3" json:"module_hash,omitempty"`
	// Number of nodes that received the module (for pre-warming)
	NodesPreWarmed uint32 `protobuf:"varint,3,opt,name=nodes_pre_warmed,json=nodesPreWarmed,proto3" json:"nodes_pre_warmed,omitempty"`
	// Error details if deployment failed (replaces error_message)
	//
	// If deployment succeeded, this field is not set (code = OK).
	// If deployment failed, code indicates failure reason.
	Error         *WasmError `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployWasmModuleResponse) Reset() {
	*x = DeployWasmModuleResponse{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployWasmModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployWasmModuleResponse) ProtoMessage() {}

func (x *DeployWasmModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployWasmModuleResponse.ProtoReflect.Descriptor instead.
func (*DeployWasmModuleResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{7}
}

func (x *DeployWasmModuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployWasmModuleResponse) GetModuleHash() string {
	if x != nil {
		return x.ModuleHash
	}
	return ""
}

func (x *DeployWasmModuleResponse) GetNodesPreWarmed() uint32 {
	if x != nil {
		return x.NodesPreWarmed
	}
	return 0
}

func (x *DeployWasmModuleResponse) GetError() *WasmError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Instantiate WASM actor request
//
// ## Purpose
// Creates a new actor instance from a deployed WASM module. The instance
// is initialized with provided state and configuration.
//
// ## Why This Exists
// - **Dynamic Actor Creation**: Spawn actors at runtime (like erlang:spawn)
// - **State Initialization**: Restore actor from snapshot or start fresh
// - **Configuration Flexibility**: Each actor can have custom config
//
// ## Design Notes
// - Module must be deployed first (or node will fetch on-demand)
// - Initial state is opaque bytes (actor interprets based on module logic)
// - Config can override module defaults (e.g., more memory for specific actor)
type InstantiateActorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module name or hash to instantiate
	//
	// Supports both:
	// - Name: "counter-actor@1.2.3" (fetches from registry)
	// - Hash: "a1b2c3d4..." (direct cache lookup)
	ModuleRef string `protobuf:"bytes,1,opt,name=module_ref,json=moduleRef,proto3" json:"module_ref,omitempty"`
	// Actor ID to assign to this instance
	//
	// Format: ULID for sortability (see CLAUDE.md Core Principle 0)
	ActorId string `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Initial state bytes (opaque to runtime)
	//
	// Passed to WASM module's init() function.
	// Can be:
	// - Empty (new actor with default state)
	// - Snapshot (restoring actor from checkpoint)
	// - Migration state (actor moving to new node)
	InitialState []byte `protobuf:"bytes,3,opt,name=initial_state,json=initialState,proto3" json:"initial_state,omitempty"`
	// Configuration overrides (optional)
	//
	// If not provided, uses module's default config or system defaults.
	Config *WasmConfig `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	// Node ID to instantiate on (optional)
	//
	// If not provided, scheduler chooses node based on load balancing.
	TargetNodeId  string `protobuf:"bytes,5,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstantiateActorRequest) Reset() {
	*x = InstantiateActorRequest{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstantiateActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstantiateActorRequest) ProtoMessage() {}

func (x *InstantiateActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstantiateActorRequest.ProtoReflect.Descriptor instead.
func (*InstantiateActorRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{8}
}

func (x *InstantiateActorRequest) GetModuleRef() string {
	if x != nil {
		return x.ModuleRef
	}
	return ""
}

func (x *InstantiateActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *InstantiateActorRequest) GetInitialState() []byte {
	if x != nil {
		return x.InitialState
	}
	return nil
}

func (x *InstantiateActorRequest) GetConfig() *WasmConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InstantiateActorRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

// Instantiate WASM actor response
type InstantiateActorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Was instantiation successful?
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Actor ID of instantiated actor
	ActorId string `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Node ID where actor is running
	NodeId string `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Instance creation time
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Error details if instantiation failed (replaces error_message)
	//
	// If instantiation succeeded, this field is not set (code = OK).
	// If instantiation failed, code indicates failure reason.
	Error         *WasmError `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstantiateActorResponse) Reset() {
	*x = InstantiateActorResponse{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstantiateActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstantiateActorResponse) ProtoMessage() {}

func (x *InstantiateActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstantiateActorResponse.ProtoReflect.Descriptor instead.
func (*InstantiateActorResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{9}
}

func (x *InstantiateActorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstantiateActorResponse) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *InstantiateActorResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InstantiateActorResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InstantiateActorResponse) GetError() *WasmError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Migrate WASM actor request
//
// ## Purpose
// Moves a running actor from one node to another. Only state migrates,
// code (WASM module) is already cached on destination node.
//
// ## Why This Exists
// - **Load Balancing**: Move actors to less loaded nodes
// - **Node Shutdown**: Drain actors before maintenance
// - **Locality Optimization**: Move actor closer to data
//
// ## Design Notes
// - Explicit migration (user-initiated) - simplest approach (User Decision A8)
// - Code cached everywhere - only state migrates (10ms vs 500ms)
// - Atomic migration: Source actor paused until destination ready
type MigrateActorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Actor ID to migrate
	ActorId string `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Source node ID (current location)
	SourceNodeId string `protobuf:"bytes,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	// Destination node ID (target location)
	TargetNodeId string `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	// Include journal entries (for durable actors)
	//
	// If true, migrate journal for replay on destination.
	IncludeJournal bool `protobuf:"varint,4,opt,name=include_journal,json=includeJournal,proto3" json:"include_journal,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MigrateActorRequest) Reset() {
	*x = MigrateActorRequest{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateActorRequest) ProtoMessage() {}

func (x *MigrateActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateActorRequest.ProtoReflect.Descriptor instead.
func (*MigrateActorRequest) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{10}
}

func (x *MigrateActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *MigrateActorRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *MigrateActorRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *MigrateActorRequest) GetIncludeJournal() bool {
	if x != nil {
		return x.IncludeJournal
	}
	return false
}

// Migrate WASM actor response
type MigrateActorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Was migration successful?
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Migration duration (should be < 10ms for state-only)
	MigrationTime *durationpb.Duration `protobuf:"bytes,2,opt,name=migration_time,json=migrationTime,proto3" json:"migration_time,omitempty"`
	// Size of state transferred (bytes)
	StateSizeBytes uint64 `protobuf:"varint,3,opt,name=state_size_bytes,json=stateSizeBytes,proto3" json:"state_size_bytes,omitempty"`
	// Error details if migration failed
	Error         *WasmError `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateActorResponse) Reset() {
	*x = MigrateActorResponse{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateActorResponse) ProtoMessage() {}

func (x *MigrateActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateActorResponse.ProtoReflect.Descriptor instead.
func (*MigrateActorResponse) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{11}
}

func (x *MigrateActorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MigrateActorResponse) GetMigrationTime() *durationpb.Duration {
	if x != nil {
		return x.MigrationTime
	}
	return nil
}

func (x *MigrateActorResponse) GetStateSizeBytes() uint64 {
	if x != nil {
		return x.StateSizeBytes
	}
	return 0
}

func (x *MigrateActorResponse) GetError() *WasmError {
	if x != nil {
		return x.Error
	}
	return nil
}

// WASM error details
//
// ## Purpose
// Provides structured error information for debugging and error handling.
// Replaces simple string error messages with typed, actionable error data.
//
// ## Why This Exists
// - **Debugging**: Details map provides context (module name, actor ID, stack trace)
// - **Client Handling**: Clients can programmatically handle specific error codes
// - **Observability**: Error metrics can be tracked by code
// - **Hash Mismatch**: Special fields for integrity check failures
//
// ## Design Notes
// - Compatible with gRPC Status (code + message + details)
// - Details map is extensible (add any key-value metadata)
// - expected_hash/actual_hash only populated for HASH_MISMATCH errors
//
// ## Examples
// ```
//
//	WasmError {
//	  code: RESOURCE_LIMIT_EXCEEDED,
//	  message: "Memory limit exceeded: 18MB > 16MB",
//	  details: {
//	    "actor_id": "calc-001@node2",
//	    "limit": "16777216",
//	    "actual": "18874368",
//	    "resource": "memory"
//	  }
//	}
//
// ```
type WasmError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code category
	Code WasmErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=plexspaces.wasm.v1.WasmErrorCode" json:"code,omitempty"`
	// Human-readable error message
	//
	// Format: Brief description suitable for logging and user display
	// Example: "Module compilation failed: invalid opcode at offset 0x1234"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Additional context for debugging
	//
	// Common keys:
	// - "actor_id": Actor that failed
	// - "module_name": Module that failed
	// - "module_hash": Module hash for integrity errors
	// - "stack_trace": Stack trace if available
	// - "resource": Resource type (memory, fuel, cpu_time)
	// - "limit": Resource limit value
	// - "actual": Actual resource usage
	Details map[string]string `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// For HASH_MISMATCH: expected hash (SHA-256 hex)
	ExpectedHash string `protobuf:"bytes,4,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"`
	// For HASH_MISMATCH: actual hash (SHA-256 hex)
	ActualHash    string `protobuf:"bytes,5,opt,name=actual_hash,json=actualHash,proto3" json:"actual_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WasmError) Reset() {
	*x = WasmError{}
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasmError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmError) ProtoMessage() {}

func (x *WasmError) ProtoReflect() protoreflect.Message {
	mi := &file_plexspaces_v1_wasm_wasm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmError.ProtoReflect.Descriptor instead.
func (*WasmError) Descriptor() ([]byte, []int) {
	return file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP(), []int{12}
}

func (x *WasmError) GetCode() WasmErrorCode {
	if x != nil {
		return x.Code
	}
	return WasmErrorCode_WASM_ERROR_CODE_OK
}

func (x *WasmError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WasmError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *WasmError) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

func (x *WasmError) GetActualHash() string {
	if x != nil {
		return x.ActualHash
	}
	return ""
}

var File_plexspaces_v1_wasm_wasm_proto protoreflect.FileDescriptor

const file_plexspaces_v1_wasm_wasm_proto_rawDesc = "" +
	"\n" +
	"\x1dplexspaces/v1/wasm/wasm.proto\x12\x12plexspaces.wasm.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aplexspaces/v1/common.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xc4\x03\n" +
	"\x10HttpFetchRequest\x12\x98\x01\n" +
	"\aheaders\x18\x01 \x03(\v21.plexspaces.wasm.v1.HttpFetchRequest.HeadersEntryBK\x92AE2CAdditional request headers merged with the configured service link.\xe0A\x02R\aheaders\x12a\n" +
	"\x04body\x18\x02 \x01(\fBM\x92A=2;Raw request body bytes encoded at the actor-world boundary.\xe0A\x02\xbaH\az\x05\x18\x80\x80\x80\x05R\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:v\x92As\n" +
	"q*\x10HttpFetchRequest2LActor-world outbound HTTP request metadata/body exchanged as protobuf bytes.\xd2\x01\aheaders\xd2\x01\x04body\"\x94\x04\n" +
	"\x11HttpFetchResponse\x12^\n" +
	"\x06status\x18\x01 \x01(\rBF\x92A624HTTP status code returned by the named service link.\xe0A\x02\xbaH\a*\x05\x18\xd7\x04(dR\x06status\x12\x8a\x01\n" +
	"\aheaders\x18\x02 \x03(\v22.plexspaces.wasm.v1.HttpFetchResponse.HeadersEntryB<\x92A624Response headers returned by the named service link.\xe0A\x02R\aheaders\x12a\n" +
	"\x04body\x18\x03 \x01(\fBM\x92A=2;Raw response body bytes returned by the named service link.\xe0A\x02\xbaH\az\x05\x18\x80\x80\x80\x05R\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:s\x92Ap\n" +
	"n*\x11HttpFetchResponse2?Actor-world outbound HTTP response exchanged as protobuf bytes.\xd2\x01\x06status\xd2\x01\aheaders\xd2\x01\x04body\"\x8b\x03\n" +
	"\n" +
	"WasmModule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fmodule_bytes\x18\x03 \x01(\fR\vmoduleBytes\x12\x1f\n" +
	"\vmodule_hash\x18\x04 \x01(\tR\n" +
	"moduleHash\x12#\n" +
	"\rwit_interface\x18\x05 \x01(\tR\fwitInterface\x12)\n" +
	"\x10source_languages\x18\x06 \x03(\tR\x0fsourceLanguages\x12:\n" +
	"\bmetadata\x18\a \x01(\v2\x1e.plexspaces.common.v1.MetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\t \x01(\x04R\tsizeBytes\x12%\n" +
	"\x0eversion_number\x18\n" +
	" \x01(\rR\rversionNumber\"\xa6\x02\n" +
	"\x0eResourceLimits\x12(\n" +
	"\x10max_memory_bytes\x18\x01 \x01(\x04R\x0emaxMemoryBytes\x12&\n" +
	"\x0fmax_stack_bytes\x18\x02 \x01(\x04R\rmaxStackBytes\x12\x19\n" +
	"\bmax_fuel\x18\x03 \x01(\x04R\amaxFuel\x12G\n" +
	"\x12max_execution_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x10maxExecutionTime\x12,\n" +
	"\x12max_table_elements\x18\x05 \x01(\rR\x10maxTableElements\x120\n" +
	"\x14max_pooled_instances\x18\x06 \x01(\rR\x12maxPooledInstances\"\x9c\x03\n" +
	"\x10WasmCapabilities\x12)\n" +
	"\x10allow_filesystem\x18\x01 \x01(\bR\x0fallowFilesystem\x12'\n" +
	"\x0ffilesystem_root\x18\x02 \x01(\tR\x0efilesystemRoot\x12#\n" +
	"\rallow_network\x18\x03 \x01(\bR\fallowNetwork\x12\x1b\n" +
	"\tallow_env\x18\x04 \x01(\bR\ballowEnv\x12!\n" +
	"\fallow_random\x18\x05 \x01(\bR\vallowRandom\x12!\n" +
	"\fallow_clocks\x18\x06 \x01(\bR\vallowClocks\x12)\n" +
	"\x10allow_tuplespace\x18\a \x01(\bR\x0fallowTuplespace\x12,\n" +
	"\x12allow_spawn_actors\x18\b \x01(\bR\x10allowSpawnActors\x12.\n" +
	"\x13allow_send_messages\x18\t \x01(\bR\x11allowSendMessages\x12#\n" +
	"\rallow_logging\x18\n" +
	" \x01(\bR\fallowLogging\"\x9a\x03\n" +
	"\n" +
	"WasmConfig\x12:\n" +
	"\x06limits\x18\x01 \x01(\v2\".plexspaces.wasm.v1.ResourceLimitsR\x06limits\x12H\n" +
	"\fcapabilities\x18\x02 \x01(\v2$.plexspaces.wasm.v1.WasmCapabilitiesR\fcapabilities\x12!\n" +
	"\fprofile_name\x18\x03 \x01(\tR\vprofileName\x12%\n" +
	"\x0eenable_pooling\x18\x04 \x01(\bR\renablePooling\x12\x1d\n" +
	"\n" +
	"enable_aot\x18\x05 \x01(\bR\tenableAot\x12-\n" +
	"\x12durability_enabled\x18\x06 \x01(\bR\x11durabilityEnabled\x12*\n" +
	"\x11use_instance_pool\x18\a \x01(\bR\x0fuseInstancePool\x12B\n" +
	"\x1dmax_concurrent_instantiations\x18\b \x01(\rR\x1bmaxConcurrentInstantiations\"\xb3\x02\n" +
	"\x17DeployWasmModuleRequest\x12;\n" +
	"\x06module\x18\x01 \x01(\v2\x1e.plexspaces.wasm.v1.WasmModuleB\x03\xe0A\x02R\x06module\x12V\n" +
	"\bpre_warm\x18\x02 \x01(\x0e2;.plexspaces.wasm.v1.DeployWasmModuleRequest.PreWarmStrategyR\apreWarm\x129\n" +
	"\x10target_node_tags\x18\x03 \x03(\tB\x0f\xbaH\f\x92\x01\t\x10d\"\x05r\x03\x18\x80\x01R\x0etargetNodeTags\"H\n" +
	"\x0fPreWarmStrategy\x12\b\n" +
	"\x04NONE\x10\x00\x12\f\n" +
	"\bANNOUNCE\x10\x01\x12\f\n" +
	"\bPUSH_ALL\x10\x02\x12\x0f\n" +
	"\vPUSH_TAGGED\x10\x03\"\xb4\x01\n" +
	"\x18DeployWasmModuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vmodule_hash\x18\x02 \x01(\tR\n" +
	"moduleHash\x12(\n" +
	"\x10nodes_pre_warmed\x18\x03 \x01(\rR\x0enodesPreWarmed\x123\n" +
	"\x05error\x18\x04 \x01(\v2\x1d.plexspaces.wasm.v1.WasmErrorR\x05error\"\xfe\x01\n" +
	"\x17InstantiateActorRequest\x12,\n" +
	"\n" +
	"module_ref\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\tmoduleRef\x12(\n" +
	"\bactor_id\x18\x02 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\aactorId\x12#\n" +
	"\rinitial_state\x18\x03 \x01(\fR\finitialState\x126\n" +
	"\x06config\x18\x04 \x01(\v2\x1e.plexspaces.wasm.v1.WasmConfigR\x06config\x12.\n" +
	"\x0etarget_node_id\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\ftargetNodeId\"\xd8\x01\n" +
	"\x18InstantiateActorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\x05error\x18\x05 \x01(\v2\x1d.plexspaces.wasm.v1.WasmErrorR\x05error\"\xd2\x01\n" +
	"\x13MigrateActorRequest\x12(\n" +
	"\bactor_id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\aactorId\x123\n" +
	"\x0esource_node_id\x18\x02 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\fsourceNodeId\x123\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\ftargetNodeId\x12'\n" +
	"\x0finclude_journal\x18\x04 \x01(\bR\x0eincludeJournal\"\xd1\x01\n" +
	"\x14MigrateActorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12@\n" +
	"\x0emigration_time\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rmigrationTime\x12(\n" +
	"\x10state_size_bytes\x18\x03 \x01(\x04R\x0estateSizeBytes\x123\n" +
	"\x05error\x18\x04 \x01(\v2\x1d.plexspaces.wasm.v1.WasmErrorR\x05error\"\xa4\x02\n" +
	"\tWasmError\x125\n" +
	"\x04code\x18\x01 \x01(\x0e2!.plexspaces.wasm.v1.WasmErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\adetails\x18\x03 \x03(\v2*.plexspaces.wasm.v1.WasmError.DetailsEntryR\adetails\x12#\n" +
	"\rexpected_hash\x18\x04 \x01(\tR\fexpectedHash\x12\x1f\n" +
	"\vactual_hash\x18\x05 \x01(\tR\n" +
	"actualHash\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xd7\x03\n" +
	"\rWasmErrorCode\x12\x16\n" +
	"\x12WASM_ERROR_CODE_OK\x10\x00\x12&\n" +
	"\"WASM_ERROR_CODE_COMPILATION_FAILED\x10\x01\x12(\n" +
	"$WASM_ERROR_CODE_INSTANTIATION_FAILED\x10\x02\x12+\n" +
	"'WASM_ERROR_CODE_RESOURCE_LIMIT_EXCEEDED\x10\x03\x12%\n" +
	"!WASM_ERROR_CODE_CAPABILITY_DENIED\x10\x04\x12'\n" +
	"#WASM_ERROR_CODE_HOST_FUNCTION_ERROR\x10\x05\x12(\n" +
	"$WASM_ERROR_CODE_ACTOR_FUNCTION_ERROR\x10\x06\x12\x1f\n" +
	"\x1bWASM_ERROR_CODE_CACHE_ERROR\x10\a\x12!\n" +
	"\x1dWASM_ERROR_CODE_HASH_MISMATCH\x10\b\x12$\n" +
	" WASM_ERROR_CODE_MODULE_NOT_FOUND\x10\t\x12'\n" +
	"#WASM_ERROR_CODE_SERIALIZATION_ERROR\x10\n" +
	"\x12\"\n" +
	"\x1eWASM_ERROR_CODE_WASMTIME_ERROR\x10\v2\xb9\x06\n" +
	"\x12WasmRuntimeService\x12\x85\x02\n" +
	"\fDeployModule\x12+.plexspaces.wasm.v1.DeployWasmModuleRequest\x1a,.plexspaces.wasm.v1.DeployWasmModuleResponse\"\x99\x01\x92Aw\n" +
	"\x12WasmRuntimeService\x12\x1bDeploy a WebAssembly module\x1aDRegisters a WebAssembly module and optionally pre-warms node caches.\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/wasm/modules\x12\x88\x02\n" +
	"\x10InstantiateActor\x12+.plexspaces.wasm.v1.InstantiateActorRequest\x1a,.plexspaces.wasm.v1.InstantiateActorResponse\"\x98\x01\x92Aw\n" +
	"\x12WasmRuntimeService\x12\x1fInstantiate a WebAssembly actor\x1a@Creates a new actor instance from a deployed WebAssembly module.\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/wasm/actors\x12\x8f\x02\n" +
	"\fMigrateActor\x12'.plexspaces.wasm.v1.MigrateActorRequest\x1a(.plexspaces.wasm.v1.MigrateActorResponse\"\xab\x01\x92Aw\n" +
	"\x12WasmRuntimeService\x12\x1bMigrate a WebAssembly actor\x1aDMoves an actor to another node using the runtime migration workflow.\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/wasm/actors/{actor_id}:migrateB\xb1\x03\x92A\xcf\x01\x12h\n" +
	"\x1bPlexSpaces WASM Runtime API\x12EDeployment and lifecycle APIs for the PlexSpaces WebAssembly runtime.2\x02v1jc\n" +
	"\x12WasmRuntimeService\x12MModule deployment, actor instantiation, and migration for WebAssembly actors.\n" +
	"\x16com.plexspaces.wasm.v1B\tWasmProtoP\x01ZOgithub.com/bhatti/PlexSpaces/sdks/go/plexspaces/proto/plexspaces/v1/wasm;wasmv1\xa2\x02\x03PWX\xaa\x02\x12Plexspaces.Wasm.V1\xca\x02\x12Plexspaces\\Wasm\\V1\xe2\x02\x1ePlexspaces\\Wasm\\V1\\GPBMetadata\xea\x02\x14Plexspaces::Wasm::V1b\x06proto3"

var (
	file_plexspaces_v1_wasm_wasm_proto_rawDescOnce sync.Once
	file_plexspaces_v1_wasm_wasm_proto_rawDescData []byte
)

func file_plexspaces_v1_wasm_wasm_proto_rawDescGZIP() []byte {
	file_plexspaces_v1_wasm_wasm_proto_rawDescOnce.Do(func() {
		file_plexspaces_v1_wasm_wasm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plexspaces_v1_wasm_wasm_proto_rawDesc), len(file_plexspaces_v1_wasm_wasm_proto_rawDesc)))
	})
	return file_plexspaces_v1_wasm_wasm_proto_rawDescData
}

var file_plexspaces_v1_wasm_wasm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plexspaces_v1_wasm_wasm_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_plexspaces_v1_wasm_wasm_proto_goTypes = []any{
	(WasmErrorCode)(0),                           // 0: plexspaces.wasm.v1.WasmErrorCode
	(DeployWasmModuleRequest_PreWarmStrategy)(0), // 1: plexspaces.wasm.v1.DeployWasmModuleRequest.PreWarmStrategy
	(*HttpFetchRequest)(nil),                     // 2: plexspaces.wasm.v1.HttpFetchRequest
	(*HttpFetchResponse)(nil),                    // 3: plexspaces.wasm.v1.HttpFetchResponse
	(*WasmModule)(nil),                           // 4: plexspaces.wasm.v1.WasmModule
	(*ResourceLimits)(nil),                       // 5: plexspaces.wasm.v1.ResourceLimits
	(*WasmCapabilities)(nil),                     // 6: plexspaces.wasm.v1.WasmCapabilities
	(*WasmConfig)(nil),                           // 7: plexspaces.wasm.v1.WasmConfig
	(*DeployWasmModuleRequest)(nil),              // 8: plexspaces.wasm.v1.DeployWasmModuleRequest
	(*DeployWasmModuleResponse)(nil),             // 9: plexspaces.wasm.v1.DeployWasmModuleResponse
	(*InstantiateActorRequest)(nil),              // 10: plexspaces.wasm.v1.InstantiateActorRequest
	(*InstantiateActorResponse)(nil),             // 11: plexspaces.wasm.v1.InstantiateActorResponse
	(*MigrateActorRequest)(nil),                  // 12: plexspaces.wasm.v1.MigrateActorRequest
	(*MigrateActorResponse)(nil),                 // 13: plexspaces.wasm.v1.MigrateActorResponse
	(*WasmError)(nil),                            // 14: plexspaces.wasm.v1.WasmError
	nil,                                          // 15: plexspaces.wasm.v1.HttpFetchRequest.HeadersEntry
	nil,                                          // 16: plexspaces.wasm.v1.HttpFetchResponse.HeadersEntry
	nil,                                          // 17: plexspaces.wasm.v1.WasmError.DetailsEntry
	(*v1.Metadata)(nil),                          // 18: plexspaces.common.v1.Metadata
	(*timestamppb.Timestamp)(nil),                // 19: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                  // 20: google.protobuf.Duration
}
var file_plexspaces_v1_wasm_wasm_proto_depIdxs = []int32{
	15, // 0: plexspaces.wasm.v1.HttpFetchRequest.headers:type_name -> plexspaces.wasm.v1.HttpFetchRequest.HeadersEntry
	16, // 1: plexspaces.wasm.v1.HttpFetchResponse.headers:type_name -> plexspaces.wasm.v1.HttpFetchResponse.HeadersEntry
	18, // 2: plexspaces.wasm.v1.WasmModule.metadata:type_name -> plexspaces.common.v1.Metadata
	19, // 3: plexspaces.wasm.v1.WasmModule.created_at:type_name -> google.protobuf.Timestamp
	20, // 4: plexspaces.wasm.v1.ResourceLimits.max_execution_time:type_name -> google.protobuf.Duration
	5,  // 5: plexspaces.wasm.v1.WasmConfig.limits:type_name -> plexspaces.wasm.v1.ResourceLimits
	6,  // 6: plexspaces.wasm.v1.WasmConfig.capabilities:type_name -> plexspaces.wasm.v1.WasmCapabilities
	4,  // 7: plexspaces.wasm.v1.DeployWasmModuleRequest.module:type_name -> plexspaces.wasm.v1.WasmModule
	1,  // 8: plexspaces.wasm.v1.DeployWasmModuleRequest.pre_warm:type_name -> plexspaces.wasm.v1.DeployWasmModuleRequest.PreWarmStrategy
	14, // 9: plexspaces.wasm.v1.DeployWasmModuleResponse.error:type_name -> plexspaces.wasm.v1.WasmError
	7,  // 10: plexspaces.wasm.v1.InstantiateActorRequest.config:type_name -> plexspaces.wasm.v1.WasmConfig
	19, // 11: plexspaces.wasm.v1.InstantiateActorResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 12: plexspaces.wasm.v1.InstantiateActorResponse.error:type_name -> plexspaces.wasm.v1.WasmError
	20, // 13: plexspaces.wasm.v1.MigrateActorResponse.migration_time:type_name -> google.protobuf.Duration
	14, // 14: plexspaces.wasm.v1.MigrateActorResponse.error:type_name -> plexspaces.wasm.v1.WasmError
	0,  // 15: plexspaces.wasm.v1.WasmError.code:type_name -> plexspaces.wasm.v1.WasmErrorCode
	17, // 16: plexspaces.wasm.v1.WasmError.details:type_name -> plexspaces.wasm.v1.WasmError.DetailsEntry
	8,  // 17: plexspaces.wasm.v1.WasmRuntimeService.DeployModule:input_type -> plexspaces.wasm.v1.DeployWasmModuleRequest
	10, // 18: plexspaces.wasm.v1.WasmRuntimeService.InstantiateActor:input_type -> plexspaces.wasm.v1.InstantiateActorRequest
	12, // 19: plexspaces.wasm.v1.WasmRuntimeService.MigrateActor:input_type -> plexspaces.wasm.v1.MigrateActorRequest
	9,  // 20: plexspaces.wasm.v1.WasmRuntimeService.DeployModule:output_type -> plexspaces.wasm.v1.DeployWasmModuleResponse
	11, // 21: plexspaces.wasm.v1.WasmRuntimeService.InstantiateActor:output_type -> plexspaces.wasm.v1.InstantiateActorResponse
	13, // 22: plexspaces.wasm.v1.WasmRuntimeService.MigrateActor:output_type -> plexspaces.wasm.v1.MigrateActorResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_plexspaces_v1_wasm_wasm_proto_init() }
func file_plexspaces_v1_wasm_wasm_proto_init() {
	if File_plexspaces_v1_wasm_wasm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plexspaces_v1_wasm_wasm_proto_rawDesc), len(file_plexspaces_v1_wasm_wasm_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plexspaces_v1_wasm_wasm_proto_goTypes,
		DependencyIndexes: file_plexspaces_v1_wasm_wasm_proto_depIdxs,
		EnumInfos:         file_plexspaces_v1_wasm_wasm_proto_enumTypes,
		MessageInfos:      file_plexspaces_v1_wasm_wasm_proto_msgTypes,
	}.Build()
	File_plexspaces_v1_wasm_wasm_proto = out.File
	file_plexspaces_v1_wasm_wasm_proto_goTypes = nil
	file_plexspaces_v1_wasm_wasm_proto_depIdxs = nil
}
